---
permalink: iscsi-config-esxi/index.html 
sidebar: sidebar 
keywords: iscsi, service, storage, virtual, machine, svm, provision, lun, esx, host, computer 
summary: 使用 ONTAP System Manager 经典界面（ ONTAP 9.7 及更早版本），您可以在 Storage Virtual Machine （ SVM ）上快速设置 iSCSI 服务，配置 LUN 并使用 ESXi 主机计算机上的 iSCSI 启动程序使 LUN 可用。 
---
= 使用 VSC 为 ESXi 配置 iSCSI 概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 ONTAP System Manager 经典界面（ ONTAP 9.7 及更早版本），您可以在 Storage Virtual Machine （ SVM ）上快速设置 iSCSI 服务，配置 LUN 并使用 ESXi 主机计算机上的 iSCSI 启动程序使 LUN 可用。

在以下情况下使用此操作步骤：

* 您正在 ESXi 5.x 上使用原生 ESXi iSCSI 软件启动程序
* 您未对 iSCSI 使用 CHAP 身份验证。
* 您正在使用受支持版本的适用于 VMware vSphere 的 Virtual Storage Console （ VSC ）为 ESX 主机配置存储设置。
+
** 从 VSC 7.0 开始， VSC 属于 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["适用于 VMware vSphere 的 ONTAP 工具"^] 虚拟设备，包括适用于 VMware vSphere 的 VSC ， vStorage APIs for Storage Awareness （ VASA ） Provider 和 Storage Replication Adapter （ SRA ）功能。
** 请务必检查 https://imt.netapp.com/matrix/["NetApp 互操作性表工具"^] 以确认当前 ONTAP 版本与 VSC 版本之间的兼容性。


* 您的网络使用 IPv4 地址。
* 您希望使用以下任一方法为逻辑接口分配地址：
+
** 自动从您定义的子网
** 手动，使用从现有子网中选择的地址
** 手动，使用要添加到现有子网的地址


* 集群中的每个节点上至少有两个可用的高速以太网端口（至少 1 GbE ，建议使用 10 GbE ）。
+
板载UTA2 (也称为 `CNA`)端口是可配置的。您可以在 ONTAP 命令行界面中配置这些端口；此过程不在其操作步骤中介绍。

+
请参见 link:https://docs.netapp.com/us-en/ontap/networking/index.html["网络管理"^] 用于使用 CLI 配置以太网端口流量控制。

* 您未配置 iSCSI SAN 启动。
* 您正在通过 ESXi 虚拟机管理程序为 VM 提供存储，而不是在 VM 中运行 iSCSI 启动程序。


有关详细信息，请参见 https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597 ：适用于 ONTAP 的 VMware vSphere"^] 以及适用于您的 VSC 版本的文档。
