---
permalink: online-help-96-97/concept_shares.html 
sidebar: sidebar 
keywords: online, help, share, system, manager, qtress, cifs, create, edit, manage, share, access, stop, home, directory, configure, smb 
summary: 您可以使用 System Manager 创建，编辑和管理共享。 
---
= 使用 System Manager 管理共享— ONTAP 9.7 及更早版本
:allow-uri-read: 


您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）创建，编辑和管理共享。



== 创建 CIFS 共享

您可以使用 System Manager 创建 CIFS 共享，以便指定 CIFS 用户可以访问的文件夹， qtree 或卷。

.开始之前
在设置和启动 CIFS 之前，您必须已安装 CIFS 许可证。

.步骤
. 单击 * 存储 * > * 共享 * 。
. 从 * SVM* 字段的下拉菜单中，选择要在其中创建 CIFS 共享的 SVM 。
. 单击 * 创建共享 * 。
. 在 * 创建共享 * 窗口中，单击 * 浏览 * ，然后选择应共享的文件夹， qtree 或卷。
. 指定新 CIFS 共享的名称。
. *可选：*选中*为Hyper-V和SQL*启用持续可用性复选框、以允许支持SMB 3.0及更高版本的客户端在无中断运行期间持久打开文件。
+
使用此选项打开的文件不会受到故障转移，交还和 LIF 迁移等中断事件的影响。

+
从 System Manager 9.6 开始， FlexGroup 卷支持持续可用性。

. 选中 * 访问此共享时加密数据 * 复选框以启用 SMB 3.0 加密。
. 为共享提供问题描述或注释，然后单击 * 创建 * 。


.结果
此时将创建 CIFS 共享，并在组中将访问权限设置为 "`Full Control for Everyone` " 。



== 停止共享访问

如果要删除对文件夹， qtree 或卷的共享网络访问权限，可以使用 System Manager 停止共享。

.开始之前
您必须已安装 CIFS 许可证。

.步骤
. 单击 * 存储 * > * 共享 * 。
. 从 * SVM* 字段的下拉菜单中，选择要停止的 CIFS 共享所在的 SVM 。
. 从共享列表中，选择要停止共享的共享，然后单击 * 停止共享 * 。
. 选中确认复选框，然后单击 * 停止 * 。
. 确认共享不再列在 * 共享 * 窗口中。




== 创建主目录共享

您可以使用 System Manager 创建主目录共享并管理主目录搜索路径。

.开始之前
必须设置并启动 CIFS 。

.步骤
. 单击 * 存储 * > * 共享 * 。
. 单击 * 创建主目录 * ，然后提供用于确定用户如何映射到目录的模式信息。
. 单击 * 创建 * 。
. 验证您创建的主目录是否已列在 * 共享 * 窗口中。




== 编辑共享设置

您可以使用 System Manager 修改共享的设置，例如符号链接设置，用户或组的共享访问权限以及对共享的访问类型。您还可以启用或禁用通过 Hyper-V 持续提供共享，以及启用或禁用基于访问的枚举（ ABE ）。从 System Manager 9.6 开始， FlexGroup 卷支持持续可用性。

.步骤
. 单击 * 存储 * > * 共享 * 。
. 从共享列表中选择要修改的共享，然后单击 * 编辑 * 。
. 在 * 编辑共享设置 * 对话框中，根据需要修改共享设置：
+
.. 在 * 常规 * 选项卡中，通过 Hyper-V 启用共享的持续可用性
+
启用持续可用性可以使 SMB 3.0 和支持 SMB 3.0 的客户端在无中断运行期间持久打开文件。持久打开的文件不会受到故障转移，交还和 LIF 迁移等中断事件的影响。

.. 在 * 权限 * 选项卡中，添加用户或组，然后分配权限以指定访问类型。
.. 在 * 选项 * 选项卡中，选择所需选项。


. 单击 * 保存并关闭 * 。
. 在 * 共享 * 窗口中验证您对选定共享所做的更改。




== ONTAP 如何启用动态主目录

通过 ONTAP 主目录，您可以配置一个 SMB 共享，该共享根据连接到它的用户和一组变量映射到不同的目录。您可以使用一些主目录参数配置一个共享，以定义入口点（共享）与主目录（ SVM 上的目录）之间的用户关系，而不是为每个用户创建单独的共享。

以来宾用户身份登录的用户没有主目录，无法访问其他用户的主目录。可通过四个变量确定用户映射到目录的方式：

* * 共享名称 *
+
这是您创建的共享的名称，用户将连接到该共享。您必须为此共享设置主目录属性。

+
共享名称可以使用以下动态名称：

+
** `%w` (用户的Windows用户名)
** `%d` (用户的Windows域名)
** `%u` (用户的映射UNIX用户名)


+
要使共享名称在所有主目录中都是唯一的、共享名称必须包含/`%w` 或 `%u` 变量。共享名称可以同时包含 `%d` 和/`%w` 变量(例如、 `%d`/`%w`)、或者共享名称可以包含静态部分和可变部分(例如、HOME_/`%w`）。

* * 共享路径 *
+
此路径是由共享定义的相对路径，因此与某个共享名称关联，并附加到每个搜索路径中，以便从 SVM 的根目录生成用户的整个主目录路径。它可以是静态的(例如、 `home`)、动态(例如、 `%w`)或两者的组合(例如、 `eng/%w`）。

* * 搜索路径 *
+
这是从 SVM 根目录开始的一组绝对路径，您可以指定这些绝对路径来指示 ONTAP 搜索主目录。您可以使用指定一个或多个搜索路径 `vserver cifs home-directory search-path add` 命令：如果指定了多个搜索路径，则 ONTAP 将按指定顺序尝试这些路径，直到找到有效路径为止。

* * 目录 *
+
这是您为用户创建的用户主目录。目录名称通常是用户的名称。您必须在搜索路径定义的一个目录中创建主目录。



例如，请考虑以下设置：

* 用户： John Smith
* 用户域： acme
* 用户名： jsmith
* SVM 名称： vs1
* 主目录共享名称1：HOME_ `%w` -共享路径： `%w`
* 主目录共享名称2： `%w` -共享路径： `%d/%w`
* 搜索路径1： `/vol0home/home`
* 搜索路径2： `/vol1home/home`
* 搜索路径3： `/vol2home/home`
* 主目录： `/vol1home/home/jsmith`


场景1：用户连接到 `\\vs1\home_jsmith`。这与第一个主目录共享名称匹配并生成相对路径 `jsmith`。现在、ONTAP将搜索名为的目录 `jsmith` 按顺序检查每个搜索路径：

* `/vol0home/home/jsmith` 不存在；继续搜索路径2。
* `/vol1home/home/jsmith` 存在；因此、不会检查搜索路径3；用户现在已连接到其主目录。


场景2：用户连接到 `\\vs1\jsmith`。这与第二个主目录共享名称匹配并生成相对路径 `acme/jsmith`。现在、ONTAP将搜索名为的目录 `acme/jsmith` 按顺序检查每个搜索路径：

* `/vol0home/home/acme/jsmith` 不存在；继续搜索路径2。
* `/vol1home/home/acme/jsmith` 不存在；继续搜索路径3。
* `/vol2home/home/acme/jsmith` 不存在；主目录不存在；因此连接失败。




== 共享窗口

您可以使用共享窗口管理共享并查看有关共享的信息。



=== 命令按钮

* * 创建共享 *
+
打开创建共享对话框，在此可以创建共享。

* * 创建主目录 *
+
打开创建主目录共享对话框，在此可以创建新的主目录共享。

* * 编辑 * 。
+
打开编辑设置对话框，在此可以修改选定共享的属性。

* * 停止共享 *
+
停止共享选定对象。

* * 刷新 *
+
更新窗口中的信息。





=== 共享列表

共享列表显示每个共享的名称和路径。

* * 共享名称 *
+
显示共享的名称。

* * 路径 *
+
显示共享的现有文件夹， qtree 或卷的完整路径名。路径分隔符可以是反斜线或正斜线，但 ONTAP 会将所有路径分隔符显示为正斜线。

* * 主目录 *
+
显示主目录共享的名称。

* * 注释 *
+
显示共享的其他说明（如果有）。

* * 持续可用共享 *
+
显示是否为共享启用了持续可用性。从 System Manager 9.6 开始， FlexGroup 卷支持持续可用性。





=== 详细信息区域

共享列表下方的区域显示每个共享的共享属性和访问权限。

* * 属性 *
+
** Name
+
显示共享的名称。

** 机会锁状态
+
指定共享是否使用机会锁（ oplock ）。

** 可浏览
+
指定 Windows 客户端是否可以浏览共享。

** 显示 Snapshot
+
指定客户端是否可以查看 Snapshot 副本。

** 持续可用的共享
+
指定是启用还是禁用共享以实现持续可用性。从 System Manager 9.6 开始， FlexGroup 卷支持持续可用性。

** 基于访问的枚举
+
指定共享上是启用还是禁用基于访问的枚举（ ABE ）。

** BranchCache
+
指定共享上是启用还是禁用 BranchCache 。

** SMB 加密
+
指定是在 Storage Virtual Machine （ SVM ）级别还是在共享级别启用使用 SMB 3.0 的数据加密。如果在 SVM 级别启用了 SMB 加密，则 SMB 加密适用于所有共享，并且此值显示为已启用（在 SVM 级别）。

** 先前版本
+
指定是否可以从客户端查看和还原先前的版本。



* * 共享访问控制 *
+
显示共享的域用户，域组，本地用户和本地组的访问权限。



* 相关信息 *

xref:task_setting_up_cifs.adoc[正在设置CIFS]
