---
permalink: online-help-96-97/concept_protection_policies.html 
sidebar: sidebar 
keywords: online, help, protection, policy, system, manager, create, edit, delete 
summary: 您可以使用 System Manager 创建，编辑和删除保护策略。 
---
= 使用System Manager - ONTAP 9.7及更早版本管理保护策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP System Manager classic (适用于ONTAP 9.7及更早版本)创建、编辑和删除保护策略。



== 创建保护策略

您可以使用 System Manager 创建集群级别异步镜像策略，存储策略或镜像和存储策略，并将这些策略应用于集群级别的数据保护关系。

.步骤
. 单击 * 保护 * > * 保护策略 * 。
. 单击 * 创建 * 。
. 在 * 创建策略 * 对话框中，选择要创建的策略类型。
. 指定策略名称和传输优先级。
+
low 表示传输的优先级最低。低优先级传输通常计划在正常优先级传输之后进行。默认情况下，传输优先级设置为正常。

. *可选：*选中*启用网络压缩*复选框以压缩数据传输期间传输的数据。
. *可选：*对于异步镜像策略、选中*传输所有源Snapshot副本*复选框以在镜像策略中包含"`all_source_snapshots`"规则、该规则可从源卷备份所有Snapshot副本。
. *可选：*单击*添加注释*为策略添加其他注释。
. 对于存储策略或镜像存储策略，请指定 SnapMirror 标签和目标保留计数。
. 单击 * 创建 * 。




== 保护策略窗口

您可以使用保护策略窗口创建，管理和显示有关镜像，存储和镜像存储策略的信息。



=== 命令按钮

* * 创建 * 。
+
打开创建策略对话框，在此可以创建镜像，存储或镜像存储策略。

* * 编辑 * 。
+
打开编辑策略对话框，在此可以编辑策略。

* * 删除 *
+
打开删除策略对话框，在此可以删除策略。

* * 刷新 *
+
更新窗口中的信息。





=== 保护策略列表

* * 名称 *
+
显示保护策略的名称。

* * 类型 *
+
显示策略类型，可以是存储，镜像存储或异步镜像。

* * 注释 *
+
显示为策略指定的问题描述。

* * 传输优先级 *
+
显示数据传输优先级，例如 " 正常 " 或 " 低 " 。





=== 详细信息区域

* * 策略详细信息选项卡 *
+
显示保护策略的详细信息，例如创建该策略的用户，规则数量，保留数量以及网络压缩状态。

* * 策略规则选项卡 *
+
显示应用于策略的规则的详细信息。只有当选定策略包含规则时，才会显示策略规则选项卡。


