---
permalink: online-help-96-97/concept_efficiency_policies.html 
sidebar: sidebar 
keywords: efficiency, policy, system, manager, create, edit, delete, online, help, flexvol, window 
summary: 您可以使用 System Manager 创建，编辑和删除效率策略。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本管理效率策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）创建，编辑和删除效率策略。



== 添加效率策略

您可以使用 System Manager 添加效率策略，以便按指定计划或在卷数据更改达到指定阈值时对卷运行重复数据删除操作。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 策略 * 窗格中，单击 * 效率策略 * 。
. 单击 * 添加 * ，然后指定策略名称。
. 指定存储效率策略的运行方式：
+
** 选择 * 计划 * ，然后指定计划名称和计划详细信息。
+
如果需要，您可以指定效率策略的最长运行时持续时间。

** 选择 * 更改日志阈值 * ，然后指定卷数据更改的阈值（以百分比表示）。


. *可选：*选中*将QoS策略设置为后台*复选框以减少对客户端操作的性能影响。
. 单击 * 添加 * 。




== 编辑效率策略

您可以使用 System Manager 修改效率策略的属性，例如策略名称，计划名称和最长运行时间。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 策略 * 窗格中，单击 * 效率策略 * 。
. 在 * 效率策略 * 窗口中，选择要编辑的策略，然后单击 * 编辑 * 。
. 在 * 编辑效率策略 * 对话框中，进行所需的更改。
. 单击 * 保存 * 。




== 删除效率策略

您可以使用 System Managerto 删除不再需要的效率策略。

.开始之前
必须禁用效率策略。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 策略 * 窗格中，单击 * 效率策略 * 。
. 选择要删除的效率策略，然后单击 * 删除 * 。
. 选中确认复选框，然后单击 * 删除 * 。




== 启用或禁用效率策略

您可以使用 System Manager 启用或禁用效率策略。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 策略 * 窗格中，单击 * 效率策略 * 。
. 选择一个或多个要启用或禁用的效率策略。
. 根据需要单击 * 状态 * > * 启用 * 或 * 状态 * > * 禁用 * 。
. 如果要禁用效率策略，请选中确认复选框，然后单击 * 确定 * 。




== 什么是效率策略

效率策略是指在 FlexVol 卷上执行重复数据删除操作的作业计划。

您可以通过将操作计划为在特定时间启动或指定在超过阈值百分比时触发操作来在 FlexVol 卷上运行重复数据删除。您可以通过创建包含在效率策略中的作业计划来计划重复数据删除操作。卷效率策略仅支持 cron 类型的作业计划。或者，您也可以指定阈值百分比。如果新数据超过指定百分比，则会启动重复数据删除操作。



== 了解预定义的效率策略

您可以为卷配置效率策略，以节省更多空间。您可以将卷配置为运行实时压缩，而无需在卷上配置计划的或手动启动的后台效率操作。

创建 SVM 时，系统会自动创建以下效率策略，并且无法删除这些策略：

* Default
+
您可以使用效率策略配置卷，以便在卷上运行计划的重复数据删除操作。

* 仅实时
+
您可以为卷配置仅实时效率策略并启用实时压缩，以便在卷上运行实时压缩，而无需执行任何计划的或手动启动的后台效率操作。



有关仅实时和默认效率策略的详细信息，请参见手册页。



== 效率策略窗口

您可以使用效率策略窗口创建，显示和管理有关效率策略的信息。



=== 命令按钮

* * 添加 * 。
+
打开添加效率策略对话框，在此可以在指定的持续时间（基于计划）或卷数据更改达到指定阈值（基于阈值）时对卷运行重复数据删除操作。

* * 编辑 * 。
+
打开编辑效率策略对话框，在此可以修改重复数据删除操作的计划，阈值， QoS 类型和最长运行时间。

* * 删除 *
+
打开删除效率策略对话框，在此可以删除选定的效率策略。

* * 状态 *
+
打开下拉菜单，其中提供了用于启用或禁用选定效率策略的选项。

* * 刷新 *
+
更新窗口中的信息。





=== 效率策略列表

* * 自动 *
+
指定在后台持续执行重复数据删除。此策略适用于所有新创建的卷以及尚未手动配置后台重复数据删除的所有升级卷。如果将此策略更改为`default`或任何其他策略、则会禁用"`auto`"策略。

+
如果卷从非AFF系统移至AFF 系统、则默认情况下、目标节点上会启用"`auto`"策略。如果卷从AFF 节点移至非AFF节点、则默认情况下、目标节点上的"`auto`"策略将替换为"`inline-only`"策略。

* * 策略 *
+
指定效率策略的名称。

* * 状态 *
+
指定效率策略的状态。状态可以是以下状态之一：

+
** enabled
+
指定可以将效率策略分配给重复数据删除操作。

** 已禁用
+
指定已禁用效率策略。您可以使用状态下拉菜单启用此策略，并稍后将其分配给重复数据删除操作。



* * 运行者 *
+
指定存储效率策略是根据计划运行还是根据阈值（更改日志阈值）运行。

* * QoS 策略 *
+
指定存储效率策略的 QoS 类型。QoS 类型可以是以下类型之一：

+
** 背景
+
指定 QoS 策略在后台运行，这样可以减少对客户端操作的潜在性能影响。

** 尽力而为
+
指定 QoS 策略正在尽力而为的基础上运行，这样可以最大限度地提高系统资源的利用率。



* * 最大运行时间 *
+
指定效率策略的最长运行时持续时间。如果未指定此值，则效率策略将一直运行，直到操作完成为止。





=== 详细信息区域

效率策略列表下方的区域显示有关选定效率策略的追加信息，包括基于计划的策略的计划名称和计划详细信息以及基于阈值的策略的阈值。
