---
permalink: online-help-96-97/concept_what_nvme_subsystem_is.html 
sidebar: sidebar 
keywords: nvme, subsystem, fc, rdma, transport, port, vserver, online, help, controller, cluster, table, settings, manage 
summary: NVMe 子系统包括一个或多个控制器，一个或多个命名空间，一个或多个非易失性内存（ NVM ）子系统端口（ FC-NVMe 或 RDMA 传输端口），一个 NVM 存储介质以及一个控制器和 NVM 存储介质之间的接口。对于控制器映射和管理， NVM 子系统会映射到 ONTAP 中的 SVM 。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本管理 NVMe 子系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）创建和管理 NVMe 子系统。您可以将 NVMe 子系统与 SVM 中的不同主机和命名空间相关联。此外，每个 Vserver 可以支持多个 NVMe 子系统。但是，您不能将 NVMe 子系统配置为在多个 SVM 上使用。



== 创建 NVMe 子系统

您可以使用 System Manager 创建 NVMe 子系统。

.步骤
. 单击 * NVMe 子系统 * 窗口中的 * 创建 * 。
. 在 * NVMe 子系统： cree* 窗口中为以下字段提供条目：
+
** * SVM*
+
从下拉菜单中，选择要创建子系统的 SVM 。

** * 名称 *
+
输入子系统的名称。此子系统名称不能已存在于 SVM 中。此名称区分大小写，并且不能超过 96 个字符。允许使用特殊字符。

** *主机操作系统*
+
从下拉菜单中，选择子系统的主机操作系统类型。

** *主机NQN*
+
输入连接到控制器的主机 NQN 。您可以输入多个主机 NQN ，方法是使用逗号分隔这些 NQN 。



. 单击 * 保存 * 。
+
此时将创建 NVMe 子系统，并显示 NVMe 子系统窗口。





== 编辑 NVMe 子系统详细信息

您可以使用 System Manager 编辑 NVMe 子系统的详细信息。

.步骤
. 在 * NVMe 子系统 * 窗口中找到要编辑的 NVMe 子系统。
. 选中要编辑的子系统名称左侧的框。
. 单击 * 编辑 * 。
+
NVMe 子系统的当前详细信息显示在 NVMe 子系统：编辑窗口中。

. 您只能修改 * 主机 NQN* 字段中的信息。
+
** *主机NQN*
+
修改连接到控制器的主机 NQN 。您可以输入多个主机 NQN ，方法是使用逗号分隔这些 NQN 。



+
"* 关联的 NVMe 命名空间 * " 表显示在主机 NQN 字段下方。对于每个命名空间，该表列出了命名空间路径和命名空间 ID 。

. 单击 * 保存 * 。
+
此时将更新 NVMe 子系统详细信息，并显示 NVMe 子系统窗口。





== 删除 NVMe 子系统

您可以使用 System Manager 从集群中删除 NVMe 子系统。

.关于此任务
删除 NVMe 子系统时会执行以下操作：

* 如果 NVMe 子系统已配置主机，则映射的主机将被删除。
* 如果 NVMe 子系统已映射命名空间，则这些命名空间将取消映射。


.步骤
. 在 * NVMe 子系统 * 窗口中找到要删除的 NVMe 子系统。
. 选中要删除的子系统名称左侧的框。
. 单击 * 删除 * 。
+
此时将显示警告消息。

. 单击 * 删除 NVMe 子系统 * 复选框以确认删除，然后单击 * 是 * 。
+
此时将从集群中删除 NVMe 子系统，并显示 NVMe 子系统窗口。





== NVMe 子系统窗口

默认情况下， NVMe 子系统窗口会显示集群中 NVMe 子系统的清单列表。您可以对列表进行筛选，以便仅显示特定于 SVM 的子系统。此窗口还可用于创建，编辑或删除 NVMe 子系统。您可以通过选择 * 存储 * > * NVMe* > * 子系统 * 来访问此窗口。

* <<NVMe 子系统表>>
* <<工具栏>>




=== NVMe 子系统表

NVMe 子系统表列出了集群中 NVMe 子系统的清单。您可以使用 * SVM* 字段中的下拉菜单选择一个 SVM 以仅显示与该 SVM 关联的 NVMe 子系统来细化此列表。通过 * 搜索 * 字段和 * 筛选 * 下拉菜单，您可以进一步自定义此列表。

NVMe 子系统表包含以下列：

* * （复选框） *
+
用于指定要对其执行操作的子系统。

+
单击复选框以选择子系统，然后在工具栏中单击要执行的操作。

* * 名称 *
+
显示子系统的名称。

+
您可以通过在 * 搜索 * 字段中输入子系统名称来搜索子系统。

* *主机操作系统*
+
显示与子系统关联的主机操作系统的名称。

* *主机NQN*
+
显示连接到控制器的 NVMe 限定名称（ NQN ）。如果显示多个 NQN ，则它们以逗号分隔。

* * 关联的 NVMe 命名空间 *
+
显示与子系统关联的 NVM 命名空间的数量。您可以将鼠标悬停在该数字上以显示关联的命名空间路径。单击某个路径以显示命名空间详细信息窗口。





=== 工具栏

工具栏位于列标题上方。您可以使用工具栏中的字段和按钮执行各种操作。

* * 搜索 *
+
用于搜索 * 名称 * 列中可能存在的值。

* * 筛选 *
+
用于从下拉菜单中选择各种筛选列表的方法。

* * 创建 * 。
+
打开创建 NVMe 子系统对话框，在此可以创建 NVMe 子系统。

* * 编辑 * 。
+
打开编辑 NVMe 子系统对话框，在此可以编辑现有 NVMe 子系统。

* * 删除 *
+
打开删除 NVMe 子系统确认对话框，在此可以删除现有 NVMe 子系统。


