---
permalink: online-help-96-97/concept_quotas.html 
sidebar: sidebar 
keywords: system, manager, quota, online, help, view, activate, deactivate, information, types, targets, default, limits, space, files, manage, tree, group 
summary: 您可以使用 System Manager 创建，编辑和删除配额。 
---
= 使用 System Manager — ONTAP 9.7 及更早版本管理配额
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）创建，编辑和删除配额。



== 创建配额

通过配额，您可以限制或跟踪用户，组或 qtree 使用的磁盘空间和文件数。您可以使用 System Manager 中的添加配额向导创建配额并将配额应用于特定卷或 qtree 。

.关于此任务
使用 System Manager ，可以为配额可以拥有的文件数的硬限制和软限制指定的最小值为 1000 。如果要指定低于 1000 的值，应使用命令行界面（ CLI ）。

.步骤
. 单击 * 存储 * > * 配额 * 。
. 从 * SVM* 字段的下拉菜单中，选择要创建配额的 Storage Virtual Machine （ SVM ）。
. 在 * 用户定义的配额 * 选项卡中，单击 * 创建 * 。
+
此时将显示创建配额向导。

. 根据向导的提示键入或选择信息。
. 确认详细信息，然后单击 * 完成 * 完成向导。




=== 下一步操作

您可以使用本地用户名或 RID 创建用户配额。如果使用用户名或组名称创建用户配额或组配额、则为 ``/etc/passwd``文件和``/etc/group``文件必须分别更新。



== 删除配额

当用户及其存储要求和限制发生变化时，您可以使用 System Manager 删除一个或多个配额。

.步骤
. 单击 * 存储 * > * 配额 * 。
. 从 * SVM* 字段的下拉菜单中，选择要删除的配额所在的 Storage Virtual Machine （ SVM ）。
. 选择要删除的一个或多个配额，然后单击 * 删除 * 。
. 选中确认复选框，然后单击 * 删除 * 。




== 编辑配额限制

您可以使用 System Manager 编辑磁盘空间阈值，配额目标可以使用的磁盘空间量硬限制和软限制，以及配额目标可以拥有的文件数量硬限制和软限制。

.步骤
. 单击 * 存储 * > * 配额 * 。
. 从 * SVM* 字段的下拉菜单中，选择要编辑的配额所在的 Storage Virtual Machine （ SVM ）。
. 选择要编辑的配额，然后单击 * 编辑限制 * 。
. 在 * 编辑限制 * 对话框中，根据需要编辑配额设置。
+
可以为配额可以拥有的文件数的硬限制和软限制指定的最小值为 100 。如果要指定低于100的值、应使用命令行界面(CLI)。

. 单击 * 保存并关闭 * 。
. 在 * 用户定义的配额 * 选项卡中验证对选定配额所做的更改。




== 激活或停用配额

您可以使用 System Manager 在存储系统上选择的一个或多个卷上激活或停用配额。当用户及其存储要求和限制发生变化时，您可以激活或停用配额。

.步骤
. 单击 * 存储 * > * 配额 * 。
. 从 SVM 字段的下拉菜单中选择要激活或停用的配额所在的 Storage Virtual Machine （ SVM ）。
. 在 * 卷上的配额状态 * 选项卡中，选择要激活或停用配额的一个或多个卷。
. 根据需要单击 * 激活 * 或 * 停用 * 。
. 如果要停用配额，请选中确认复选框，然后单击 * 确定 * 。
. 在 * 状态 * 列中验证卷的配额状态。




== 调整配额大小

您可以使用 System Manager 中的调整配额大小对话框调整指定卷中的活动配额，以使其反映您对配额所做的更改。

.开始之前
必须为要调整配额大小的卷启用配额。

.步骤
. 单击 * 存储 * > * 配额 * 。
. 在 * 配额 * 窗口的 * 卷上的配额状态 * 选项卡中，选择要调整配额大小的一个或多个卷。
. 单击 * 调整大小 * 。




== 查看配额信息

您可以使用 System Manager 中的配额窗口查看配额详细信息，例如应用配额的卷和 qtree ，配额类型，应用配额的用户或组以及空间和文件使用量。

.步骤
. 单击 * 存储 * > * 配额 * 。
. 从 * SVM* 字段的下拉菜单中，选择要查看其相关信息的配额所在的 Storage Virtual Machine （ SVM ）。
. 执行相应的操作：
+
[cols="1a,1a"]
|===
| 条件 | 那么 ... 


 a| 
您希望查看已创建的所有配额的详细信息
 a| 
单击 * 用户定义的配额 * 选项卡。



 a| 
您希望查看当前处于活动状态的配额的详细信息
 a| 
单击 * 配额报告 * 选项卡。

|===
. 从显示的配额列表中选择要查看相关信息的配额。
. 查看配额详细信息。




== 配额类型

配额可以根据应用到的目标进行分类。

以下是根据应用配额的目标确定的配额类型：

* * 用户配额 *
+
目标为用户。

+
用户可以通过 UNIX 用户名， UNIX UID ， Windows SID ， UID 与用户匹配的文件或目录，采用 Windows 2000 之前格式的 Windows 用户名以及由用户 SID 拥有 ACL 的文件或目录来表示。您可以将其应用于卷或 qtree 。

* * 组配额 *
+
目标是一个组。

+
该组由 UNIX 组名称， GID 或 GID 与该组匹配的文件或目录表示。ONTAP 不会根据 Windows ID 应用组配额。您可以将配额应用于卷或 qtree 。

* * qtree 配额 *
+
目标为 qtree ，由 qtree 的路径名称指定。

+
您可以确定目标 qtree 的大小。

* * 默认配额 *
+
自动将配额限制应用于一组大型配额目标，而无需为每个目标创建单独的配额。

+
默认配额可以应用于所有三种类型的配额目标（用户，组和 qtree ）。配额类型由类型字段的值决定。





== 配额限制

您可以应用磁盘空间限制或限制每个配额类型的文件数。如果未指定配额限制，则不会应用任何限制。

配额可以是软配额，也可以是硬配额。软配额发生原因 Data ONTAP ，用于在超过指定限制时发送通知，而硬配额则会在超过指定限制时阻止写入操作成功。

硬配额会对系统资源施加硬限制；任何可能导致超过此限制的操作都将失败。以下设置将创建硬配额：

* 磁盘限制参数
* files limit 参数


软配额会在资源使用量达到特定级别时发送警告消息，但不会影响数据访问操作，因此您可以在超过配额之前采取适当的操作。以下设置将创建软配额：

* 磁盘限制参数的阈值
* 软磁盘限制参数
* 软文件限制参数


通过阈值和软磁盘配额，管理员可以收到多个有关配额的通知。通常，管理员会将 " 磁盘限制阈值 " 设置为仅略小于 " 磁盘限制 " 的值，以便此阈值在写入开始失败之前提供 " 最终警告 " 。

* * 磁盘空间硬限制 *
+
应用于硬配额的磁盘空间限制。

* * 磁盘空间软限制 *
+
应用于软配额的磁盘空间限制。

* * 阈值限制 *
+
应用于阈值配额的磁盘空间限制。

* * 文件硬限制 *
+
硬配额上的最大文件数。

* * 文件软限制 *
+
软配额上的最大文件数。





== 配额管理

System Manager 包含多项功能，可帮助您创建，编辑或删除配额。您可以创建用户，组或树配额，并可以在磁盘和文件级别指定配额限制。所有配额均按卷建立。

创建配额后，您可以执行以下任务：

* 启用和禁用配额
* 调整配额大小




== 配额窗口

您可以使用配额窗口创建，显示和管理有关配额的信息。



=== 选项卡

* * 用户定义的配额 *
+
您可以使用 * 用户定义的配额 * 选项卡查看所创建配额的详细信息以及创建，编辑或删除配额。

* * 配额报告 *
+
您可以使用配额报告选项卡查看空间和文件使用情况，并编辑活动配额的空间和文件限制。

* 卷上的 * 配额状态 *
+
您可以使用卷上的配额状态选项卡查看配额的状态，打开或关闭配额以及调整配额大小。





=== 命令按钮

* * 创建 * 。
+
打开创建配额向导，在此可以创建配额。

* * 编辑限制 *
+
打开编辑限制对话框，在此可以编辑选定配额的设置。

* * 删除 *
+
从配额列表中删除选定配额。

* * 刷新 *
+
更新窗口中的信息。





=== 用户定义的配额列表

配额列表显示每个配额的名称和存储信息。

* * 卷 *
+
指定要应用配额的卷。

* * qtree*
+
指定与配额关联的 qtree 。"`所有 qtree` " 表示配额与所有 qtree 关联。

* * 类型 *
+
指定配额类型：用户，组或树。

* * 用户 / 组 *
+
指定与配额关联的用户或组。" 所有用户 " 表示配额与所有用户关联。" 所有组 " 表示配额与所有组关联。

* * 配额目标 *
+
指定配额分配到的目标类型。目标可以是 qtree ，用户或组。

* * 空间硬限制 *
+
指定应用于硬配额的磁盘空间限制。

+
默认情况下，此字段处于隐藏状态。

* * 空间软限制 *
+
指定应用于软配额的磁盘空间限制。

+
默认情况下，此字段处于隐藏状态。

* * 阈值 *
+
指定应用于阈值配额的磁盘空间限制。

+
默认情况下，此字段处于隐藏状态。

* * 文件硬限制 *
+
指定硬配额中的最大文件数。

+
默认情况下，此字段处于隐藏状态。

* * 文件软限制 *
+
指定软配额中的最大文件数。

+
默认情况下，此字段处于隐藏状态。





=== 详细信息区域

配额列表下方的区域显示配额详细信息，例如配额错误，空间使用量和限制以及文件使用量和限制。

* 相关信息 *

https://docs.netapp.com/us-en/ontap/volumes/index.html["逻辑存储管理"^]
