---
permalink: online-help-96-97/concept_cluster_peers.html 
sidebar: sidebar 
keywords: cluster, peer, data, replication, snapmirror, snapvault, flexcache, syncmirror, configuration, system, manager, modify, passphrase, lif, configure, remote, change, encryption, status, online, help 
summary: 对于使用 SnapMirror 技术和 SnapVault 技术进行数据复制以及在 MetroCluster 配置中使用 FlexCache 卷和 SyncMirror 技术进行数据复制，需要使用对等集群。您可以使用 System Manager 为两个集群建立对等关系，以便对等集群可以在它们之间协调和共享资源。 
---
= 使用 System Manager 的集群对等方— ONTAP 9.7 及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）对等两个集群，以便对等集群可以在它们之间协调和共享资源。对于使用 SnapMirror 技术和 SnapVault 技术进行数据复制以及在 MetroCluster 配置中使用 FlexCache 卷和 SyncMirror 技术进行数据复制，需要使用对等集群。



== 生成对等密码短语

从 System Manager 9.6 开始，您可以为本地集群 IP 空间生成密码短语，并在创建对等关系时在远程集群中使用相同的密码短语。

.步骤
. 单击 * 配置 * > * 集群对等方 * 。
. 单击 * 生成对等密码短语 * 。
+
此时将显示生成对等密码短语对话框窗口。

. 填写以下字段：
+
** * IP 空间 * ：从下拉菜单中选择 IP 空间。
** * 密码短语有效期 * ：从下拉菜单中选择希望密码短语有效的持续时间。
** * SVM 权限 * ：选择以下选项之一：
+
*** * 所有 SVM* 以指示允许所有 SVM 访问集群。
*** * 选定 SVM* 以指示允许访问集群的特定 SVM 。在要指定的字段中突出显示 SVM 名称。




. *可选：*如果远程集群的有效集群版本早于ONTAP 9.6、请选中此复选框。否则，无法生成集群对等关系。
. 单击 * 生成 * 以生成密码短语。
+
为成功生成密码短语，系统将显示一条消息，用于标识您的密码短语。

. 如果要通过电子邮件发送或复制密码短语，请执行以下操作之一：
+
** 单击 * 通过电子邮件发送密码短语详细信息 * 。
** 单击 * 复制密码短语 * 。






== 修改集群对等密码短语

您可以修改在创建集群对等方期间提供的密码短语。

.步骤
. [[STEP1]]单击*配置*>*集群对等方*。
. 选择对等集群，然后单击 * 编辑 *
+
此时将显示下拉菜单。

. 单击 * 本地集群密码短语 * 。
+
此时将显示编辑本地集群密码短语对话框窗口。

. [[STEP4]]在*Enter Pasports*字段中，输入新的密码短语，然后单击*Apply*。
+
[NOTE]
====
密码短语的最小长度为 8 个字符。

====
+
密码短语将立即修改。但是，在显示正确的身份验证状态之前，可能会有一段延迟。

. 登录到远程集群并执行步骤 link:#step1["1."] 到 link:#step4["4."] 修改远程集群中的密码短语。
+
本地集群的身份验证状态显示为 `ok_and_offer` 直到您修改远程集群中的密码短语为止。





== 修改为远程集群配置的 LIF

您可以使用 System Manager 修改为远程集群配置的 IP 空间和集群间逻辑接口（ LIF ）。您可以添加新的集群间 IP 地址或删除现有 IP 地址。

.开始之前
要创建集群对等关系，必须至少具有一个集群间 IP 地址。

.步骤
. 单击 * 配置 * > * 集群 * > * 配置更新 * 。
. 选择对等集群，然后单击 * 编辑 *
+
此时将显示下拉菜单。

. 单击 * 对等集群网络参数 * 。
+
此时将显示编辑对等网络参数对话框窗口。

. 如果需要，请修改以下字段：
+
** * IP 空间 * ：从下拉菜单中选择 IP 空间。
** * 集群间 LIF* ：添加或删除集群间 IP 地址。您可以添加多个 IP 地址，方法是使用逗号分隔这些地址。


. 单击 * 修改 * 。
. 验证您在 * 集群对等方 * 窗口中所做的更改。




== 更改对等加密状态

您可以使用 System Manager 更改选定集群的对等加密状态。

.关于此任务
加密状态可以是已启用或已禁用。您可以通过选择 * 更改加密 * 将状态从已启用更改为已禁用或从已禁用更改为已启用。

.步骤
. 单击 * 配置 * > * 集群对等方 * 。
. 选择对等集群，然后单击 * 编辑 *
+
此时将显示下拉菜单。

. 单击 * 更改加密 * 。
+
如果加密状态为 "`N/A` " ，则此操作不可用。

+
此时将显示更改加密对话框窗口。切换按钮用于指示当前加密状态。

. 滑动切换按钮以更改对等加密状态，然后继续。
+
** 如果当前加密状态为 "`none` " ，则可以滑动切换按钮将此状态更改为 "`tls_psk` " 来启用加密。
** 如果当前加密状态为 "`tls_psk` " ，则可以滑动切换按钮将状态更改为 "`none` " 来禁用加密。


. 启用或禁用对等加密后，您可以生成一个新密码短语并在对等集群上提供该密码短语，也可以应用已在对等集群上生成的现有密码短语。
+
[NOTE]
====
如果本地站点上使用的密码短语与远程站点上使用的密码短语不匹配，则集群对等关系将无法正常运行。

====
+
选择以下选项之一：

+
** *生成密码短语*：继续 link:#step6["第6步"]。
** *已有密码短语*：继续 link:#step9["第9步"]。


. [[STEP6]]如果选择*生成密码短语*，请填写必要的字段：
+
** * IP 空间 * ：从下拉菜单中选择 IP 空间。
** * 密码短语有效期 * ：从下拉菜单中选择希望密码短语有效的持续时间。
** * SVM 权限 * ：选择以下选项之一：
+
*** * 所有 SVM* 以指示允许所有 SVM 访问集群。
*** * 选定 SVM* 以指示允许访问集群的特定 SVM 。在要指定的字段中突出显示 SVM 名称。




. *可选：*如果远程集群的有效集群版本早于ONTAP 9.6、请选中此复选框。否则，将无法生成密码短语。
. 单击 * 应用 * 。
+
系统将为此关系生成密码短语并显示此密码短语。您可以复制密码短语或通过电子邮件发送密码短语。

+
本地集群的身份验证状态显示为 `ok_and_offer` 在选定密码短语有效期内、直到您在远程集群上提供密码短语为止。

. [[STEP9]]如果已在远程集群中生成新密码短语、请执行以下子步骤：
+
.. 单击 * 已有密码短语 * 。
.. 在 * 密码短语 * 字段中输入在远程集群中生成的同一密码短语。
.. 单击 * 应用 * 。






== 删除集群对等关系

如果不再需要集群对等关系，您可以使用 System Manager 删除此关系。您必须从对等关系中的每个集群中删除集群对等关系。

.步骤
. [[STEP1]]单击*配置*>*集群对等方*。
. 选择要删除关系的集群对等方，然后单击 * 删除 * 。
. [[STEP3]]选中确认复选框，然后单击*Delete*。
. 登录到远程集群并执行步骤 link:#step1["1."] 到 link:#step3["3."] 删除本地集群与远程集群之间的对等关系。
+
对等关系的状态将显示为 "`unhealthy` " ，直到从本地集群和远程集群中删除此关系为止。





== 集群对等方窗口

您可以使用集群对等方窗口管理对等集群关系，从而可以将数据从一个集群移动到另一个集群。



=== 命令按钮

* * 创建 * 。
+
打开创建集群对等对话框，在此可以创建与远程集群的关系。

* * 编辑 * 。
+
显示一个下拉菜单，其中包含以下选项：

+
** * 本地集群密码短语 *
+
打开编辑本地集群密码短语对话框，在此可以输入新密码短语以验证本地集群。

** * 对等集群网络参数 *
+
打开编辑对等集群网络参数对话框，在此可以修改 IP 空间以及添加或删除集群间 LIF IP 地址。

+
您可以添加多个 IP 地址，以逗号分隔。

** * 更改加密 *
+
打开选定对等集群的更改加密对话框。在更改对等关系的加密时，您可以生成新的密码短语，也可以提供已在远程对等集群上生成的密码短语。

+
如果加密状态为 "`N/A` " ，则此操作不可用。



* * 删除 *
+
打开删除集群对等关系对话框，在此可以删除选定的对等集群关系。

* * 刷新 *
+
更新窗口中的信息。

* * 管理 SVM 权限 *
+
允许 SVM 自动接受 SVM 对等请求。

* * 生成对等密码短语 *
+
用于通过指定 IP 空间，设置密码短语有效期限以及指定为其授予权限的 SVM 来为本地集群 IP 空间生成密码短语。

+
您可以在远程集群中使用相同的密码短语建立对等关系。





=== 对等集群列表

* * 对等集群 *
+
指定关系中对等集群的名称。

* * 可用性 *
+
指定对等集群是否可用于通信。

* * 身份验证状态 *
+
指定对等集群是否经过身份验证。

* * 本地集群 IP 空间 *
+
显示与本地集群对等关系关联的 IP 空间。

* * 对等集群集群间 IP 地址 *
+
显示与集群间对等关系关联的 IP 地址。

* * 上次更新时间 *
+
显示上次修改对等集群的时间。

* * 加密 *
+
显示对等关系的加密状态。

+
[NOTE]
====
从 System Manager 9.6 开始，当您在两个集群之间建立对等关系时，对等关系默认处于加密状态

====
+
** * 不适用 * ：加密不适用于此关系。
** * 无 * ：对等关系未加密。
** * TLS PSK* ：对等关系已加密。



