---
permalink: online-help-96-97/concept_cluster_expansion.html 
sidebar: sidebar 
keywords: cluster, expanision, system, manager, storage, size, capabilities, add, node, configure, network, online, help 
summary: 您可以使用 System Manager 向集群添加兼容节点并配置节点网络详细信息，以增加存储的大小和功能。您还可以查看节点的摘要。 
---
= 使用 System Manager 进行集群扩展— ONTAP 9.7 及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP System Manager classic (适用于ONTAP 9.7及更早版本)通过向集群添加兼容节点并配置节点网络详细信息来增加存储的大小和功能。您还可以查看节点的摘要。

登录到 System Manager 时， System Manager 会自动检测已通过缆线连接但尚未添加到集群中的兼容节点，并提示您添加这些节点。您可以在 System Manager 检测到兼容节点时添加这些节点，也可以稍后手动添加这些节点。



== 向集群添加节点

您可以使用 System Manager 通过向现有集群添加节点来增加存储系统的大小和功能。

.开始之前
* 必须使用缆线将新的兼容节点连接到集群。
+
网络窗口仅会列出默认广播域中的端口。

* 集群中的所有节点都必须已启动且正在运行。
* 所有节点的版本必须相同。


.步骤
. 将新的兼容节点添加到集群：
+
|===
| 如果您 ... | 执行此操作 ... 


 a| 
未登录到 System Manager
 a| 
.. 登录到系统管理器。
+
[NOTE]
====
System Manager 会在登录时自动检测新的兼容节点。System Manager 会提示您将新的兼容节点添加到集群中。

====
.. 单击 * 将节点添加到集群 * 。
.. 修改节点的名称。
.. 指定节点许可证。
.. 单击 * 提交并继续 * 。




 a| 
已登录到 System Manager
 a| 
.. 单击 * 配置 * > * 集群 * > * 扩展 * 。
+
System Manager 将搜索新添加的节点。如果显示任何警告，则必须先修复这些警告，然后再继续操作。如果发现新的兼容节点，请继续执行下一步。

.. 修改节点的名称。
.. 指定节点许可证。
.. 单击 * 提交并继续 * 。


|===




== 配置节点的网络详细信息

您可以使用 System Manager 为新添加的节点配置节点管理 LIF 和服务处理器设置。

.开始之前
* 默认 IP 空间中必须具有足够数量的端口，才能创建 LIF 。
* 所有端口都必须已启动且正在运行。


.步骤
. 配置节点管理：
+
.. 在 * IP 地址 * 字段中输入 IP 地址。
.. 在 * 端口 * 字段中选择用于节点管理的端口。
.. 输入网络掩码和网关详细信息。


. 配置服务处理器设置：
+
.. 选中 * 覆盖默认值 * 复选框以覆盖默认值。
.. 输入 IP 地址，网络掩码和网关详细信息。


. 单击 * 提交并继续 * 以完成节点的网络配置。
. 在 * 摘要 * 页面中验证节点的详细信息。




=== 下一步操作

* 如果集群受到保护，则应在新添加的节点中创建所需数量的集群间 LIF ，以避免部分对等和保护运行不正常。
* 如果集群中启用了 SAN 数据协议，则应创建所需数量的 SAN 数据 LIF 以提供数据。


* 相关信息 *

xref:task_creating_network_interfaces.adoc[创建网络接口]
