---
permalink: online-help-96-97/concept_array_luns.html 
sidebar: sidebar 
keywords: system, manager, array, lun, aggregate, assign, online, help, classic 
summary: 您可以使用 System Manager 将阵列 LUN 分配给现有聚合并管理阵列 LUN 。 
---
= 使用 System Manager （ ONTAP 9.7 及更早版本）管理阵列 LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）将阵列 LUN 分配给现有聚合并管理阵列 LUN 。



== 分配阵列 LUN

您可以使用 System Manager 将未分配的阵列 LUN 分配给现有聚合，以增加聚合的大小。

.关于此任务
* 如果满足以下条件，则可以分配阵列 LUN ：
+
** 选定阵列 LUN 的容器类型必须为 "`unassigned` " 。
** 磁盘必须连接到 HA 对中的节点。
** 这些磁盘必须对节点可见。


* 对于 MetroCluster 配置，不能使用 System Manager 将阵列 LUN 分配为备用磁盘。
+
您必须改用命令行界面。



.步骤
. 单击 * 存储 * > * 聚合和磁盘 * > * 阵列 LUN* 。
. 选择阵列 LUN ，然后单击 * 分配 * 。
. 在 * 分配阵列 LUN* 对话框中，选择要将阵列 LUN 分配到的节点。
. 单击 * 分配 * 。




== 将备用阵列 LUN 重新分配给节点

您可以使用 System Manager 将备用阵列 LUN 的所有权从一个节点重新分配给另一个节点，以增加聚合的容量。

.关于此任务
* 如果满足以下条件，则可以重新分配阵列 LUN ：
+
** 选定阵列 LUN 的容器类型必须为 `spare` 。
** 磁盘必须连接到 HA 对中的节点。
** 这些磁盘必须对节点可见。


* 对于 MetroCluster 配置，不能使用 System Manager 将阵列 LUN 重新分配为备用阵列 LUN 。
+
您必须改用命令行界面。



.步骤
. 单击 * 存储 * > * 聚合和磁盘 * > * 阵列 LUN* 。
. 选择要重新分配的备用阵列 LUN ，然后单击 * 分配 * 。
. 在 * 警告 * 对话框中，单击 * 继续 * 。
. 在 * 分配阵列 LUN* 对话框中，选择要将备用阵列 LUN 重新分配到的节点。
. 单击 * 分配 * 。




== 将备用阵列 LUN 置零

您可以使用 System Manager 通过向阵列 LUN 写入零来擦除所有数据并格式化备用阵列 LUN 。然后，可以在新聚合中使用这些阵列 LUN 。

.关于此任务
将备用阵列 LUN 置零后，集群中的所有备用磁盘（包括磁盘）都会置零。您可以将特定节点或整个集群的备用阵列 LUN 置零。

.步骤
. 单击 * 存储 * > * 聚合和磁盘 * > * 阵列 LUN* 。
. 单击 * 将备件置零 * 。
. 在 * 将备用磁盘置零 * 对话框中，选择要将阵列 LUN 置零的节点或 "`所有节点` " 。
. 选中 * 将所有未置零备件置零 * 复选框以确认置零操作。
. 单击 * 将备件置零 * 。




== 关于磁盘和阵列 LUN

磁盘是使用 ONTAP 软件访问原生磁盘架的存储系统的基本存储单元。阵列 LUN 是第三方存储阵列提供给运行 ONTAP 软件的存储系统的基本存储单元。

通过 ONTAP 软件，您可以为磁盘和阵列 LUN 分配所有权，并将其添加到聚合中。ONTAP 软件还提供了多种管理磁盘的方法，包括删除磁盘，更换磁盘以及对磁盘进行清理。由于阵列 LUN 由第三方存储阵列提供，因此您可以使用第三方存储阵列执行阵列 LUN 的所有其他管理任务。

您可以使用磁盘或阵列 LUN 创建聚合。创建聚合后，无论聚合是从磁盘还是阵列 LUN 创建的，都可以使用 ONTAP 软件以完全相同的方式对其进行管理。



== 阵列 LUN 窗口

通过阵列 LUN 窗口，您可以为阵列 LUN 分配所有权并将其添加到聚合。

只有当存在任何备用阵列 LUN 或安装了 V_StorageAttach 许可证时，左侧导航窗格中才会显示阵列 LUN 链接。



=== 命令按钮

* * 分配 *
+
用于将阵列 LUN 的所有权分配或重新分配给节点。

* * 零备件 *
+
擦除所有数据并格式化备用阵列 LUN 和磁盘。

* * 刷新 *
+
更新窗口中的信息。





=== 阵列 LUN 列表

显示每个阵列 LUN 的名称，状态和供应商等信息。

* * 名称 *
+
指定阵列 LUN 的名称。

* * 状态 *
+
指定阵列 LUN 的状态。

* * 供应商 *
+
指定供应商的名称。

* * 已用空间 *
+
指定阵列 LUN 使用的空间。

* * 总大小 *
+
指定阵列 LUN 的大小。

* * 容器 *
+
指定阵列 LUN 所属的聚合。

* * 节点名称 *
+
指定阵列 LUN 所属节点的名称。

* * 主所有者 *
+
显示将阵列 LUN 分配到的主节点的名称。

* * 当前所有者 *
+
显示当前拥有阵列 LUN 的节点的名称。

* * 阵列名称 *
+
指定阵列的名称。

* * 池 *
+
显示将选定阵列 LUN 分配到的池的名称。





=== 详细信息区域

阵列 LUN 列表下方的区域显示有关选定阵列 LUN 的详细信息。

* 相关信息 *

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["FlexArray 虚拟化安装要求和参考"]
