---
permalink: online-help-96-97/concept_storage_pools.html 
sidebar: sidebar 
keywords: system, manager, storage, pools, ssd, flash, pool, aggregates, online, help, create, 
summary: 您可以使用 System Manager 创建存储池，以使多个 Flash Pool 聚合能够共享 SSD 。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本管理存储池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）创建存储池，以使多个 Flash Pool 聚合能够共享 SSD 。



== 创建存储池

存储池是 SSD （缓存磁盘）的集合。您可以使用 System Manager 组合 SSD 来创建存储池，从而可以在 HA 对之间共享 SSD 和 SSD 备用磁盘，以便同时分配给两个或多个 Flash Pool 聚合。

.开始之前
* HA 对的两个节点都必须已启动且正在运行，才能通过存储池分配 SSD 和 SSD 备用磁盘。
* 存储池必须至少具有 3 个 SSD 。
* 存储池中的所有 SSD 必须属于同一个 HA 对。


.关于此任务
使用 SSD 向存储池添加磁盘时， System Manager 会对 SSD RAID 组强制实施热备用规则。例如、如果SSD RAID组和选项中有10个SSD `raid.min_spare_count` 设置为 `1` 在节点级别、System Manager保留1个SSD作为热备用磁盘、而使用其他9个SSD执行与SSD相关的操作。

使用 System Manager 创建存储池时，不能使用分区 SSD 。

.步骤
. 单击 * 存储 * > * 聚合和磁盘 * > * 存储池 * 。
. 在 * 存储池 * 窗口中，单击 * 创建 * 。
. 在 * 创建存储池 * 对话框中，指定存储池的名称，磁盘大小和磁盘数量。
. 单击 * 创建 * 。




== 将磁盘添加到存储池

您可以使用 System Manager 将 SSD 添加到现有存储池并增加其缓存大小。

.开始之前
HA 对的两个节点都必须已启动且正在运行，才能通过存储池分配 SSD 和 SSD 备用磁盘。

.关于此任务
* 添加到存储池的 SSD 会按比例分布在使用存储池缓存的聚合之间，并分配到存储池的可用空间。
* 使用 SSD 向存储池添加磁盘时， System Manager 会对 SSD RAID 组强制实施热备用规则。
+
例如、如果SSD RAID组和选项中有10个SSD `raid.min_spare_count` 设置为 `1` 在节点级别、System Manager保留1个SSD作为热备用磁盘、而使用其他9个SSD执行与SSD相关的操作。

* 使用 System Manager 向存储池添加磁盘时，不能使用分区 SSD 。


.步骤
. 单击 * 存储 * > * 聚合和磁盘 * > * 存储池 * 。
. 在 * 存储池 * 窗口中，选择存储池，然后单击 * 添加磁盘 * 。
. 在 * 添加磁盘 * 对话框中，指定要添加的磁盘数。
. 单击 * 下一步 * 。
. 在 * 摘要 * 对话框中，查看缓存如何在各种聚合之间分布以及存储池的可用空间。
. 单击 * 添加 * 。




== 删除存储池

如果存储池的缓存不是最佳缓存，或者任何聚合或 Flash Pool 聚合不再使用存储池，则您可能需要删除该存储池。您可以使用 System Manager 中的删除存储池对话框删除存储池。

.开始之前
存储池不能由任何聚合使用。

.步骤
. 单击 * 存储 * > * 聚合和磁盘 * > * 存储池 * 。
. 在 * 存储池 * 窗口中，选择要删除的存储池，然后单击 * 删除 * 。
. 在 * 删除存储池 * 对话框中，单击 * 删除 * 。




== 使用 SSD 存储池

要使多个 Flash Pool 聚合能够共享 SSD ，您可以将 SSD 添加到 _storage pool_ 。将 SSD 添加到存储池后，您将无法再将 SSD 作为独立实体进行管理。您必须使用存储池分配或分配 SSD 提供的存储。

您可以为特定高可用性（ HA ）对创建存储池。然后，您可以将该存储池中的分配单元添加到同一 HA 对所拥有的一个或多个 Flash Pool 聚合中。就像磁盘必须由拥有聚合的同一节点拥有，然后才能将磁盘分配给聚合一样，存储池只能为拥有该存储池的某个节点所拥有的 Flash Pool 聚合提供存储。

如果您必须增加系统上的 Flash Pool 缓存量，则可以向存储池添加更多 SSD ，但最多不超过使用此存储池的 Flash Pool 缓存的 RAID 类型的最大 RAID 组大小。将 SSD 添加到现有存储池时，您可以增加存储池的分配单元的大小，包括已分配给 Flash Pool 聚合的任何分配单元。

一个存储池只能使用一个备用 SSD ，以便在该存储池中的 SSD 不可用时， ONTAP 可以使用备用 SSD 重建故障 SSD 的分区。您无需预留任何分配单元作为备用容量； ONTAP 只能使用未分区的完整 SSD 作为存储池中 SSD 的备用 SSD 。

将 SSD 添加到存储池后，您将无法删除此 SSD ，就像无法从聚合中删除磁盘一样。如果要再次使用存储池中的 SSD 作为离散驱动器，则必须销毁已将存储池的分配单元分配到的所有 Flash Pool 聚合，然后销毁存储池。



== 使用 SSD 存储池的要求和最佳实践

某些技术无法与使用 SSD 存储池的 Flash Pool 聚合结合使用。

对于使用 SSD 存储池作为缓存存储的 Flash Pool 聚合，不能使用以下技术：

* MetroCluster
* SyncMirror 功能
+
镜像聚合可以与使用存储池的 Flash Pool 聚合共存；但是，无法镜像 Flash Pool 聚合。

* 物理 SSD
+
Flash Pool 聚合可以使用 SSD 存储池或物理 SSD ，但不能同时使用这两者。



SSD 存储池必须符合以下规则：

* SSD 存储池只能包含 SSD ； HDD 不能添加到 SSD 存储池。
* SSD 存储池中的所有 SSD 必须属于同一个高可用性（ HA ）对。
* 您不能使用已分区的 SSD 在存储池中进行根数据分区。


如果您从一个存储池向两个具有不同 RAID 类型的缓存提供存储，并且将存储池的大小扩展到 RAID4 的最大 RAID 组大小之外，则 RAID4 分配单元中的额外分区将不会使用。因此，最佳做法是使存储池的缓存 RAID 类型保持同构。

您不能更改从存储池分配的缓存 RAID 组的 RAID 类型。您可以在添加第一个分配单元之前设置缓存的 RAID 类型，并且稍后无法更改 RAID 类型。

创建存储池或向现有存储池添加 SSD 时，必须使用相同大小的 SSD 。如果发生故障并且不存在大小正确的备用 SSD ，则 ONTAP 可以使用较大的 SSD 来更换发生故障的 SSD 。但是，较大的 SSD 会进行适当的大小调整，以匹配存储池中其他 SSD 的大小，从而导致 SSD 容量丢失。

一个存储池只能使用一个备用 SSD 。如果存储池为 HA 对中两个节点所拥有的 Flash Pool 聚合提供了分配单元，则备用 SSD 可以归任一节点所有。但是，如果存储池仅为 HA 对中某个节点所拥有的 Flash Pool 聚合提供分配单元，则 SSD 备用磁盘必须属于同一节点。



== 有关何时使用 SSD 存储池的注意事项

SSD 存储池具有许多优势，但也存在一些限制，您在决定是使用 SSD 存储池还是专用 SSD 时应注意这些限制。

只有当 SSD 存储池为两个或更多 Flash Pool 聚合提供缓存时，它们才有意义。SSD 存储池具有以下优势：

* 提高了 Flash Pool 聚合中使用的 SSD 的存储利用率
+
SSD 存储池允许您在两个或更多 Flash Pool 聚合之间共享奇偶校验 SSD ，从而降低奇偶校验所需 SSD 的总百分比。

* 能够在 HA 配对节点之间共享备用磁盘
+
由于存储池实际上归 HA 对所有，因此，如果需要，一个 HA 配对节点所拥有的备用磁盘可以用作整个 SSD 存储池的备用磁盘。

* 提高 SSD 性能的利用率
+
SSD 提供的高性能可支持 HA 对中的两个控制器进行访问。



这些优势必须与使用 SSD 存储池的成本进行权衡，其中包括以下各项：

* 减少故障隔离
+
丢失一个 SSD 会影响包含其一个分区的所有 RAID 组。在这种情况下，从包含受影响 SSD 的 SSD 存储池分配缓存的每个 Flash Pool 聚合都有一个或多个 RAID 组处于重建状态。

* 减少了性能隔离
+
如果 Flash Pool 缓存的大小不正确，则共享该缓存的 Flash Pool 聚合之间可能存在争用。可以通过适当的缓存规模估算和 QoS 控制来缓解这种风险。

* 管理灵活性降低
+
向存储池添加存储时，您可以增加包含该存储池中一个或多个分配单元的所有 Flash Pool 缓存的大小；您无法确定如何分配额外容量。





== 将 SSD 添加到现有存储池与创建新存储池的注意事项

您可以通过两种方式增加 SSD 缓存的大小—将 SSD 添加到现有 SSD 存储池或创建新的 SSD 存储池。最佳方法取决于您的配置和存储计划。

在创建新存储池与向现有存储池添加存储容量之间进行选择的方式与决定是创建新 RAID 组还是向现有 RAID 组添加存储类似：

* 如果要添加大量 SSD ，则创建新存储池可提供更大的灵活性，因为新存储池的分配方式与现有存储池不同。
* 如果只添加少量 SSD ，而增加现有 Flash Pool 缓存的 RAID 组大小不是问题描述，则向现有存储池添加 SSD 会降低备用和奇偶校验成本，并自动分配新存储。


如果您的存储池正在为缓存具有不同 RAID 类型的 Flash Pool 聚合提供分配单元，并且您将存储池的大小扩展到超过 RAID4 RAID 组的最大大小，则 RAID4 分配单元中新添加的分区将不会使用。



== 为什么要向存储池添加磁盘

您可以将 SSD 添加到现有存储池并增加其缓存大小。将 SSD 添加到已将分配单元分配给 Flash Pool 聚合的存储池时，您可以增加其中每个聚合的缓存大小以及存储池的总缓存。

如果尚未分配存储池的分配单元，则向该存储池添加 SSD 不会影响 SSD 缓存大小。

将 SSD 添加到现有存储池时， SSD 必须归存储池中现有 SSD 所属的同一 HA 对中的一个节点或另一个节点所有。您可以添加 HA 对中任一节点所拥有的 SSD 。



== 存储池的工作原理

_storage pool_ 是 SSD 的集合。您可以组合 SSD 以创建存储池，从而使您能够在多个 Flash Pool 聚合之间同时共享 SSD 和 SSD 备用磁盘。

存储池由分配单元组成，您可以使用这些分配单元为聚合提供 SSD 和 SSD 备用磁盘或增加现有 SSD 大小。

将 SSD 添加到存储池后，您不能再将 SSD 用作单个磁盘。您必须使用存储池分配或分配 SSD 提供的存储。



== 存储池窗口

您可以使用存储池窗口创建，显示和管理 SSD 的专用缓存，也称为 _storage pools_ 。这些存储池可以与非根聚合关联以提供 SSD 缓存，也可以与 Flash Pool 聚合关联以增加其大小。

此页面不适用于包含具有全闪存优化特性的节点的集群。



=== 命令按钮

* * 创建 * 。
+
打开创建存储池对话框，在此可以创建存储池。

* * 添加磁盘 *
+
打开添加磁盘对话框，在此可以向存储池添加缓存磁盘。

* * 删除 *
+
删除选定存储池。

* * 刷新 *
+
更新窗口中的信息。





=== 存储池列表

* * 名称 *
+
显示存储池的名称。

* * 总缓存 *
+
显示存储池的总缓存大小。

* * 备用缓存 *
+
显示存储池的可用备用缓存大小。

* * 已用缓存（ % ） *
+
显示存储池的已用缓存大小百分比。

* * 分配单元 *
+
显示可用于增加存储池大小的总缓存大小的最小分配单元。

* * 所有者 *
+
显示 HA 对或与存储池关联的节点的名称。

* * 状态 *
+
显示存储池的状态，可以是 " 正常 " ， " 已降级 " ， " 创建 " ， " 删除 " ， " 重新分配 " ， 或不断增长。

* * 运行状况良好 *
+
显示存储池是否运行正常。





=== 详细信息选项卡

显示有关选定存储池的详细信息，例如名称，运行状况，存储类型，磁盘计数，总缓存， 备用缓存，已用缓存大小（以百分比表示）和分配单元。此选项卡还会显示存储池配置的聚合的名称。



=== 磁盘选项卡

显示有关选定存储池中磁盘的详细信息，例如名称，磁盘类型，可用大小和总大小。

* 相关信息 *

xref:task_provisioning_storage_by_creating_flash_pool_aggregate_manually.adoc[通过手动创建 Flash Pool 聚合来配置存储]

xref:task_provisioning_cache_by_adding_disks.adoc[通过添加 SSD 来配置缓存]

https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["磁盘和聚合管理"]
