---
permalink: online-help-96-97/concept_qtrees.html 
sidebar: sidebar 
keywords: system, manager, create, edit, delete, qtree, partition, data, policies, svm 
summary: 您可以使用 System Manager 创建，编辑和删除 qtree 。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本管理 qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）创建，编辑和删除 qtree 。



== 创建 qtree

qtree 可用于管理卷中的数据并对其进行分区。您可以使用 System Manager 中的创建 qtree 对话框向存储系统上的卷添加新的 qtree 。

.步骤
. 单击 * 存储 * > * qtree* 。
. 从 * SVM* 字段的下拉菜单中，选择要创建 qtree 的 Storage Virtual Machine （ SVM ）。
. 单击 * 创建 * 。
. 在 * 创建 qtree* 对话框的 * 详细信息 * 选项卡中，键入 qtree 的名称。
. 选择要将 qtree 添加到的卷。
+
卷浏览列表仅包含处于联机状态的卷。

. 如果要为 qtree 禁用机会锁（ oplock ），请清除 * 为此 qtree* 中的文件和目录启用机会锁复选框。
+
默认情况下，每个 qtree 都启用机会锁。

. 如果要更改继承的默认安全模式，请选择一种新的安全模式。
+
qtree 的默认安全模式是包含 qtree 的卷的安全模式。

. 如果要更改默认继承的导出策略，请选择现有导出策略或创建导出策略。
+
qtree 的默认导出策略是分配给包含 qtree 的卷的导出策略。

. 如果要限制磁盘空间使用量，请单击 * 配额 * 选项卡。
+
.. 如果要对 qtree 应用配额，请单击 * qtree quot* ，然后指定磁盘空间限制。
.. 如果要为 qtree 上的所有用户应用配额，请单击 * 用户配额 * ，然后指定磁盘空间限制。


. 单击 * 创建 * 。
. 验证您创建的 qtree 是否包含在 * qtree* 窗口的 qtree 列表中。




== 删除 qtree

您可以使用 System Manager 删除 qtree 并回收 qtree 在卷中使用的磁盘空间。删除 qtree 后， ONTAP 将不再应用适用于该 qtree 的所有配额。

.开始之前
* qtree 状态必须为正常。
* qtree 不能包含任何 LUN 。


.步骤
. 单击 * 存储 * > * qtree* 。
. 在 * qtree* 窗口中，选择要删除的一个或多个 qtree ，然后单击 * 删除 * 。
. 选中确认复选框，然后单击 * 删除 * 。
. 确认删除的 qtree 不再包含在 * qtree* 窗口的 qtree 列表中。




== 编辑 qtree

您可以使用 System Manager 修改 qtree 的属性，例如安全模式，启用或禁用机会锁（ oplock ）以及分配新的或现有的导出策略。

.步骤
. 单击 * 存储 * > * qtree* 。
. 选择要编辑的 qtree ，然后单击 * 编辑 * 。
. 在 * 编辑 qtree* 对话框中，根据需要编辑以下属性：
+
** 机会锁
** 安全风格
** 导出策略


. 单击 * 保存 * 。
. 在 * qtree* 窗口中验证对选定 qtree 所做的更改。




== 为 qtree 分配导出策略

您可以导出卷上的特定 qtree ，使其可供客户端直接访问，而不是导出整个卷。您可以使用 System Manager 通过为 qtree 分配导出策略来导出 qtree 。您可以从 qtree 窗口为一个或多个 qtree 分配导出策略。

.步骤
. 单击 * 存储 * > * qtree* 。
. 从 SVM 字段的下拉菜单中选择要导出的 qtree 所在的 Storage Virtual Machine （ SVM ）。
. 选择要为其分配导出策略的一个或多个 qtree ，然后单击 * 更改导出策略 * 。
. 在 * 导出策略 * 对话框中，创建导出策略或选择现有导出策略。
+
link:task_creating_export_policy.html["创建导出策略"]

. 单击 * 保存 * 。
. 验证分配给 qtree 的导出策略及其相关导出规则是否显示在相应 qtree 的 * 详细信息 * 选项卡中。




== 查看 qtree 信息

您可以使用 System Manager 中的 qtree 窗口查看包含 qtree 的卷， qtree 的名称，安全模式和状态以及机会锁状态。

.步骤
. 单击 * 存储 * > * qtree* 。
. 从 * SVM* 字段的下拉菜单中，选择要查看其信息的 qtree 所在的 Storage Virtual Machine （ SVM ）。
. 从显示的 qtree 列表中选择 qtree 。
. 在 * qtree* 窗口中查看 qtree 详细信息。




== qtree 选项

qtree 是一种逻辑上定义的文件系统，可以作为 FlexVol 卷中根目录的一个特殊子目录存在。qtree 用于管理卷中的数据并对其进行分区。

如果在包含卷的 FlexVol 上创建 qtree ，则 qtree 将显示为目录。因此，在删除卷时，您需要注意不要意外删除 qtree 。

您可以在创建 qtree 时指定以下选项：

* qtree 的名称
* 要使 qtree 驻留在其中的卷
* 机会锁
+
默认情况下，为 qtree 启用机会锁。如果对整个存储系统禁用机会锁，则即使为每个 qtree 启用机会锁，也不会设置机会锁。

* 安全风格
+
安全模式可以是 UNIX ， NTFS 或混合（ UNIX 和 NTFS ）。默认情况下， qtree 的安全模式与选定卷的安全模式相同。

* 导出策略
+
您可以创建新的导出策略或选择现有策略。默认情况下， qtree 的导出策略与选定卷的导出策略相同。

* qtree 和用户配额的空间使用量限制




== qtree 窗口

您可以使用 qtree 窗口创建，显示和管理有关 qtree 的信息。



=== 命令按钮

* * 创建 * 。
+
打开创建 qtree 对话框，在此可以创建新的 qtree 。

* * 编辑 * 。
+
打开编辑 qtree 对话框，在此可以更改安全模式，并在 qtree 上启用或禁用机会锁。

* * 更改导出策略 *
+
打开导出策略对话框，在此可以将一个或多个 qtree 分配给新的或现有的导出策略。

* * 删除 *
+
删除选定的 qtree 。

+
除非选定 qtree 的状态正常，否则此按钮将被禁用。

* * 刷新 *
+
更新窗口中的信息。





=== qtree 列表

qtree 列表显示 qtree 所在的卷以及 qtree 名称。

* * 名称 *
+
显示 qtree 的名称。

* * 卷 *
+
显示 qtree 所在卷的名称。

* * 安全模式 *
+
指定 qtree 的安全模式。

* * 状态 *
+
指定 qtree 的当前状态。

* * 机会锁 *
+
指定是为 qtree 启用还是禁用机会锁设置。

* * 导出策略 *
+
显示将 qtree 分配到的导出策略的名称。





=== 详细信息区域

* * 详细信息选项卡 *
+
显示有关选定 qtree 的详细信息，例如包含 qtree 的卷的挂载路径，导出策略的详细信息以及导出策略规则。



* 相关信息 *

https://docs.netapp.com/us-en/ontap/concepts/index.html["ONTAP 概念"^]

https://docs.netapp.com/us-en/ontap/volumes/index.html["逻辑存储管理"^]

https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS 管理"^]

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB/CIFS 管理"^]
