---
permalink: online-help-96-97/concept_how_volume_guarantees_work_for_flexvol_volumes.html 
sidebar: sidebar 
keywords: volume, guarantee, work, flexvol, volume, space, preallocated, aggregate, online, help 
summary: 卷保证（有时称为空间保证）可确定如何从卷所在的聚合中为卷分配空间，无论是否为卷预先分配了空间。 
---
= 关于使用 System Manager - ONTAP 9.7 及更早版本的 FlexVol 卷的卷保证
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 System Manager classic （适用于 ONTAP 9.7 及更早版本）为 FlexVol 卷设置卷保证。卷保证（有时称为 _space guarantees_ ）用于确定如何从卷所在聚合中为卷分配空间，无论是否为卷预先分配了空间。

保证是卷的一个属性。

您可以在创建新卷时设置保证；您也可以更改现有卷的保证，但前提是存在足够的可用空间来满足新的保证。

卷保证类型可以是 `volume` (默认类型)或 `none`。

* 保证类型 `volume` 创建卷时、在聚合中为整个卷分配空间、而不管该空间是否已用于数据。
+
不能为该聚合中的任何其他卷提供或分配已分配的空间。

* 的保证 `none` 仅在卷需要时才从聚合中分配空间。
+
使用此保证类型的卷所占用的空间量会随着数据的添加而增加，而不是由初始卷大小决定，如果卷数据不增长到初始卷大小，则可能会留下未使用的空间。保证为的卷的最大大小 `none` 不受其聚合中可用空间量的限制。与聚合关联的所有卷的总大小可能会超过聚合的可用空间量，但实际可以使用的空间量受聚合大小的限制。

+
如果卷中的 LUN 或文件（包括预留了空间的 LUN 和文件）的聚合没有足够的可用空间来容纳写入，则写入操作可能会失败。



为分配聚合中的空间时 `volume` 对于现有卷、即使该卷尚未使用该空间、该空间也不会再视为聚合中的可用空间。只有当聚合中有足够的可用空间时，才会执行消耗聚合中可用空间的操作，例如创建聚合 Snapshot 副本或在包含聚合的聚合中创建新卷；这些操作将无法使用已分配给另一个卷的空间。

当聚合中的可用空间用尽时，只能保证向该聚合中具有预分配空间的卷或文件写入数据成功。

只有联机卷才支持保证。如果使某个卷脱机，则该卷的任何已分配但未使用的空间将可用于该聚合中的其他卷。当您尝试将该卷恢复联机时，如果聚合中的可用空间不足，无法履行其保证，则该卷将保持脱机状态。您必须强制卷联机，此时卷的保证将被禁用。

* 相关信息 *

http://www.netapp.com/us/media/tr-3965.pdf["NetApp 技术报告 3965 ：《 NetApp 精简配置部署和实施 Data ONTAP 8.1 （ 7- 模式）》"^]
