---
permalink: online-help-96-97/concept_service_processors.html 
sidebar: sidebar 
keywords: service, processors, monitor, manage, storage, system, manager, temperature, voltage, current, fan, speed, online, help, isolate, management, network, traffic, sp, bmc, e0m, interface, subnet, performance, routing, ip, address, edit 
summary: 您可以使用服务处理器通过 System Manager 监控和管理存储系统参数，例如温度，电压，电流和风扇速度。 
---
= 将服务处理器与 System Manager 结合使用— ONTAP 9.7 及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用具有 ONTAP System Manager classic （在 ONTAP 9.7 及更早版本中提供）的服务处理器来监控和管理存储系统参数，例如温度，电压，电流和风扇速度。



== 隔离管理网络流量

最好在专用于管理流量的子网上配置 SP/BMC 和 e0M 管理接口。通过管理网络运行数据流量可能会导致发生原因性能下降并出现路由问题。

大多数存储控制器上的管理以太网端口（由机箱背面的扳手图标指示）连接到内部以太网交换机。内部交换机可连接到 SP/BMC 和 e0M 管理接口，您可以使用此接口通过 Telnet ， SSH 和 SNMP 等 TCP/IP 协议访问存储系统。

如果您计划同时使用远程管理设备和 e0M ，则必须在同一 IP 子网上对其进行配置。由于这些接口是低带宽接口，因此最佳做法是在专用于管理流量的子网上配置 SP/BMC 和 e0M 。

如果无法隔离管理流量，或者专用管理网络异常庞大，则应尽量减少网络流量。传入广播或多播流量过多可能会降低 SP/BMC 性能。

[NOTE]
====
某些存储控制器（例如 AFF A800 ）具有两个外部端口，一个用于 BMC ，另一个用于 e0M 。对于这些控制器，无需在同一 IP 子网上配置 BMC 和 e0M 。

====


== 将 IP 地址分配给服务处理器

您可以使用 System Manager 同时为所有服务处理器分配 IP 地址，并使用这些服务处理器监控和管理存储系统的各种系统参数。

.步骤
. 单击 * 配置 * > * 集群 * > * 配置更新 * 。
. 在 * 服务处理器 * 窗口中，单击 * 全局设置 * 。
. 在 * 全局设置 * 对话框中，选择用于分配 IP 地址的源：
+
|===
| 如果您要 ... | 那么 ... 


 a| 
自动从 DHCP 服务器分配 IP 地址
 a| 
选择 * DHCP * 。



 a| 
从子网分配 IP 地址
 a| 
选择 * 子网 * 。



 a| 
手动提供 IP 地址
 a| 
选择 * 手动分配 * 。

|===
. 单击 * 保存 * 。




== 编辑服务处理器设置

您可以使用 System Manager 修改服务处理器属性，例如 IP 地址，网络掩码或前缀长度以及网关地址。您还可以将 IP 地址分配给未分配任何 IP 地址的服务处理器。

.关于此任务
* 您可以编辑手动分配 IP 地址的服务处理器的设置。
* 您不能编辑通过 DHCP 服务器或子网分配 IP 地址的服务处理器的设置。


.步骤
. 单击 * 配置 * > * 集群 * > * 服务处理器 * 。
. 在 * 服务处理器 * 窗口中，选择要修改的服务处理器，然后单击 * 编辑 * 。
. 在 * 编辑服务处理器 * 对话框中，进行所需的更改，然后单击 * 保存并关闭 * 。




== 了解服务处理器

服务处理器是存储系统中独立于系统的资源，可帮助您监控和管理存储系统参数，例如温度，电压，电流和风扇速度。

当服务处理器检测到任何存储系统参数存在异常情况时，服务处理器将记录事件，向 ONTAP 通知问题描述，并通过电子邮件或 SNMP 陷阱生成 AutoSupport 消息。

服务处理器通过 watchdog 机制监控 ONTAP ，并有助于快速故障转移到配对节点。服务处理器还会跟踪大量系统事件并将这些事件保存在日志文件中。这些事件包括启动进度，现场可更换单元（ FRU ）更改， ONTAP 生成的事件以及用户事务历史记录。

服务处理器可以远程登录和管理存储系统，并且可以诊断，关闭，重新加电或重新启动系统，而不管存储系统的状态如何。此外，服务处理器还提供远程诊断功能。

通过结合使用服务处理器的监控和管理功能，您可以在发生问题描述时评估存储系统，然后立即执行有效的服务操作。



== 服务处理器窗口

您可以使用服务处理器窗口查看和修改服务处理器属性，例如 IP 地址，网络掩码（ IPv4 ）或前缀长度（ IPv6 ）和网关，并配置服务处理器的 IP 源。



=== 命令按钮

* * 编辑 * 。
+
打开编辑服务处理器对话框，在此可以修改服务处理器的 IP 地址，网络掩码（ IPv4 ）或前缀长度（ IPv6 ）以及网关信息。

* * 全局设置 *
+
打开全局设置对话框，在此可以将所有服务处理器的 IP 地址源配置为以下选项之一： DHCP ，子网或手动。

* * 刷新 *
+
更新窗口中的信息。





=== 服务处理器列表

* *节点*
+
指定服务处理器所在的节点。

* * IP 地址 *
+
指定服务处理器的 IP 地址。

* * 状态 *
+
指定服务处理器的状态，可以是联机，脱机，守护进程脱机，节点脱机，已降级， 已重新启动或未知。

* *MAC地址*
+
指定服务处理器的 MAC 地址。





=== 详细信息区域

服务处理器列表下方的区域显示有关服务处理器的详细信息，包括网络详细信息，例如 IP 地址，网络掩码（ IPv4 ）或前缀长度（ IPv6 ），网关， IP 源， MAC 地址以及常规详细信息，例如固件版本以及是否启用了固件自动更新。

* 相关信息 *

xref:task_setting_up_network_when_ip_address_range_is_disabled.adoc[在禁用 IP 地址范围时设置网络]
