---
permalink: online-help-96-97/concept_system_alerts.html 
sidebar: sidebar 
keywords: system, manager, monitor, cluster, health, alerts, delete, 
summary: 您可以使用 System Manager 监控集群的不同部分。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本管理系统警报
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）监控集群的不同部分。



== 确认系统运行状况警报

您可以使用 System Manager 确认子系统的系统运行状况警报并对其做出响应。您可以使用显示的信息采取建议的操作并更正警报报告的问题。

.步骤
. 单击 * 事件和作业 * > * 系统警报 * 。
. 在 * 系统警报 * 窗口中，单击子系统名称旁边的箭头图标。
. 选择要确认的警报，然后单击 * 确认 * 。
. 键入您的姓名，然后单击 * 确认 * 。




== 禁止系统运行状况警报

您可以使用 System Manager 禁止不需要任何干预的系统运行状况警报。

.步骤
. 单击 * 事件和作业 * > * 系统警报 * 。
. 在 * 系统警报 * 窗口中，单击子系统名称旁边的箭头图标。
. 选择要禁止的警报，然后单击 * 禁止 * 。
. 键入您的名称，然后单击 * 禁止 * 。




== 删除系统运行状况警报

您可以使用 System Manager 删除已响应的系统运行状况警报。

.步骤
. 单击 * 事件和作业 * > * 系统警报 * 。
. 在 * 系统警报 * 窗口中，单击子系统名称旁边的箭头图标。
. 选择要删除的警报，然后单击 * 删除 * 。
. 单击 * 确定 * 。




== 可用的集群运行状况监控器

有多个运行状况监控器可监控集群的不同部分。运行状况监控器可以检测事件，向您发送警报以及在清除事件后删除事件，从而帮助您从 ONTAP 系统中的错误中恢复。

[cols="1a,1a,1a"]
|===
| 运行状况监控器名称（标识符） | 子系统名称（标识符） | 目的 


 a| 
集群交换机（集群交换机）
 a| 
交换机（交换机运行状况）
 a| 
监控集群网络交换机和管理网络交换机的温度，利用率，接口配置，冗余（仅限集群网络交换机）以及风扇和电源运行情况。集群交换机运行状况监控器通过 SNMP 与交换机通信。SNMPv2c 是默认设置。

[NOTE]
====
从 ONTAP 9.2 开始，此监控器可以检测并报告自上次轮询期间以来集群交换机重新启动的时间。

====


 a| 
MetroCluster 网络结构
 a| 
交换机
 a| 
监控 MetroCluster 配置后端网络结构拓扑并检测错误配置，例如布线和分区不正确以及 ISL 故障。



 a| 
MetroCluster 运行状况
 a| 
互连， RAID 和存储
 a| 
监控 FC-VI 适配器， FC 启动程序适配器，左后聚合和磁盘以及集群间端口



 a| 
节点连接（节点连接）
 a| 
CIFS 无中断运行（ CIFS-NDO ）
 a| 
监控 SMB 连接，确保 Hyper-V 应用程序无中断运行。



 a| 
存储（ SAS 连接）
 a| 
监控节点级别的磁盘架，磁盘和适配器，以查看适当的路径和连接。



 a| 
系统
 a| 
不适用
 a| 
聚合来自其他运行状况监控器的信息。



 a| 
系统连接（ system-connect ）
 a| 
存储（ SAS 连接）
 a| 
监控集群级别的磁盘架，以获取指向两个 HA 集群节点的适当路径。

|===


== 响应系统运行状况警报的方式

发生系统运行状况警报时，您可以确认该警报，了解其详细信息，修复基本状况并防止其再次发生。

当运行状况监控器发出警报时，您可以通过以下任一方式做出响应：

* 获取有关警报的信息，其中包括受影响的资源，警报严重性，可能的发生原因，可能的影响以及更正操作。
* 获取有关警报的详细信息，例如发出警报的时间以及是否有任何其他人已确认警报。
* 获取有关受影响资源或子系统的状态的运行状况信息，例如特定磁盘架或磁盘。
* 确认警报以指示有人正在处理此问题，并将您自己标识为 "`确认者。`
* 通过采取警报中提供的更正操作解决问题，例如修复布线以解决连接问题。
* 如果系统未自动清除警报，请将其删除。
* 禁止警报以防止其影响子系统的运行状况。
+
当您了解问题时，禁止非常有用。禁止警报后，警报可能仍会发生，但在出现禁止的警报时，子系统运行状况显示为 "`ok-on-suppressed 。` " 。





== 系统警报窗口

您可以使用系统警报窗口了解有关系统运行状况警报的更多信息。您还可以从窗口确认，删除和禁止警报。



=== 命令按钮

* * 确认 *
+
用于确认选定警报以指示问题已得到解决，并将单击按钮的人员标识为 "`确认者。` "

* * 禁止 *
+
用于禁止选定警报，以防止系统再次就同一警报通知您，并将您标识为 " `S阻止程序 " 。`

* * 删除 *
+
删除选定警报。

* * 刷新 *
+
更新窗口中的信息。





=== 警报列表

* * 子系统（编号警报数） *
+
显示为其生成警报的子系统的名称，例如 SAS 连接，交换机运行状况， CIFS NDO 或 MetroCluster 。

* * 警报 ID*
+
显示警报 ID 。

* *节点*
+
显示为其生成警报的节点的名称。

* * 严重性 *
+
将警报的严重性显示为未知，其他，信息，已降级，次要， 主要，严重或致命。

* * 资源 *
+
显示生成警报的资源，例如特定磁盘架或磁盘。

* * 时间 *
+
显示生成警报的时间。





=== 详细信息区域

详细信息区域显示有关警报的详细信息，例如生成警报的时间以及警报是否已确认。此区域还包括有关警报生成的条件的可能发生原因和可能影响的信息，以及更正警报报告的问题的建议操作。

* 相关信息 *

https://docs.netapp.com/us-en/ontap/system-admin/index.html["系统管理"]
