---
permalink: online-help-96-97/concept_iscsi_protocol.html 
sidebar: sidebar 
keywords: iscsi, protocol, system, manager, configure, block, data, host, tcp, ip, online, help, initiate, disable, enable, dialog, box, security, authentication, default 
summary: 您可以使用 System Manager 配置 iSCSI 协议，以便使用基于 TCP/IP 的 SCSI 协议将块数据传输到主机。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本配置 iSCSI 协议
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）配置 iSCSI 协议，以便使用 SCSI 协议通过 TCP/IP 将块数据传输到主机。



== 创建 iSCSI 别名

iSCSI 别名是一种便于用户识别的标识符，您可以将此标识符分配给 iSCSI 目标设备（此处为存储系统），以便在用户界面中更容易识别目标设备。您可以使用 System Manager 创建 iSCSI 别名。

.关于此任务
iSCSI 别名是一个包含 1 到 128 个可打印字符的字符串。 iSCSI 别名不能包含空格。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 协议 * 窗格中，单击 * iSCSI * 。
. 在 * iSCSI* 窗口的 * 服务 * 选项卡中，单击 * 编辑 * 。
. 在 * 编辑 iSCSI 服务配置 * 对话框的 * 目标别名 * 字段中输入 iSCSI 别名，然后单击 * 确定 * 。




== 在存储系统接口上启用或禁用 iSCSI 服务

您可以使用 System Manager 通过启用或禁用接口来控制用于 iSCSI 通信的网络接口。启用 iSCSI 服务后， iSCSI 连接和请求将通过为 iSCSI 启用的网络接口接受，但不会通过已禁用的接口接受。

.开始之前
您必须已终止当前正在使用此接口的所有未完成的 iSCSI 连接和会话。默认情况下，启用 iSCSI 许可证后，所有以太网接口上都会启用 iSCSI 服务。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 协议 * 窗格中，单击 * iSCSI * 。
. 在 * iSCSI 接口 * 区域中，选择要启用或禁用 iSCSI 服务的接口。
. 根据需要单击 * 启用 * 或 * 禁用 * 。




== 添加 iSCSI 启动程序的安全方法

您可以使用 System Manager 添加启动程序并指定用于对启动程序进行身份验证的安全方法。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 协议 * 窗格中，单击 * iSCSI * 。
. 在 * iSCSI * 窗口中，单击 * 启动程序安全性 * 选项卡。
. 单击 * 启动程序安全性 * 区域中的 * 添加 * 。
. 指定启动程序名称和用于对启动程序进行身份验证的安全方法。
+
对于 CHAP 身份验证，您必须提供用户名和密码，然后确认入站设置的密码。对于出站设置，此登录信息是可选的。

. 单击 * 确定 * 。




== 编辑默认安全设置

您可以使用 System Manager 中的编辑默认安全性对话框编辑连接到存储系统的 iSCSI 启动程序的默认安全设置。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 协议 * 窗格中，单击 * iSCSI * 。
. 在 * 启动程序安全性 * 选项卡的 * 默认安全性 * 区域中，单击 * 编辑 * 。
. 在 * 编辑默认安全性 * 对话框中，更改安全类型。
+
对于 CHAP 身份验证，您必须提供用户名和密码，然后确认入站设置的密码。对于出站设置，此登录信息是可选的。

. 单击 * 确定 * 。




== 更改默认 iSCSI 启动程序身份验证方法

您可以使用 System Manager 更改默认 iSCSI 身份验证方法，此身份验证方法适用于未配置特定身份验证方法的任何启动程序。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 协议 * 窗格中，单击 * iSCSI * 。
. 在 * 启动程序安全性 * 选项卡中，单击 * 默认安全性 * 区域中的 * 编辑 * 。
. 更改安全类型。
+
对于 CHAP 身份验证，您必须提供用户名和密码，然后确认入站设置的密码。对于出站设置，此登录信息是可选的。

. 单击 * 确定 * 。




== 设置 iSCSI 启动程序的默认安全性

您可以使用 System Manager 删除启动程序的身份验证设置，并使用默认安全方法对启动程序进行身份验证。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 协议 * 窗格中，单击 * iSCSI * 。
. 在 * 启动程序安全性 * 选项卡中，选择要更改安全设置的启动程序。
. 单击 * 启动程序安全性 * 区域中的 * 设置默认值 * ，然后单击确认对话框中的 * 设置默认值 * 。




== 启动或停止 iSCSI 服务

您可以使用 System Manager 在存储系统上启动或停止 iSCSI 服务。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 协议 * 窗格中，单击 * iSCSI * 。
. 根据需要单击 * 开始 * 或 * 停止 * 。




== 查看启动程序安全信息

您可以使用 System Manager 查看默认身份验证信息以及所有特定于启动程序的身份验证信息。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 协议 * 窗格中，单击 * iSCSI * 。
. 在 * iSCSI* 窗口的 * 启动程序安全性 * 选项卡中，查看详细信息。




== iSCSI 窗口

您可以使用 iSCSI 窗口启动或停止 iSCSI 服务，更改存储系统 iSCSI 节点名称以及创建或更改存储系统的 iSCSI 别名。您还可以为连接到存储系统的 iSCSI 启动程序添加或更改启动程序安全设置。



=== 选项卡

* * 服务 *
+
您可以使用 * 服务 * 选项卡启动或停止 iSCSI 服务，更改存储系统 iSCSI 节点名称以及创建或更改存储系统的 iSCSI 别名。

* * 启动程序安全性 *
+
您可以使用 * 启动程序安全性 * 选项卡为连接到存储系统的 iSCSI 启动程序添加或更改启动程序安全性设置。





=== 命令按钮

* * 编辑 * 。
+
打开编辑 iSCSI 服务配置对话框，在此可以更改存储系统的 iSCSI 节点名称和 iSCSI 别名。

* * 启动 *
+
启动 iSCSI 服务。

* * 停止 *
+
停止 iSCSI 服务。

* * 刷新 *
+
更新窗口中的信息。





=== 详细信息区域

详细信息区域显示有关 iSCSI 服务状态， iSCSI 目标节点名称和 iSCSI 目标别名的信息。您可以使用此区域在网络接口上启用或禁用 iSCSI 服务。

* 相关信息 *

https://docs.netapp.com/us-en/ontap/san-admin/index.html["SAN 管理"^]
