---
permalink: online-help-96-97/concept_managing_network.html 
sidebar: sidebar 
keywords: system, manager, storage, create, manage, ipspace, broadcast, domain, subnet, network, interface, ethernet, port, fc, fcoe, adapter, online, help 
summary: 您可以使用 System Manager 通过创建和管理 IP 空间，广播域，子网，网络接口，以太网端口， 和 FC/FCoE 适配器。 
---
= 使用 System Manager — ONTAP 9.7 及更早版本管理网络
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （在 ONTAP 9.7 及更早版本中提供）通过创建和管理 IP 空间，广播域，子网，网络接口，以太网端口， 和 FC/FCoE 适配器。



== 网络窗口

[role="lead"]
您可以使用网络窗口查看网络组件列表，例如子网，网络接口，以太网端口，广播域， FC/FCoE 和 NVMe 适配器以及 IP 空间，以及在存储系统中创建，编辑或删除这些组件。



=== 选项卡

* * 子网 *
+
用于查看子网列表以及在存储系统中创建，编辑或删除子网。

* * 网络接口 *
+
用于查看网络接口列表，在存储系统中创建，编辑或删除接口，迁移 LIF ，更改接口状态以及将接口发送回主端口。

* * 以太网端口 *
+
用于查看和编辑集群的端口，以及创建，编辑或删除接口组和 VLAN 端口。

* * 广播域 *
+
用于查看广播域列表以及在存储系统中创建，编辑或删除域。

* * FC/FCoE 和 NVMe 适配器 *
+
用于查看集群中的端口以及编辑 FC/FCoE 和 NVMe 适配器设置。

* * IP 空间 *
+
用于查看 IP 空间和广播域列表，以及在存储系统中创建，编辑或删除 IP 空间。





=== 子网选项卡



=== 命令按钮

* * 创建 * 。
+
打开创建子网对话框，在此可以创建包含用于创建网络接口的配置信息的新子网。

* * 编辑 * 。
+
打开编辑子网对话框，在此可以修改子网的某些属性，例如名称，子网地址， IP 地址范围和网关详细信息。

* * 删除 *
+
删除选定子网。

* * 刷新 *
+
更新窗口中的信息。





=== 子网列表

* * 名称 *
+
指定子网的名称。

* * 子网 IP/ 子网掩码 *
+
指定子网地址详细信息。

* * 网关 *
+
指定网关的 IP 地址。

* * 可用 *
+
指定子网中可用的 IP 地址数。

* * 已用 *
+
指定子网中使用的 IP 地址数。

* * 总数 *
+
指定子网中的总 IP 地址数（可用和已用）。

* * 广播域 *
+
指定子网所属的广播域。

* * IP 空间 *
+
指定子网所属的 IP 空间。





=== 详细信息区域

子网列表下方的区域显示有关选定子网的详细信息，包括子网范围以及显示可用 IP 地址数，已用 IP 地址数和总 IP 地址数的图形。



=== 网络接口选项卡的限制

* 对于集群 LIF ，节点管理 LIF ， VIP LIF 和 BGP LIF ，您不能使用 System Manager 执行以下操作：
+
** 创建，编辑，删除，启用或禁用 LIF
** 迁移 LIF 或将 LIF 发送回主端口


* 对于集群管理 LIF ，您可以使用 System Manager 迁移 LIF 或将 LIF 发送回主端口。
+
但是，您不能创建，编辑，删除，启用， 或禁用 LIF 。

* 对于集群间 LIF ，您可以使用 System Manager 创建，编辑，删除，启用或禁用 LIF 。
+
但是，您不能迁移 LIF 或将 LIF 发送回主端口。

* 您不能在以下配置中创建，编辑或删除网络接口：
+
** MetroCluster 配置
** 为灾难恢复（ DR ）配置的 SVM 。






=== 命令按钮

* * 创建 * 。
+
打开创建网络接口对话框，在此可以创建网络接口和集群间 LIF 以提供数据和管理 SVM 。

* * 编辑 * 。
+
打开编辑网络接口对话框，在此可以为数据 LIF 启用管理访问。

* * 删除 *
+
删除选定的网络接口。

+
只有在禁用数据 LIF 时，才会启用此按钮。

* * 状态 *
+
打开下拉菜单，其中提供了用于启用或禁用选定网络接口的选项。

* * 迁移 *
+
用于将数据 LIF 或集群管理 LIF 迁移到集群中同一节点或不同节点上的其他端口。

* * 发送到主页 *
+
用于将 LIF 重新托管在其主端口上。

+
只有在选定接口托管在非主端口上且主端口可用时，才会启用此命令按钮。

+
当集群中的任何节点关闭时，此命令按钮将被禁用。

* * 刷新 *
+
更新窗口中的信息。





=== 接口列表

您可以将指针移动到带颜色的图标上以查看接口的运行状态：

* 绿色指定接口已启用。
* 红色指定接口已禁用。
* * 接口名称 *
+
指定网络接口的名称。

* * Storage Virtual Machine*
+
指定接口所属的 SVM 。

* * IP 地址 /WWPN
+
指定接口的 IP 地址或全球通用端口名称（ WWPN ）。

* * 当前端口 *
+
指定托管接口的节点和端口的名称。

* * 数据协议访问 *
+
指定用于访问数据的协议。

* * 管理访问 *
+
指定是否在接口上启用管理访问。

* * 子网 *
+
指定接口所属的子网。

* * mx角色*
+
指定接口的操作角色，可以是数据，集群间，集群，集群管理或节点管理。





=== 详细信息区域

接口列表下方的区域显示有关选定接口的详细信息：故障转移属性，例如主端口，当前端口，端口速度，故障转移策略，故障转移组和故障转移状态，以及常规属性，例如管理状态，角色， IP 空间，广播域，网络掩码， 网关和 DDNS 状态。



=== 以太网端口选项卡



=== 命令按钮

* * 创建接口组 *
+
打开创建接口组对话框，在此可以通过选择端口并确定端口的使用和网络流量分布来创建接口组。

* * 创建 VLAN*
+
打开创建 VLAN 对话框，在此可以通过选择以太网端口或接口组并添加 VLAN 标记来创建 VLAN 。

* * 编辑 * 。
+
打开以下对话框之一：

+
** 编辑以太网端口对话框：用于修改以太网端口设置。
** 编辑 VLAN 对话框：用于修改 VLAN 设置。
** 编辑接口组对话框：用于修改接口组。


+
您只能编辑未与广播域关联的 VLAN 。

* * 删除 *
+
打开以下对话框之一：

+
** 删除 VLAN 对话框：用于删除 VLAN 。
** 删除接口组对话框：用于删除接口组。


* * 刷新 *
+
更新窗口中的信息。





=== 端口列表

您可以将指针移动到带颜色的图标上以查看端口的运行状态：

* 绿色表示端口已启用。
* 红色表示端口已禁用。
* * 端口 *
+
显示物理端口， VLAN 端口或接口组的端口名称。

* *节点*
+
显示物理接口所在的节点。

* * 广播域 *
+
显示端口的广播域。

* * IP 空间 *
+
显示端口所属的 IP 空间。

* * 类型 *
+
显示接口的类型，例如接口组，物理接口， VIP 或 VLAN 。





=== 详细信息区域

端口列表下方的区域显示有关端口属性的详细信息。

* * 详细信息选项卡 *
+
显示管理详细信息和操作详细信息。

+
在操作详细信息中，此选项卡会显示端口的运行状况。这些端口可能运行状况良好或已降级。降级端口是指发生持续网络波动的端口，或者与同一广播域中的任何其他端口没有连接的端口。

+
此外，此选项卡还会显示选定端口上托管的网络接口的接口名称， SVM 详细信息和 IP 地址详细信息。它还指示接口是否位于主端口。

* * 性能选项卡 *
+
显示以太网端口的性能指标图，包括错误率和吞吐量。

+
更改客户端时区或集群时区会影响性能指标图。您应刷新浏览器以查看更新后的图形。





=== 广播域选项卡



=== 命令按钮

* * 创建 * 。
+
打开创建广播域对话框，在此可以创建新的广播域以包含端口。

* * 编辑 * 。
+
打开编辑广播域对话框，在此可以修改广播域的属性，例如名称， MTU 大小和关联端口。

* * 删除 *
+
删除选定广播域。

* * 刷新 *
+
更新窗口中的信息。





=== 广播域列表

* * 广播域 *
+
指定广播域的名称。

* * MTU *
+
指定 MTU 大小。

* * IP 空间 *
+
指定 IP 空间。

* * 组合端口更新状态 *
+
指定在创建或编辑广播域时端口更新的状态。端口更新中的任何错误都会显示在一个单独的窗口中，您可以通过单击关联的链接打开该窗口。





=== 详细信息区域

广播域列表下方的区域显示广播域中的所有端口。在非默认 IP 空间中，如果广播域的端口存在更新错误，则此类端口不会显示在详细信息区域中。您可以将指针移动到带颜色的图标上以查看端口的运行状态：

* 绿色表示端口已启用。
* 红色表示端口已禁用。




=== FC/FCoE 和 NVMe 适配器选项卡



=== 命令按钮

* * 编辑 * 。
+
打开编辑 FC/FCoE 和 NVMe 设置对话框，在此可以修改适配器的速度。

* * 状态 *
+
用于使适配器联机或脱机。

* * 刷新 *
+
更新窗口中的信息。





=== FC/FCoE 和 NVMe 适配器列表

* * WWN*
+
指定 FC/FCoE 和 NVMe 适配器的唯一标识符。

* * 节点名称 *
+
指定正在使用适配器的节点的名称。

* * 插槽 *
+
指定使用适配器的插槽。

* * WWPN *
+
指定适配器的 FC 全球通用端口名称（ WWPN ）。

* * 状态 *
+
指定适配器的状态是联机还是脱机。

* * 速度 *
+
指定速度设置是自动设置还是手动设置。





=== 详细信息区域

FC/FCoE 和 NVMe 适配器列表下方的区域显示有关选定适配器的详细信息。

* * 详细信息选项卡 *
+
显示适配器详细信息，例如介质类型，端口地址，数据链路速率，连接状态，操作状态， 网络结构状态以及适配器的速度。

* * 性能选项卡 *
+
显示 FC/FCoE 和 NVMe 适配器的性能指标图，包括 IOPS 和响应时间。

+
更改客户端时区或集群时区会影响性能指标图。您应刷新浏览器以查看更新后的图形。





=== IP 空间选项卡



=== 命令按钮

* * 创建 * 。
+
打开创建 IP 空间对话框，在此可以创建新的 IP 空间。

* * 编辑 * 。
+
打开编辑 IP 空间对话框，在此可以重命名现有 IP 空间。

* * 删除 *
+
删除选定的 IP 空间。

* * 刷新 *
+
更新窗口中的信息。





=== IP 空间列表

* * 名称 *
+
指定 IP 空间的名称。

* * 广播域 *
+
指定广播域。





=== 详细信息区域

IP 空间列表下方的区域显示选定 IP 空间中的 Storage Virtual Machine （ SVM ）列表。
