---
permalink: online-help-96-97/concept_svm_user_accounts.html 
sidebar: sidebar 
keywords: system, manager, create, manage, online, help, storage, virtual, machine, svm, user, account, password, change, lock, unlock , command, button 
summary: 您可以使用 System Manager 创建和管理 Storage Virtual Machine （ SVM ）用户帐户。 
---
= 使用System Manager - ONTAP 9.7及更早版本创建和管理SVM用户帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）创建和管理 Storage Virtual Machine （ SVM ）用户帐户。



== 添加 SVM 用户帐户

您可以使用 System Manager 添加 Storage Virtual Machine （ SVM ）用户帐户，并指定用于访问存储系统的用户登录方法。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * SVM 用户详细信息 * 窗格中，单击 * 用户 * 。
. 单击 * 添加 * 。
. 指定用于连接到存储系统的用户名和密码，然后确认该密码。
. 添加一种或多种用户登录方法，然后单击 * 添加 * 。
+
系统会自动为新 vsadmin 帐户提供一种登录方法，该方法使用 HTTP 作为应用程序，并使用证书进行身份验证。





== 更改 SVM 用户帐户的密码

您可以使用 System Manager 重置 Storage Virtual Machine （ SVM ）用户帐户的密码。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * SVM 用户详细信息 * 窗格中，单击 * 用户 * 。
. 选择要修改密码的用户帐户，然后单击 * 重置密码 * 。
. 在 * 重置密码 * 对话框中，键入新密码并确认新密码，然后单击 * 更改 * 。




== 编辑 SVM 用户帐户

您可以使用 System Manager 通过修改用于访问存储系统的用户登录方法来编辑 Storage Virtual Machine （ SVM ）用户帐户。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * SVM 用户详细信息 * 窗格中，单击 * 用户 * 。
. 选择要编辑的用户帐户，然后单击 * 编辑 * 。
. 修改一种或多种用户登录方法，然后单击 * 修改 * 。




== 锁定或解除锁定 SVM 用户帐户

您可以使用 System Manager 锁定或解除锁定 Storage Virtual Machine （ SVM ）用户帐户。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * SVM 用户详细信息 * 窗格中，单击 * 用户 * 。
. 在 * 用户 * 窗口中，选择要修改帐户状态的用户帐户，然后根据需要单击 * 锁定 * 或 * 解锁 * 。




== 用户窗口

您可以使用用户窗口管理用户帐户，重置用户密码以及查看有关所有用户帐户的信息。



=== 命令按钮

* * 添加 * 。
+
打开添加用户对话框，在此可以添加用户帐户。

* * 编辑 * 。
+
打开修改用户对话框，在此可以修改用户登录方法。

+
[NOTE]
====
最佳做法是，对用户帐户的所有访问和身份验证方法使用一个角色。

====
* * 删除 *
+
用于删除选定用户帐户。

* * 更改密码 *
+
打开更改密码对话框，在此可以重置选定用户的密码。

* * 锁定 *
+
锁定用户帐户。

* * 刷新 *
+
更新窗口中的信息。





=== 用户列表

用户列表下方的区域显示有关选定用户的详细信息。

* * 用户 *
+
显示用户帐户的名称。

* * 帐户已锁定 *
+
显示用户帐户是否已锁定。





=== 用户登录方法区域

* * 应用程序 *
+
显示用户可用于访问存储系统的访问方法。支持的访问方法包括：

+
** 系统控制台（控制台）
** HTTP （ S ）（ http ）
** ONTAP API （ ontapi ）
** 服务处理器（ service-processor ）
** SSH （ ssh ）


* * 身份验证 *
+
显示支持的默认身份验证方法，即 "`password` " 。

* * 角色 *
+
显示选定用户的角色。


