---
permalink: online-help-96-97/concept_aggregates.html 
sidebar: sidebar 
keywords: aggregates, system, manager, security, backup, performance, data, sharing, classic, online, help, window 
summary: 您可以使用 System Manager 创建聚合，以满足用户不同的安全性，备份，性能和数据共享要求。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本管理聚合
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）创建聚合，以满足用户不同的安全性，备份，性能和数据共享要求。



== 聚合窗口

您可以使用聚合窗口创建，显示和管理有关聚合的信息。



=== 命令按钮

* * 创建 * 。
+
打开创建聚合对话框，在此可以创建聚合。

* * 编辑 * 。
+
打开编辑聚合对话框，在此可以更改聚合的名称或要为聚合提供的 RAID 保护级别。

* * 删除 *
+
删除选定聚合。

+
[NOTE]
====
已对根聚合禁用此按钮。

====
* * 更多操作 *
+
提供了以下选项：

* * 将状态更改为 *
+
将选定聚合的状态更改为以下状态之一：

+
** 联机
+
允许对此聚合中包含的卷进行读写访问。

** 脱机
+
不允许进行读写访问。

** 限制
+
允许执行某些操作，例如奇偶校验重建，但不允许数据访问。



* * 添加容量 *
+
用于向现有聚合添加容量（ HDD 或 SSD ）。

* * 添加缓存 *
+
用于向现有 HDD 聚合或 Flash Pool 聚合添加缓存磁盘（ SSD ）。

+
如果集群中的节点具有全闪存优化特性，则此按钮不可用。

* * 镜像 *
+
用于镜像聚合。

* * 卷移动 *
+
用于移动 FlexVol 卷。

* * 附加云层 *
+
用于将云层附加到聚合。

* * 刷新 *
+
更新窗口中的信息。





=== 聚合列表

显示每个聚合的名称和空间使用情况信息。

* * 状态 *
+
显示聚合的状态。

* * 名称 *
+
显示聚合的名称。

* *节点*
+
显示将聚合中的磁盘分配到的节点的名称。

+
此字段仅在集群级别可用。

* * 类型 *
+
显示聚合的类型。

+
对于包含具有全闪存优化特性的节点的集群，不会显示此字段。

* * 已用（ % ） *
+
显示聚合中已用空间的百分比。

* * 可用空间 *
+
显示聚合中的可用空间。

* * 已用空间 *
+
显示聚合中的数据所使用的空间量。

* * 总空间 *
+
显示聚合的总空间。

* * FabricPool *
+
显示选定聚合是否已附加到云层。

* * 云层 *
+
如果选定聚合已附加到云层，则会显示此云层的名称。

* * 卷计数 *
+
显示与聚合关联的卷数。

* * 磁盘计数 *
+
显示用于创建聚合的磁盘数。

* * 闪存池 *
+
显示 Flash Pool 聚合的总缓存大小。如果值为 NA ，则表示此聚合不是 Flash Pool 聚合。

+
对于包含具有全闪存优化特性的节点的集群，不会显示此字段。

* * 镜像 *
+
显示聚合是否已镜像。

* * SnapLock 类型 *
+
显示聚合的 SnapLock 类型。





=== 详细信息区域

选择一个聚合以查看有关选定聚合的信息。您可以单击显示更多详细信息以查看有关选定聚合的详细信息。

* * 概述选项卡 *
+
显示有关选定聚合的详细信息，并以图形方式显示聚合的空间分配，聚合的空间节省以及聚合在 IOPS 和总数据传输方面的性能。

* * 磁盘信息选项卡 *
+
显示磁盘布局信息，例如磁盘名称，磁盘类型，物理大小，可用大小，磁盘位置， 磁盘状态，丛名称，丛状态， RAID 组， RAID 类型， 和存储池（如果有）。此外，还会显示与多路径配置中的磁盘主路径关联的磁盘端口以及与磁盘二级路径关联的磁盘名称。

* * 卷选项卡 *
+
显示有关聚合上的卷总数，聚合总空间以及提交给聚合的空间的详细信息。

* * 性能选项卡 *
+
显示用于显示聚合性能指标的图形，包括吞吐量和 IOPS 。显示读取，写入和总传输的吞吐量和 IOPS 性能指标数据，并单独记录 SSD 和 HDD 的数据。

+
更改客户端时区或集群时区会影响性能指标图。您应刷新浏览器以查看更新后的图形。



* 相关信息 *

xref:task_provisioning_storage_through_aggregates.adoc[通过聚合配置存储]

xref:task_deleting_aggregates.adoc[正在删除聚合]

xref:task_editing_aggregates.adoc[编辑聚合]
