---
permalink: online-help-96-97/concept_schedules.html 
sidebar: sidebar 
keywords: online, help, system, manager, manage, schedule, storage 
summary: 您可以使用 System Manager 在存储系统中创建和管理计划。 
---
= 使用System Manager - ONTAP 9.7及更早版本管理计划
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP System Manager classic (适用于ONTAP 9.7及更早版本)在存储系统中创建和管理计划。



== 创建计划

您可以使用 System Manager 创建计划，以便在特定时间或定期运行作业。

.关于此任务
在 MetroCluster 配置中创建计划时，最好也在运行正常的站点的集群上创建等效的计划。

.步骤
. 单击 * 保护 * > * 计划 * 。
. 单击 * 创建 * 。
. 在 * 创建计划 * 对话框中，指定计划名称。
. 根据您的要求创建计划：
+
|===
| 要创建的内容 | 执行此操作 ... 


 a| 
某天的每日计划或特定计划
 a| 
选择 * 基本 * ，然后指定计划和重复设置详细信息（以小时和分钟为单位）。



 a| 
按特定间隔运行的计划
 a| 
选择 * 间隔 * ，然后指定计划和重复设置详细信息（以天，小时和分钟为单位）。



 a| 
在特定时间段运行的计划
 a| 
选择 * 高级 * ，然后指定计划和重复设置详细信息（以月，天，工作日，小时和分钟为单位）。

|===
. 单击 * 创建 * 。




== 编辑计划

如果先前创建的 cron 计划或间隔计划不符合您的要求，您可以使用 System Manager 对其进行更改。您可以修改计划详细信息，例如重复天数和小时数，间隔选项和高级 cron 选项。

.关于此任务
在 MetroCluster 配置中编辑计划时，最好也在运行正常的站点集群上编辑等效计划。

.步骤
. 单击 * 保护 * > * 计划 * 。
. 选择要修改的计划并单击 * 编辑 * 。
. 在 * 编辑计划 * 对话框中，通过执行相应的操作来修改计划：
+
|===
| 如果选择的计划选项为 ... | 执行此操作 ... 


 a| 
基本
 a| 
指定重复天数和重复计划详细信息。



 a| 
interval
 a| 
以天，小时和分钟为单位指定间隔选项。



 a| 
高级
 a| 
以月，天，工作日（如果适用），小时和分钟为单位指定高级 cron 选项。

|===
. 单击 * 确定 * 。




== 删除计划

您可以使用 System Manager 删除运行特定存储管理任务的计划。

.步骤
. 单击 * 保护 * > * 计划 * 。
. 选择要删除的计划并单击 * 删除 * 。
. 选中确认复选框，然后单击 * 删除 * 。




== 管理计划

您可以配置许多任务（例如，卷 Snapshot 副本和镜像复制），使其按指定计划运行。按指定计划运行的计划称为_cron_计划、因为它们与UNIX相似 `cron` 计划。按间隔运行的计划称为 _interval_ 计划。

您可以通过以下方式管理计划：

* 创建 cron 计划或间隔计划
* 显示有关所有计划的信息
* 修改 cron 计划或间隔计划
* 删除 cron 计划或间隔计划
+
您不能删除正在运行的作业当前正在使用的计划。



集群管理员可以执行所有计划管理任务。



== 计划窗口

您可以使用计划窗口管理已计划的任务，例如创建，显示有关计划的信息，修改和删除计划。



=== 命令按钮

* * 创建 * 。
+
打开创建计划对话框，在此可以创建基于时间的计划和间隔计划。

* * 编辑 * 。
+
打开编辑计划对话框，在此可以编辑选定计划。

* * 删除 *
+
打开删除计划对话框，在此可以删除选定计划。

* * 刷新 *
+
更新窗口中的信息。





=== 计划列表

* * 名称 *
+
指定计划的名称。

* * 类型 *
+
指定计划的类型—基于时间或基于间隔。





=== 详细信息区域

详细信息区域显示有关何时运行选定计划的信息。
