---
permalink: online-help-96-97/concept_namespace.html 
sidebar: sidebar 
keywords: junction, path, window, system, manager, mount, unmount, flexvol, volume, svm, namespace, online, help, policies, export 
summary: 您可以使用 System Manager 中的接合路径窗口将 FlexVol 卷挂载或卸载到 SVM 命名空间中的接合位置。 
---
= System Manager 中的接合路径窗口— ONTAP 9.7 及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （在 ONTAP 9.7 及更早版本中提供）中的接合路径窗口将 FlexVol 卷挂载或卸载到 SVM 命名空间中的接合位置。



== 挂载卷

您可以使用 System Manager 将卷挂载到 Storage Virtual Machine （ SVM ）命名空间中的接合位置。

.关于此任务
* 如果将卷挂载到的接合路径的语言设置与该路径中直接父卷的语言设置不同，则 NFSv3 客户端将无法访问某些文件，因为某些字符可能无法正确解码。
+
如果直接父目录为根卷，则不会发生此问题描述。

* 您只能将 SnapLock 卷挂载到 SVM 的根目录下。
* 不能将常规卷挂载到 SnapLock 卷下。


.步骤
. 单击 * 存储 * > * 接合路径 * 。
. 从 * SVM* 字段的下拉菜单中选择要挂载卷的 SVM 。
. 单击 * 挂载 * ，然后选择要挂载的卷。
. *可选：*如果要更改默认接合名称、请指定一个新名称。
. 单击 * 浏览 * ，然后选择要将卷挂载到的接合路径。
. 单击 * 确定 * ，然后单击 * 挂载 * 。
. 在 * 详细信息 * 选项卡中验证新的接合路径。




== 卸载 FlexVol 卷

您可以使用 System Manager 中存储窗格的接合路径选项从 Storage Virtual Machine （ SVM ）命名空间中的接合卸载 FlexVol 卷。

.步骤
. 单击 * 存储 * > * 接合路径 * 。
. 从 * SVM* 字段的下拉菜单中，选择要从中卸载卷的 SVM 。
. 选择必须卸载的卷，然后单击 * 卸载 * 。
. 选中确认复选框，然后单击 * 卸载 * 。




== 更改导出策略

创建卷时，该卷会自动继承 Storage Virtual Machine （ SVM ）根卷的默认导出策略。您可以使用 System Manager 更改与卷关联的默认导出策略，以重新定义客户端对数据的访问。

.步骤
. 单击 * 存储 * > * 接合路径 * 。
. 从 * SVM* 字段的下拉菜单中，选择要修改的卷所在的 SVM 。
. 选择卷，然后单击 * 更改导出策略 * 。
. 选择导出策略，然后单击 * 更改 * 。
. 验证 * 接合路径 * 窗口中的 * 导出策略 * 列是否显示您应用于卷的导出策略。


.结果
默认导出策略将替换为选定的导出策略。



== 接合路径窗口

您可以使用接合路径菜单管理 Storage Virtual Machine （ SVM ）的 NAS 命名空间。



=== 命令按钮

* * 挂载 *
+
打开挂载卷对话框，在此可以将卷挂载到 SVM 命名空间中的接合位置。

* * 卸载 *
+
打开卸载卷对话框，在此可以从父卷卸载卷。

* * 更改导出策略 *
+
打开更改导出策略对话框，在此可以更改与卷关联的现有导出策略。

* * 刷新 *
+
更新窗口中的信息。





=== 接合路径列表

* * 路径 *
+
指定已挂载卷的接合路径。您可以单击接合路径以查看相关卷和 qtree 。

* * 存储对象 *
+
指定挂载在接合路径上的卷的名称。您还可以查看卷包含的 qtree 。

* * 导出策略 *
+
指定已挂载卷的导出策略。

* * 安全模式 *
+
指定卷的安全模式。可能的值包括 UNIX （对于 UNIX 模式位）， NTFS （对于 CIFS ACL ）和混合（对于混合 NFS 和 CIFS 权限）。





=== 详细信息选项卡

显示有关选定卷或 qtree 的常规信息，例如名称，存储对象类型，挂载对象的接合路径和导出策略。如果选定对象是 qtree ，则会显示有关空间硬限制，空间软限制和空间使用量的详细信息。
