---
permalink: online-help-96-97/reference_application_provisioning_settings.html 
sidebar: sidebar 
keywords: application, provisioning, setting, microsoft, sql, database, applications, san, mongodb, oracle, host, access, initiator, sap, hana, smb 
summary: 在为数据库，服务器或虚拟桌面设置基本或增强型模板时，您必须向 System Manager 提供详细信息。配置应用程序后，您可以编辑详细信息并指定调整大小（仅增加大小）。本节介绍每个模板中的字段。仅显示配置或编辑特定应用程序设置所需的字段。 
---
= System Manager - ONTAP 9.7 及更早版本中的应用程序配置设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）中为数据库，服务器或虚拟桌面设置基本或增强型模板时，您必须提供详细信息。配置应用程序后，您可以编辑详细信息并指定调整大小（仅增加大小）。本节介绍每个模板中的字段。仅显示配置或编辑特定应用程序设置所需的字段。



== 有关基于 SAN 的 Microsoft SQL 数据库应用程序的详细信息

要通过 SAN 配置 Microsoft SQL 数据库应用程序或编辑这些设置，请输入以下信息：

* * 数据库名称 *
+
必填：要配置的数据库的名称；在为每个数据库配置存储时，此字符串用作前缀。

* * 数据库大小 *
+
必填：数据库的大小，以 MB ， GB ， TB 或 PB 为单位。

* * 数据库的 ONTAP 服务级别 *
+
必填：数据库的服务级别。

* * 日志大小 *
+
必填：数据库日志的大小，以 MB ， GB ， TB 或 PB 为单位。

* 日志的 * ONTAP 服务级别 *
+
必填：日志的服务级别。

* * tempdb*
+
必填： tempdb 数据库的大小，以 MB ， GB ， TB 或 PB 为单位。

* * 导出协议 *
+
必填：导出协议为 SAN

* * 服务器核心数（在 SQL 服务器上） *
+
指示数据库服务器上的 CPU 核数，以 2 为增量。

* * 跨越 HA 控制器节点 *
+
指定是否应在高可用性节点对中创建存储对象。





== 有关配置 SAP HANA 数据库的详细信息

* * 活动 SAP HANA 节点 *
+
活动 SAP HANA 节点的数量。最大节点数为 16 。

* 每个 HANA 节点的 * 内存大小 *
+
单个 SAP HANA 节点的内存大小。

* * 每个 HANA 节点的数据磁盘大小 *
+
每个节点的数据磁盘大小。

+
[NOTE]
====
如果设置为 0 ，则使用上述内存大小字段计算数据区域的大小。

====




== 基于 SMB 的 Microsoft SQL 数据库应用程序的详细信息

要通过 SMB 配置 Microsoft SQL 数据库应用程序或编辑设置，请输入以下信息：

* * 数据库名称 *
+
必填：要配置的数据库的名称；在为每个数据库配置存储时，此字符串用作前缀。

* * 数据库大小 *
+
必填：数据库的大小，以 MB ， GB ， TB 或 PB 为单位。

* * 数据库服务级别 *
+
必填：数据库的服务级别。

* * 服务器核心数（在 SQL 服务器上） *
+
指示数据库服务器上的 CPU 核数，以 2 为增量。

* * 日志大小 *
+
必填：数据库日志的大小，以 MB ， GB ， TB 或 PB 为单位。

* * 日志服务级别 *
+
必填：日志的服务级别。

* * 为 tempdb 配置 *
+
必填：指示是否配置了 tempdb 。

* * 导出协议 *
+
必填：导出协议为 SMB 或 SAN 。

+
只有在集群已获得 CIFS 许可且已为 SVM 配置 CIFS 时，才能选择 SMB 。

* * 授予用户访问权限 *
+
必填：应用程序的访问级别。

* * 权限 *
+
必填：应用程序的权限级别。





== SQL Server 帐户的详细信息

您可以输入以下信息来提供对 SQL Server 帐户的完全控制访问：

[NOTE]
====
此时将授予安装帐户 `SeSecurityPrivilege`。

====
* * SQL Server 服务帐户 *
+
必填：这是一个现有域帐户；请指定为 `domain\user`。

* * SQL Server 代理服务帐户 *
+
可选：如果配置了 SQL Server 代理服务，则此帐户为域帐户，请以 " 域 \ 用户 " 格式指定。





== Oracle 数据库应用程序详细信息

您可以输入以下信息来配置 Oracle 数据库应用程序或编辑设置：

* * 数据库名称 *
+
必填：要配置的数据库的名称；在为每个数据库配置存储时，此字符串用作前缀。

* * 数据文件大小 *
+
必填：数据文件的大小，以 MB ， GB ， TB 或 PB 为单位。

* 数据文件的 * ONTAP 服务级别 *
+
必填：数据文件的服务级别。

* * 重做日志组大小 *
+
必填：重做日志组的大小，以 MB ， GB ， TB 或 PB 为单位。

* 重做日志组的 * ONTAP 服务级别 *
+
必填：重做日志组的服务级别。

* * 归档日志大小 *
+
必填：归档日志的大小，以 MB ， GB ， TB 或 PB 为单位。

* 归档日志的 * ONTAP 服务级别 *
+
必填：归档组的服务级别。

* * 导出协议 *
+
导出协议： SAN 或 NFS

* * 启动程序 *
+
启动程序组中的启动程序（ WWPN 或 IQN ）列表，以英文逗号分隔。

* * 授予对主机的访问权限 *
+
用于授予应用程序访问权限的主机名。





== MongoDB 应用程序的详细信息

要配置 MongoDB 应用程序或编辑设置，请输入以下信息：

* * 数据库名称 *
+
必填：要配置的数据库的名称；在为每个数据库配置存储时，此字符串用作前缀。

* * 数据集大小 *
+
必填：数据文件的大小，以 MB ， GB ， TB 或 PB 为单位。

* * 数据集的 ONTAP 服务级别 *
+
必填：数据文件的服务级别。

* * 复制因子 *
+
必填：复制的数量。

* * 主主机的映射 *
+
必填：主主机的名称。

* * 副本主机 1 的映射 *
+
必填：第一个主机副本的名称。

* *副本主机的映射2*
+
必填：第二个主机副本的名称。





== 虚拟桌面应用程序的详细信息

要配置虚拟桌面基础架构 (VDI) 或编辑设置，请输入以下信息：

* * 平均桌面大小（用于 SAN 虚拟桌面） *
+
此选项用于确定每个卷的精简配置大小，以 MB ， GB ， TB 或 PB 为单位。

* * 桌面大小 *
+
此选项用于确定应配置的卷的大小，以 MB ， GB ， TB 或 PB 为单位。

* * 适用于桌面的 ONTAP 服务级别 *
+
必填：数据文件的服务级别。

* * 桌面数量 *
+
此数字用于确定创建的卷数。

+
[NOTE]
====
此选项不用于配置虚拟机。

====
* * 选择虚拟机管理程序 *
+
用于这些卷的虚拟机管理程序；虚拟机管理程序确定正确的数据存储库协议。选项包括 VMware ， Hyper-V 或 XenServer/KVM 。

* * 桌面持久性 *
+
确定桌面是持久桌面还是非持久桌面。选择桌面持久性可设置卷的默认值，例如 Snapshot 计划和后处理重复数据删除策略。默认情况下，所有卷都会启用实时效率。

+
[NOTE]
====
配置后，可以手动修改这些策略。

====
* * 数据存储库前缀 *
+
输入的值用于生成数据存储库的名称以及导出策略名称或共享名称（如果适用）。

* * 导出协议 *
+
导出协议： SAN 或 NFS

* * 启动程序 *
+
启动程序组中的启动程序（ WWPN 或 IQN ）列表，以英文逗号分隔。

* * 授予对主机的访问权限 *
+
用于授予应用程序访问权限的主机名。





== 启动程序详细信息

要设置启动程序，请输入以下信息：

* * 启动程序组 *
+
您可以选择现有组或创建新组。

* * 启动程序组名称 *
+
新启动程序组的名称。

* * 启动程序 *
+
启动程序组中的启动程序（ WWPN 或 IQN ）列表，以英文逗号分隔。



以下字段仅适用于 _SAP HANA 配置：

* * 启动程序操作系统类型 *
+
新启动程序组的操作系统类型。

* * FCP 端口集 *
+
启动程序组绑定到的 FCP 端口集。





== 主机访问配置

要配置主机对卷的访问权限，请输入以下信息：

* * 卷导出配置 *
+
选择要在创建期间应用于卷的导出策略。选项包括：

+
** 全部允许
+
此选项意味着，系统会创建一个导出规则，允许对任何客户端进行读写访问。

** 创建自定义策略
+
使用此选项可以指定要接收读写访问的主机 IP 地址列表。



+
[NOTE]
====
您可以稍后使用 System Manager 工作流修改卷导出策略。

====
* * 主机 IP 地址 *
+
此 IP 地址列表以英文逗号分隔。

+
[NOTE]
====
对于基于 NFS 的系统，将使用数据存储库前缀创建一个新的导出策略，并在此策略中创建一条规则以授予对 IP 列表的访问权限。

====




== 应用程序详细信息

添加应用程序后，您可以在 " 应用程序详细信息 " 窗口的 * 概述 * 选项卡中查看配置设置。根据所设置的应用程序类型，还会显示 NFS 或 CIFS 访问和权限等其他详细信息。

* * 类型 *
+
这是所创建的常规应用程序，数据库或虚拟基础架构的类型。

* * SVM*
+
创建应用程序的服务器虚拟机的名称。

* * 大小 *
+
卷的总大小。

* * 可用 *
+
卷中当前可用的空间量。

* * 保护 *
+
配置的数据保护类型。



您可以展开 * 组件 * 和 * 卷 * 窗格以查看有关已用空间， IOPS 和延迟的性能详细信息。

[NOTE]
====
组件窗格中显示的已用大小与命令行界面中显示的已用大小不同。

====