---
permalink: online-help-96-97/reference_disks_window.html 
sidebar: sidebar 
keywords: command, button, disk, window, inventory, detail, online, help 
summary: 您可以使用磁盘窗口查看存储系统中的所有磁盘。 
---
= System Manager 中的磁盘窗口— ONTAP 9.7 及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP System Manager classic中的磁盘窗口(在ONTAP 9.7及更早版本中可用)查看存储系统中的所有磁盘。



== 命令按钮

* * 分配 *
+
将磁盘所有权分配或重新分配给节点。

+
只有在选定磁盘的容器类型为未分配，备用或共享时，才会启用此按钮。

* * 零备件 *
+
擦除所有数据并格式化备用磁盘和阵列 LUN 。

* * 刷新 *
+
更新窗口中的信息。





== 选项卡



== 摘要

显示有关集群中磁盘的详细信息，包括备用磁盘和已分配磁盘的大小。此选项卡还会以图形方式显示有关 HDD 的备用磁盘，聚合和根聚合的信息，以及有关缓存磁盘（ SSD ）的备用磁盘，存储池中的磁盘，聚合， Flash Pool 聚合和根聚合的信息。

对于具有全闪存优化特性的系统，不会显示 HDD 面板。

详细信息面板可提供追加信息有关已分区和未分区备用磁盘（磁盘类型，节点，磁盘大小， RPM ，校验和， 可用磁盘数和备用容量），以表格形式显示。



== 清单

* * 名称 *
+
显示磁盘的名称。

* * 容器类型 *
+
显示磁盘的使用目的。可能的值包括聚合，已断开，外部，标签维护，维护， 共享，备用，未分配，卷，未知， 和不支持。

* * 分区类型 *
+
显示磁盘的分区类型。

* * 节点名称 *
+
显示包含聚合的节点的名称。

+
此字段仅在集群级别可用。

* * 主所有者 *
+
显示将此磁盘分配到的主节点的名称。

* * 当前所有者 *
+
显示当前拥有此磁盘的节点的名称。

* * 根所有者 *
+
显示当前拥有此磁盘根分区的节点的名称。

* * 数据所有者 *
+
显示当前拥有此磁盘的数据分区的节点的名称。

* * 数据 1 所有者 *
+
显示当前拥有磁盘的 data1 分区的节点的名称。

* * 数据 2 所有者 *
+
显示当前拥有磁盘data2分区的节点的名称。

* * 存储池 *
+
显示与磁盘关联的存储池的名称。

* * 类型 *
+
显示磁盘的类型。

* * 固件版本 *
+
显示磁盘的固件版本。

* * 型号 *
+
显示磁盘的型号。

* * 转数 *
+
如果选择选项、则显示磁盘驱动器的有效速度 `raid.mix.hdd.rpm.capacity` 已启用、并在选项出现时显示磁盘驱动器的实际速度 `raid.mix.hdd.rpm.capacity` 已禁用。

+
此字段不适用于 SSD 。

* * 有效大小 *
+
显示磁盘上的可用空间。

* * 物理空间 *
+
显示磁盘的总物理空间。

* * 磁盘架 *
+
显示物理磁盘所在的磁盘架。

+
默认情况下，此字段处于隐藏状态。

* * 托架 *
+
显示物理磁盘架中的托架。

+
默认情况下，此字段处于隐藏状态。

* * 池 *
+
显示将选定磁盘分配到的池的名称。

+
默认情况下，此字段处于隐藏状态。

* * 校验和 *
+
显示校验和的类型。

+
默认情况下，此字段处于隐藏状态。

* * 承运商 ID*
+
指定有关位于指定多磁盘托架中的磁盘的信息。ID 是一个 64 位值。

+
默认情况下，此字段处于隐藏状态。





== 清单详细信息区域

清单选项卡下方的区域显示有关选定磁盘的详细信息，包括聚合或卷的相关信息（如果适用），供应商 ID ，置零状态（以百分比表示），磁盘序列号以及磁盘损坏时的错误详细信息。对于共享磁盘，清单详细信息区域将显示所有聚合的名称，包括根聚合和非根聚合。

* 相关信息 *

xref:task_viewing_disk_information.adoc[查看磁盘信息]
