---
permalink: online-help-96-97/reference_storage_tiers_window.html 
sidebar: sidebar 
keywords: online, help, storage, tier, window, command, button 
summary: 您可以使用存储层窗口查看集群范围的空间详细信息以及添加和查看聚合详细信息。 
---
= System Manager 中的存储层窗口— ONTAP 9.7 及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager 经典版中的存储层窗口（在 ONTAP 9.7 和 earier 中提供）查看集群范围的空间详细信息以及添加和查看聚合详细信息。

内部层面板或性能层面板（如果集群包含全闪存（全 SSD ）聚合）可显示集群范围的空间详细信息，例如所有聚合的总大小之和，集群中聚合使用的空间， 和集群中的可用空间。

" 云层 " 面板可显示集群中已获得许可的云层总数，集群中已使用的已获得许可的空间以及集群中可用的已获得许可的空间。" 云层 " 面板还会显示已使用的未获许可的云容量。

聚合按类型分组，聚合面板将显示有关聚合总空间，已用空间和可用空间的详细信息。如果固态驱动器（ SSD ）或全闪存 FAS 聚合上存在非活动（冷）数据，则还会显示其使用的空间量。您可以选择聚合并执行任何与聚合相关的操作。



== 命令按钮

* * 添加聚合 *
+
用于创建聚合。

* * 操作 *
+
提供了以下选项：

+
** * 将状态更改为 *
+
将选定聚合的状态更改为以下状态之一：

+
*** * 联机 *
+
允许对此聚合中包含的卷进行读写访问。

*** * 脱机 *
+
不允许进行读写访问。

*** * 限制 *
+
允许执行奇偶校验重建等某些操作，但不允许数据访问。



** * 添加容量 *
+
用于向现有聚合添加容量（ HDD 或 SSD ）。

** * 添加缓存 *
+
用于向现有 HDD 聚合或 Flash Pool 聚合添加缓存磁盘（ SSD ）。

+
您不能向启用了 FabricPool 的聚合添加缓存磁盘。

+
如果集群中的节点具有全闪存优化特性，则此选项不可用。

** * 镜像 *
+
用于镜像聚合。

** * 卷移动 *
+
用于移动 FlexVol 卷。







== 详细信息区域

您可以单击聚合名称以查看有关聚合的详细信息。

* * 概述选项卡 *
+
显示有关选定聚合的详细信息，并以图形方式显示聚合的空间分配，聚合的空间节省以及聚合的性能。

* * 磁盘信息选项卡 *
+
显示选定聚合的磁盘布局信息。

* * 卷选项卡 *
+
显示有关聚合上的卷总数，聚合总空间以及提交给聚合的空间的详细信息。

* * 性能选项卡 *
+
显示用于显示聚合性能指标的图形，包括吞吐量和 IOPS 。显示读取，写入和总传输的吞吐量和 IOPS 性能指标数据，并单独记录 SSD 和 HDD 的数据。

+
更改客户端时区或集群时区会影响性能指标图。如果更改了客户端时区或集群时区，则应刷新浏览器以查看更新后的图形。



* 相关信息 *

xref:task_adding_cloud_tier.adoc[正在添加云层]

xref:task_attaching_aggregate_to_cloud_tier.adoc[将聚合附加到云层]

xref:task_deleting_cloud_tier.adoc[删除云层]

xref:task_editing_cloud_tier.adoc[编辑云层]

xref:task_provisioning_storage_through_aggregates.adoc[通过聚合配置存储]

xref:task_deleting_aggregates.adoc[正在删除聚合]

xref:task_editing_aggregates.adoc[编辑聚合]
