---
permalink: online-help-96-97/reference_cluster_update_window.html 
sidebar: sidebar 
keywords: online, help, cluster, update, window, tab, update, command, button, history, tab 
summary: 您可以使用集群更新窗口无中断地自动更新集群，也可以在中断的情况下更新单节点集群。 
---
= 使用 System Manager 的集群更新窗口— ONTAP 9.7 及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 " 集群更新 " 窗口无中断地自动更新集群，也可以使用 ONTAP System Manager classic （在 ONTAP 9.7 及更早版本中提供）无中断地更新单节点集群。



== 选项卡

* * 集群更新 *
+
可用于无中断地执行自动集群更新，也可在中断的情况下更新单节点集群。

* * 更新历史记录 *
+
显示先前集群更新的详细信息。





== 集群更新选项卡

通过 "Cluster Update" 选项卡，您可以无中断地自动更新集群，也可以无中断地更新单节点集群。



== 命令按钮

* * 刷新 *
+
更新窗口中的信息。

* * 选择 *
+
您可以选择要更新的软件映像版本。

+
** 集群版本详细信息：显示当前使用的集群版本以及节点或高可用性（ HA ）对的版本详细信息。
** 可用软件映像：用于选择要更新的现有软件映像。
+
或者，您也可以从 NetApp 支持站点下载软件映像并添加此映像以进行更新。



* * 验证 *
+
您可以根据更新的软件映像版本查看和验证集群。更新前验证将检查集群是否处于可供更新的状态。如果验证完成后出现错误，则会显示一个表，其中显示了各个组件的状态以及所需的错误更正操作。

+
只有在验证成功完成后，才能执行更新。

* * 更新 *
+
您可以将集群中的所有节点或集群中的 HA 对更新为选定版本的软件映像。在更新过程中，您可以选择暂停更新，然后可以取消或恢复更新。

+
如果发生错误，更新将暂停，并显示一条错误消息以及补救步骤。您可以选择在执行补救步骤后恢复更新，也可以选择取消更新。更新成功完成后，您可以查看包含节点名称，正常运行时间，状态和 ONTAP 版本的表。





== 更新历史记录选项卡

显示有关集群更新历史记录的详细信息。



== 更新历史记录列表

* * 映像版本 *
+
指定要将节点更新到的 ONTAP 映像版本。

* * 软件更新已安装在 * 上
+
指定安装更新的磁盘类型。

* * 状态 *
+
指定软件映像更新的状态（更新是成功还是已取消）。

* * 开始时间 *
+
指定更新开始的时间。

* * 完成时间 *
+
指定更新完成的时间。

+
默认情况下，此字段处于隐藏状态。

* * 更新所需时间 *
+
指定完成更新所用的时间。

* * 先前版本 *
+
指定更新前节点的 ONTAP 版本。

* * 更新版本 *
+
指定更新后节点的 ONTAP 版本。


