---
permalink: online-help-96-97/reference_dashboard_window.html 
sidebar: sidebar 
keywords: system, manager, dashboard, window, multiple, panel, online, help 
summary: 信息板窗口包含多个面板，可提供有关系统及其性能的累积概览信息。 
---
= System Manager 的信息板窗口— ONTAP 9.7 及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 经典版（在 ONTAP 9.7 及更早版本中提供）中的信息板窗口包含多个面板，可提供有关系统及其性能的累积概览信息。

您可以使用信息板窗口查看有关以下内容的信息：重要警报和通知，聚合和卷的效率和容量，集群中可用的节点，高可用性（ HA ）对中节点的状态，最活跃的应用程序和对象， 以及集群或节点的性能指标。

* * 警报和通知 *
+
以红色显示所有警报，例如紧急 EMS 事件，脱机节点详细信息，损坏的磁盘详细信息，高风险许可证授权以及脱机网络端口详细信息。以黄色显示所有通知，例如过去 24 小时在集群级别发生的运行状况监控通知，中等风险的许可证授权，未分配磁盘详细信息，迁移的 LIF 数量，失败的卷移动操作， 以及在过去 24 小时内需要管理干预的卷移动操作。

+
" 警报和通知 " 面板最多可显示三个警报和通知，超过三个警报和通知后，将显示 " 查看全部 " 链接。您可以单击查看全部链接以查看有关警报和通知的详细信息。

+
警报和通知面板的刷新间隔为 1 分钟。

* * 集群概述 *
+
显示即将达到容量的聚合和卷，集群或节点的存储效率以及前几个卷的保护详细信息。

+
容量选项卡将按已用空间降序显示即将达到容量的前几个联机聚合。

+
在卷超出已用容量字段中输入有效值后，容量选项卡将提供一个链接，指向已利用容量最高的卷数。它还会显示集群中可用的非活动（冷）数据量。

+
效率选项卡可显示集群或节点的存储效率节省量。您可以查看已用逻辑空间总量，已用物理空间总量以及节省的总空间量。您可以选择集群或特定节点来查看存储效率节省量。对于 System Manager 9.5 ， Snapshot 副本使用的空间已包含在已用总逻辑空间，已用总物理空间和总节省量的值中。但是，从 System Manager 9.6 开始， Snapshot 副本所用空间将包括在已用总逻辑空间，已用总物理空间和总节省量的值中。

+
集群概述面板的刷新间隔为 15 分钟。

+
" 保护 " 选项卡可显示有关未定义保护关系的集群范围卷的信息。仅显示符合以下条件的 FlexVol 卷和 FlexGroup 卷：

+
** 这些卷为 RW 卷且处于联机状态。
** 包含卷的聚合已联机。
** 这些卷具有保护关系，尚未初始化。
您可以导航到卷窗口以查看未定义保护关系的卷。


+
" 保护 " 选项卡还会显示未定义保护关系的卷数量最多的前五个 SVM 。

* * 节点 * ：
+
以图形方式显示集群中可用节点的数量和名称，以及 HA 对中节点的状态。您应将光标置于节点的图形表示上方，以查看 HA 对中节点的状态。

+
您可以使用节点链接查看有关所有节点的详细信息。您也可以单击图形表示形式来查看节点的型号以及节点中可用的聚合，存储池，磁盘架和磁盘的数量。您可以使用管理节点链接来管理节点。您可以使用管理 HA 链接管理 HA 对中的节点。

+
节点面板的刷新间隔为 15 分钟。

* * 应用程序和对象 *
+
您可以使用 " 应用程序和对象 " 面板显示有关集群中的应用程序，客户端和文件的信息。

+
" 应用程序 " 选项卡可显示有关集群中前五个应用程序的信息。您可以根据 IOPS 和延迟（从低到高或从高到低）或容量（从低到高或从高到低）查看前五大应用程序。

+
您应单击特定的条形图以查看有关此应用程序的详细信息。系统将显示总空间，已用空间和可用空间以满足容量要求，并显示 IOPS 详细信息，同时显示延迟详细信息。

+
您可以单击 * 查看详细信息 * 以打开特定应用程序的 " 应用程序 " 窗口。

+
对象选项卡显示有关集群中前五个活动客户端和文件的信息。您可以根据 IOPS 或吞吐量查看排名前五位的活动客户端和文件。

+
[NOTE]
====
此信息仅针对 CIFS 和 NFS 协议显示。

====
+
" 应用程序和对象 " 面板的刷新间隔为 1 分钟。

* * 性能 *
+
显示基于延迟， IOPS 和吞吐量的集群的平均性能指标，读取性能指标和写入性能指标。默认情况下会显示平均性能指标。您可以单击读取或写入分别查看读取性能指标或写入性能指标。您可以查看集群或节点的性能指标。

+
如果无法从 ONTAP 中检索到有关集群性能的信息，则无法查看相应的图形。在这种情况下， System Manager 会显示特定的错误消息。

+
性能面板中图表的刷新间隔为 15 秒。





== 使用信息板监控集群

您可以通过 System Manager 中的信息板监控集群的运行状况和性能。您还可以使用信息板确定硬件问题和存储配置问题。

.步骤
. 单击 * 信息板 * 选项卡以查看运行状况和性能信息板面板。

