---
permalink: online-help-96-97/reference_luns_window.html 
sidebar: sidebar 
keywords: online, help, lun, management, window, command, button, initiator, portset, group, online, help 
summary: 您可以使用 LUN 窗口创建和管理 LUN 以及显示有关 LUN 的信息。您还可以添加，编辑或删除启动程序组和启动程序 ID 。 
---
= ONTAP 9.7 及更早版本中的 LUN 窗口
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager 经典版（在 ONTAP 9.7 及更早版本中提供）中的 LUN 窗口创建和管理 LUN 以及显示有关 LUN 的信息。您还可以添加，编辑或删除启动程序组和启动程序 ID 。



== LUN 管理选项卡

此选项卡可用于创建，克隆，删除，移动或编辑 LUN 的设置。您还可以将 LUN 分配给存储服务质量（ QoS ）策略组。



== 命令按钮

* * 创建 * 。
+
打开创建 LUN 向导，在此可以创建 LUN 。

+
在 AFF 平台上不包含任何现有 LUN 的集群中，将打开创建 FC SAN 优化的 LUN 对话框，在此可以设置一个或多个 FC SAN 优化的 LUN 。

* * 克隆 *
+
打开克隆 LUN 对话框，在此可以克隆选定的 LUN 。

* * 编辑 * 。
+
打开编辑 LUN 对话框，在此可以编辑选定 LUN 的设置。

* * 删除 *
+
删除选定的 LUN 。

* * 状态 *
+
用于将选定 LUN 的状态更改为联机或脱机。

* * 移动 *
+
打开移动 LUN 对话框，在此可以将选定 LUN 移动到新卷或同一 Storage Virtual Machine （ SVM ）中的现有卷或 qtree 。

* * 存储服务质量 *
+
打开服务质量详细信息对话框，在此可以将一个或多个 LUN 分配给新的或现有的策略组。

* * 刷新 *
+
更新窗口中的信息。





== LUN 列表

* * 名称 *
+
显示 LUN 的名称。

* * SVM*
+
显示创建 LUN 的 Storage Virtual Machine （ SVM ）的名称。

* * 容器路径 *
+
显示包含 LUN 的文件系统（卷或 qtree ）的名称。

* * 空间预留 *
+
指定是启用还是禁用空间预留。

* * 可用大小 *
+
显示 LUN 中的可用空间。

* * 总大小 *
+
显示 LUN 中的总空间。

* * 已用 % *
+
显示已用总空间（以百分比表示）。

* * 类型 *
+
指定 LUN 类型。

* * 状态 *
+
指定 LUN 的状态。

* * 策略组 *
+
显示将 LUN 分配到的存储 QoS 策略组的名称。默认情况下，此列处于隐藏状态。

* * 应用程序 *
+
显示分配给 LUN 的应用程序的名称。

* * 问题描述 *
+
显示 LUN 的问题描述。





== 详细信息区域

LUN 列表下方的区域显示与选定 LUN 相关的详细信息。

* * 详细信息选项卡 *
+
显示与 LUN 相关的详细信息，例如 LUN 序列号， LUN 是否为克隆， LUN 问题描述， LUN 分配到的策略组，策略组的最小吞吐量，策略组的最大吞吐量，有关 LUN 移动操作的详细信息， 以及分配给 LUN 的应用程序。您还可以查看有关与选定 LUN 关联的启动程序组和启动程序的详细信息。

* * 性能选项卡 *
+
显示 LUN 的性能指标图，包括数据速率， IOPS 和响应时间。

+
更改客户端时区或集群时区会影响性能指标图。刷新浏览器以查看更新后的图形。





== 启动程序组选项卡

此选项卡可用于创建，删除或编辑启动程序组和启动程序 ID 的设置。



== 命令按钮

* * 创建 * 。
+
打开创建启动程序组对话框，在此可以创建启动程序组以控制主机对特定 LUN 的访问。

* * 编辑 * 。
+
打开编辑启动程序组对话框，在此可以编辑选定启动程序组的设置。

* * 删除 *
+
删除选定启动程序组。

* * 刷新 *
+
更新窗口中的信息。





== 启动程序组列表

* * 名称 *
+
显示启动程序组的名称。

* * 类型 *
+
指定启动程序组支持的协议类型。支持的协议包括 iSCSI ， FC/FCoE 或混合（ iSCSI 和 FC/FCoE ）。

* * 操作系统 * ：
+
指定启动程序组的操作系统。

* * 端口集 *
+
显示与启动程序组关联的端口集。

* * 启动程序计数 *
+
显示添加到启动程序组的启动程序数量。





== 详细信息区域

启动程序组列表下方的区域显示有关添加到选定启动程序组的启动程序以及映射到启动程序组的 LUN 的详细信息。



== 端口集选项卡

此选项卡可用于创建，删除或编辑端口集的设置。



== 命令按钮

* * 创建 * 。
+
打开创建端口集对话框，在此可以创建端口集以限制对 LUN 的访问。

* * 编辑 * 。
+
打开编辑端口集对话框，在此可以选择要与端口集关联的网络接口。

* * 删除 *
+
删除选定的端口集。

* * 刷新 *
+
更新窗口中的信息。





== 端口集列表

* * 端口集名称 *
+
显示端口集的名称。

* * 类型 *
+
指定端口集支持的协议类型。支持的协议包括 iSCSI ， FC/FCoE 或混合（ iSCSI 和 FC/FCoE ）。

* * 接口计数 *
+
显示与端口集关联的网络接口的数量。

* * 启动程序组计数 *
+
显示与端口集关联的启动程序组的数量。





== 详细信息区域

端口集列表下方的区域显示了有关与选定端口集关联的网络接口和启动程序组的详细信息。

* 相关信息 *

xref:task_creating_luns.adoc[正在创建 LUN]

xref:task_deleting_luns.adoc[正在删除 LUN]

xref:task_creating_initiator_groups.adoc[正在创建启动程序组]

xref:task_editing_luns.adoc[编辑 LUN]

xref:task_editing_initiator_groups.adoc[编辑启动程序组]

xref:task_editing_initiators.adoc[编辑启动程序]

xref:task_bringing_luns_online.adoc[使 LUN 联机]

xref:task_taking_luns_offline.adoc[使 LUN 脱机]

xref:task_cloning_luns.adoc[正在克隆 LUN]
