---
permalink: online-help-96-97/reference_trace_file_access_window.html 
sidebar: sidebar 
keywords: system, manager, commnd, button, trace, file, access, window, online, help, cif, entry, list 
summary: '从 System Manager 9.6 开始，如果在使用 CIFS 或 NFS 协议访问 SVM 上的文件和共享时遇到问题，您可以使用 " 跟踪文件访问 " 窗口来诊断问题。' 
---
= System Manager 中的跟踪文件访问窗口
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP System Manager 9.6 开始，如果在使用 CIFS 或 NFS 协议访问 SVM 上的文件和共享时遇到问题，您可以使用 " 跟踪文件访问 " 窗口来诊断问题。



== 命令按钮

* * 继续 *
+
启动在选定 SVM 上设置和启动文件访问跟踪的过程。

* * 协议 *
+
用于选择用于访问选定 SVM 上的文件和共享的协议，可以是 CIFS 或 NFS 。

* * 高级选项图标 *
+
用于指定其他详细信息以缩小跟踪范围。

* * 在跟踪结果中显示 *
+
用于在 " 高级选项 " 对话框中指定是希望跟踪结果仅显示被拒绝的文件访问请求，还是显示所有文件访问请求—成功的请求和被拒绝的请求。

* * 开始跟踪 *
+
用于启动跟踪。结果显示了未来 60 分钟内提交的文件访问请求的访问问题。

* * 停止跟踪 *
+
用于停止跟踪。

* * 查看权限 *
+
用于显示权限。使用 CIFS 协议时，您可以显示有效文件和共享权限。使用 NFS 协议时，您可以显示有效文件权限。

* * 复制到剪贴板 *
+
用于将结果表复制到剪贴板。

* * 导出跟踪结果 *
+
用于将跟踪结果导出为逗号分隔值（ .csv ）格式的文件。





== 输入字段

* * 用户名 *
+
您可以输入收到要跟踪的文件访问请求错误的用户的名称。

* * 搜索跟踪结果 *
+
输入要在搜索结果中查找的特定信息，然后单击 * 输入 * 。

* * 客户端 IP 地址 *
+
在高级选项对话框中，您可以指定客户端的 IP 地址作为附加详细信息来缩小跟踪范围。

* * 文件 *
+
在高级选项对话框中，您可以指定要访问的文件或文件路径作为附加详细信息来缩小跟踪范围。



.CIFS协议跟踪结果列表
指定 CIFS 协议时，结果列表将根据您指定的参数显示以下跟踪数据。数据按时间倒序显示。如果停止跟踪，则结果将保留在列表中，直到您启动另一个跟踪为止。

* 共享：系统尝试访问的共享的名称，无论是否成功。
* path ：系统尝试访问的文件的文件路径，无论是否成功。
* 客户端 IP 地址：发起访问请求的客户端的 IP 地址。
* 原因：尝试访问文件或共享的成功或失败的原因。
+
[NOTE]
====
当跟踪结果显示一条消息，指出未授予 " 同步 " ， " 读取控制 " ， " 读取属性 " ， " 执行 " ， " 读取 EA" 访问权限时， 消息为 "write" 或 "read" ，表示尚未为列出的权限集授予所需的访问权限。要查看实际权限状态，您需要使用提供的链接查看权限。

====


.NFS协议跟踪的结果列表
指定NFS协议时、结果列表将根据您指定的参数显示以下跟踪数据。数据按时间倒序显示。如果停止跟踪，则结果将保留在列表中，直到您启动另一个跟踪为止。

* path ：系统尝试访问的文件的文件路径，无论是否成功。
* 客户端 IP 地址：发起访问请求的客户端的 IP 地址。
* 原因：尝试访问文件或共享的成功或失败的原因。
+
[NOTE]
====
当跟踪结果显示一条消息，指出未授予 " 同步 " ， " 读取控制 " ， " 读取属性 " ， " 执行 " ， " 读取 EA" 访问权限时， 消息为 "write" 或 "read" ，表示尚未为列出的权限集授予所需的访问权限。要查看实际权限状态，您需要使用提供的链接查看权限。

====


* 相关信息 *

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB/CIFS 管理"]

xref:../nas-multiprotocol-config/index.html[SMB/CIFS 和 NFS 多协议配置]
