---
permalink: online-help-96-97/reference_protection_window.html 
sidebar: sidebar 
keywords: command, buttons, protection, window, relationship, vault, mirror, online, help, ls 
summary: '您可以使用 " 保护 " 窗口创建和管理镜像关系，存储关系以及镜像和存储关系，并显示有关这些关系的详细信息。保护窗口不会显示负载共享（ LS ）关系和过渡数据保护（ TDP ）关系。' 
---
= 使用 System Manager — ONTAP 9.7 及更早版本的保护窗口
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将保护窗口与 ONTAP System Manager classic （在 ONTAP 9.7 及更早版本中提供）结合使用，以创建和管理镜像关系，存储关系以及镜像和存储关系，并显示有关这些关系的详细信息。保护窗口不会显示负载共享（ LS ）关系和过渡数据保护（ TDP ）关系。



== 命令按钮

* * 创建 * 。
+
打开创建保护关系对话框，在此可以从目标卷创建镜像关系，存储关系或镜像和存储关系。

+
System Manager 不会在创建保护关系对话框中显示为灾难恢复（ DR ）配置的任何 Storage Virtual Machine （ SVM ）。

* * 编辑 * 。
+
打开编辑保护关系对话框，在此可以编辑关系的计划和策略。

+
对于存储关系，镜像和存储关系或版本灵活的镜像关系，您可以通过修改策略类型来修改关系类型。

* * 删除 *
+
打开删除保护关系对话框，在此可以删除关系。

* * 操作 *
+
显示可对保护关系执行的操作。

* * 刷新 *
+
更新窗口中的信息。





== 保护关系列表

* * 源 Storage Virtual Machine*
+
显示某个关系中镜像或存储数据的卷所在的 SVM 。

* * 源卷 *
+
显示在关系中从中镜像或存储数据的卷。

* * 目标卷 *
+
显示在关系中将数据镜像或存储到的卷。

* * 运行状况良好 *
+
显示关系是否运行正常。

* * 对象类型 *
+
显示关系的对象类型，例如卷， FlexGroup 或 SVM 。

* * 关系状态 *
+
显示关系的状态，例如已执行 Snapmirrored ，未初始化或已断开。

* * 传输状态 *
+
显示关系的状态。

* * 关系类型 *
+
显示关系的类型，例如镜像，存储或镜像和存储。

* * 滞后时间 *
+
滞后时间是指当前时间与已成功传输到目标系统的最后一个 Snapshot 副本的时间戳之间的差值。除非源系统和目标系统上的时钟未同步，否则滞后时间始终至少与上次成功传输的持续时间相同。时区差异会自动计算为滞后时间。

* * 策略名称 *
+
显示分配给关系的策略的名称。

* * 策略类型 *
+
显示分配给关系的策略类型。策略类型可以是 StrictSync ， Sync ，异步镜像，异步存储或异步镜像存储。





== 详细信息区域

* * 详细信息选项卡 *
+
显示有关选定关系的常规信息，例如源集群和目标集群，数据传输速率，关系状态，有关网络压缩率的详细信息，数据传输状态，当前数据传输的类型，上次数据传输的类型，最新 Snapshot 副本， 和最新 Snapshot 副本的时间戳。

* * 策略详细信息选项卡 *
+
显示有关分配给选定保护关系的策略的详细信息。此选项卡还会显示与指定标签匹配的源卷中的 SnapMirror 标签和 Snapshot 副本计划。

* * Snapshot 副本选项卡 *
+
显示选定保护关系中具有 SnapMirror 标签属性的 Snapshot 副本计数以及最新 Snapshot 副本的时间戳。


