---
permalink: online-help-96-97/reference_svm_dashboard_window.html 
sidebar: sidebar 
keywords: svm, dashboard, detail, online, help 
summary: 信息板可提供有关 Storage Virtual Machine （ SVM ）及其性能的累积概览信息。您可以使用信息板窗口查看与 SVM 相关的重要信息，例如配置的协议，即将达到容量的卷以及性能。 
---
= System Manager 中的 SVM 信息板窗口— ONTAP 9.7 及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager classic 中的信息板窗口（在 ONTAP 9.7 及更早版本中提供）可提供有关 Storage Virtual Machine （ SVM ）及其性能的累积概览信息。您可以使用信息板窗口查看与 SVM 相关的重要信息，例如配置的协议，即将达到容量的卷以及性能。



== SVM 详细信息

此窗口可通过各种面板显示有关 SVM 的详细信息，例如 " 协议状态 " 面板， " 即将达到容量的卷 " 面板， " 应用程序 " 面板和 " 性能 " 面板。

* * 协议状态 *
+
简要介绍为 SVM 配置的协议。您可以单击协议名称以查看配置。

+
如果未配置协议或 SVM 没有协议许可证，您可以单击协议名称来配置协议或添加协议许可证。

* * 即将达到容量的卷 *
+
显示有关容量利用率接近 80% 或以上且需要立即引起关注或采取更正操作的卷的信息。

* * 应用程序 *
+
显示有关 SVM 的前五个应用程序的信息。您可以根据 IOPS （从低到高或从高到低）或容量（从低到高或从高到低）查看排名前五位的应用程序。您必须单击特定的条形图才能查看有关此应用程序的详细信息。对于容量，将显示总空间，已用空间和可用空间；对于 IOPS ，将显示 IOPS 详细信息。对于 L2/L3 应用程序，还会显示延迟指标。

+
[NOTE]
====
应用程序窗口中显示的已用大小与命令行界面中的已用大小不同。

====
+
您可以单击 * 查看详细信息 * 以打开特定应用程序的 " 应用程序 " 窗口。您可以单击 * 查看所有应用程序 * 来查看 SVM 的所有应用程序。

+
应用程序面板的刷新间隔为 1 分钟。

* * SVM 性能 *
+
显示 SVM 中协议的性能指标，包括延迟和 IOPS 。

+
如果无法从 ONTAP 中检索到有关 SVM 性能的信息，则无法查看相应的图形。在这种情况下， System Manager 会显示特定的错误消息。

+
SVM 性能面板的刷新间隔为 15 秒。


