---
permalink: online-help-96-97/task_editing_mirror_relationships.html 
sidebar: sidebar 
keywords: system, manager, edit, mirror, relationships, online, help 
summary: 您可以使用 System Manager 通过选择集群中的现有策略或计划或者创建策略或计划来编辑镜像关系。 
---
= 使用 System Manager 管理镜像关系— ONTAP 9.7 及更早版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）管理镜像关系。您可以更新、创建、暂停、初始化、重新建立、 除了恢复已暂停的镜像关系之外、还可以删除和编辑镜像关系。



== 删除关系

您可以使用 System Manager 删除镜像关系并永久结束源卷与目标卷之间的镜像关系。删除镜像关系后，源卷上的基本 Snapshot 副本将被删除。

.关于此任务
删除镜像关系之前，最好先断开镜像关系。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要删除的镜像关系，然后单击 * 删除 * 。
. 选中确认复选框以删除镜像关系并释放基本 Snapshot 副本，然后单击 * 删除 * 。


.结果
此时将删除此关系，并删除源卷上的基本 Snapshot 副本。



== 重新同步关系

您可以使用 System Manager 重新建立先前已断开的镜像关系。您可以执行重新同步操作，以便从禁用源卷的灾难中恢复。

.开始之前
源集群和目标集群以及源 SVM 和目标 SVM 必须处于对等关系。

.关于此任务
* 执行重新同步操作时，镜像目标上的内容将被源卷上的内容覆盖。
+
[NOTE]
====
** 对于 SnapLock Compliance 卷，活动文件系统中与通用 Snapshot 副本相关的所有数据更改都会保留在锁定的 Snapshot 副本中，直到为当前卷设置的到期时间为止。
+
如果卷到期时间为过去或尚未设置，则 Snapshot 副本和通用 Snapshot 副本将锁定 30 天。通用 Snapshot 副本与最新锁定的 Snapshot 副本之间的所有中间 Snapshot 副本都会被删除。

** 对于 SnapLock Compliance 卷以外的所有卷，重新同步操作可能发生原因会丢失在创建基本 Snapshot 副本后写入目标卷的较新数据。


====
* 如果保护窗口中的上次传输错误字段建议执行重新同步操作，则必须先中断此关系，然后再执行重新同步操作。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要重新同步的镜像关系。
. 单击 * 操作 * > * 重新同步 * 。
. 选中确认复选框，然后单击 * 重新同步 * 。




== 恢复暂停的关系

您可以使用 System Manager 恢复已暂停的镜像关系。恢复此关系后，系统将恢复向镜像目标的正常数据传输，并重新启动所有镜像活动。

.关于此任务
如果您已从命令行界面（ CLI ）暂停已断开的镜像关系，则无法从 System Manager 恢复此关系。您必须使用命令行界面恢复此关系。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要恢复的镜像关系。
. 单击 * 操作 * > * 恢复 * 。
. 选中确认复选框，然后单击 * 恢复 * 。


.结果
此时将恢复选定镜像关系中到镜像目标的数据传输。



== 更新关系

您可以使用 System Manager 对目标启动计划外镜像更新。您可能需要执行手动更新，以防止因即将发生断电，计划内维护或数据迁移而导致数据丢失。

.开始之前
镜像关系必须处于 Snapmirrored 状态。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要更新数据的镜像关系，然后单击 * 操作 * > * 更新 * 。
. 选择以下选项之一：
+
** 选择 * 按需 * 可从源卷和目标卷之间的最新通用 Snapshot 副本执行增量传输。
** 选择 * 选择 Snapshot 副本 * 并指定要传输的 Snapshot 副本。


. *可选：*选择*将传输带宽限制为*可限制用于传输的网络带宽并指定最大传输速度。
. 单击 * 更新 * 。
. 在 * 详细信息 * 选项卡中验证传输状态。




== 暂停关系

您可以使用 System Manager 暂停镜像目标以使其保持稳定，然后再创建 Snapshot 副本。暂停操作可以完成镜像关系的活动镜像传输，并禁用以后的传输。

.关于此任务
您只能暂停处于 Snapmirrored 状态的镜像关系。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要暂停的镜像关系。
. 单击 * 操作 * > * 暂停 * 。
. 选中确认复选框，然后单击 * 暂停 * 。




== 初始化关系

启动镜像关系时，必须初始化该关系。初始化关系包括从源卷到目标卷的完整基线数据传输。如果在创建镜像关系时尚未初始化此关系，则可以使用 System Manager 对其进行初始化。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要初始化的镜像关系。
. 单击 * 操作 * > * 初始化 * 。
. 选中确认复选框，然后单击 * 初始化 * 。
. 在 * 保护 * 窗口中验证镜像关系的状态。


.结果
此时将创建一个 Snapshot 副本并将其传输到目标。此 Snapshot 副本用作后续增量 Snapshot 副本的基线。



== 编辑关系

您可以使用 System Manager 通过选择集群中的现有策略或计划或者创建策略或计划来编辑镜像关系。

.关于此任务
* 您不能编辑在 Data ONTAP 8.2.1 中的卷与 ONTAP 8.3 或更高版本中的卷之间创建的镜像关系。
* 您不能编辑现有策略或计划的参数。
* 您可以通过修改策略类型来修改版本灵活的镜像关系，存储关系或镜像和存储关系的关系类型。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要修改策略或计划的镜像关系，然后单击 * 编辑 * 。
. 在 * 编辑关系 * 对话框中，选择现有策略或创建策略：
+
|===
| 如果您要 ... | 执行以下操作 ... 


 a| 
选择一个现有策略。
 a| 
单击 * 浏览 * ，然后选择现有策略。



 a| 
创建策略
 a| 
.. 单击 * 创建策略 * 。
.. 指定策略的名称。
.. 设置计划传输的优先级。
+
low 表示传输的优先级最低，通常计划在正常优先级传输之后进行。默认情况下，优先级设置为正常。

.. 选中 * 传输所有源 Snapshot 副本 * 复选框，以便在镜像策略中包含 "`all_source_snapshots` " 规则，从而可以从源卷备份所有 Snapshot 副本。
.. 选中 * 启用网络压缩 * 复选框以压缩要传输的数据。
.. 单击 * 创建 * 。


|===
. 指定关系的计划：
+
|===
| 条件 | 执行以下操作 ... 


 a| 
要分配现有计划
 a| 
从计划列表中，选择一个现有计划。



 a| 
要创建计划
 a| 
.. 单击 * 创建计划 * 。
.. 指定计划的名称。
.. 选择 * 基本 * 或 * 高级 * 。
+
*** 基本仅指定一周中的某一天，时间和传输间隔。
*** 高级可创建 cron 模式的计划。


.. 单击 * 创建 * 。




 a| 
您不想分配计划
 a| 
选择 * 无 * 。

|===
. 单击 * 确定 * 以保存更改。




== 从目标SVM创建镜像关系

您可以使用System Manager从目标Storage Virtual Machine (SVM)创建镜像关系、并为此镜像关系分配策略和计划。如果源卷上的数据损坏或丢失，镜像副本可以快速提供数据。

.开始之前
* 源集群必须运行 ONTAP 8.2.2 或更高版本。
* 必须在源集群和目标集群上启用 SnapMirror 许可证。
+
[NOTE]
====
对于某些平台，如果目标集群启用了 SnapMirror 许可证和数据保护优化（ DPO ）许可证，则源集群不必启用 SnapMirror 许可证。

====
* 在镜像卷时，如果选择 SnapLock 卷作为源卷，则必须在目标集群上安装 SnapMirror 许可证和 SnapLock 许可证。
* 源集群和目标集群之间的对等关系必须运行正常。
* 目标 SVM 必须具有可用空间。
* 必须存在读 / 写（ rw ）类型的源卷。
* FlexVol 卷必须处于联机状态，并且类型必须为读 / 写。
* SnapLock 聚合类型必须相同。
* 如果要从运行 ONTAP 9.2 或更早版本的集群连接到启用了安全断言标记语言（ SAML ）身份验证的远程集群，则必须在远程集群上启用基于密码的身份验证。


.关于此任务
* System Manager 不支持级联关系。
+
例如，关系中的目标卷不能是另一关系中的源卷。

* 您不能在 MetroCluster 配置中 sync-source SVM 和 sync-destination SVM 之间创建镜像关系。
* 您可以在 MetroCluster 配置中 sync-source SVM 之间创建镜像关系。
* 您可以创建从 sync-source SVM 上的卷到提供数据的 SVM 上的卷的镜像关系。
* 您可以创建从提供数据的 SVM 上的卷到 sync-source SVM 上的数据保护（ DP ）卷的镜像关系。
* 您只能在相同类型的 SnapLock 卷之间创建镜像关系。
+
例如，如果源卷是 SnapLock Enterprise 卷，则目标卷也必须是 SnapLock Enterprise 卷。您必须确保目标 SVM 具有相同 SnapLock 类型的聚合。

* 为镜像关系创建的目标卷不会进行精简配置。
* 一次选择最多可以保护 25 个卷。
* 如果目标集群运行的 ONTAP 版本早于源集群运行的 ONTAP 版本，则无法在 SnapLock 卷之间创建镜像关系。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 在 * 卷关系 * 窗口中，单击 * 创建 * 。
. 在 * 浏览 SVM* 对话框中，为目标卷选择一个 SVM 。
. 在 * 创建保护关系 * 对话框中，从 * 关系类型 * 下拉列表中选择 * 镜像 * 。
. 指定集群， SVM 和源卷。
+
如果指定集群运行的 ONTAP 软件版本早于 ONTAP 9.3 ，则仅会列出对等 SVM 。如果指定集群运行的是 ONTAP 9.3 或更高版本，则会列出对等 SVM 和允许的 SVM 。

. 对于 FlexVol 卷，请指定卷名称后缀。
+
卷名称后缀会附加到源卷名称中，以生成目标卷名称。

. 单击 * 浏览 * ，然后更改镜像策略。
. 从现有计划列表中为此关系选择一个计划。
. 选择 * 初始化关系 * 以初始化镜像关系。
. 启用启用启用了 FabricPool 的聚合，然后选择适当的分层策略。
. 单击 * 创建 * 。


.结果
如果选择创建目标卷，则会创建类型为 _dp_ 的目标卷，并将语言属性设置为与源卷的语言属性匹配。

在源卷和目标卷之间创建镜像关系。如果选择初始化此关系，则基本 Snapshot 副本将传输到目标卷。



== 反向重新同步镜像关系

您可以使用 System Manager 重新建立先前已断开的镜像关系。在反向重新同步操作中，您可以反转源卷和目标卷的功能。

.开始之前
源卷必须处于联机状态。

.关于此任务
* 在修复或替换源卷，更新源卷以及重新建立系统的初始配置时，您可以使用目标卷提供数据。
* 执行反向重新同步时，镜像源上的内容将被目标卷上的内容覆盖。
+
[NOTE]
====
** 对于 SnapLock Compliance 卷，活动文件系统中与通用 Snapshot 副本相关的所有数据更改都会保留在锁定的 Snapshot 副本中，直到为当前卷设置的到期时间为止。
+
如果卷到期时间为过去或尚未设置，则 Snapshot 副本和通用 Snapshot 副本将锁定 30 天。通用 Snapshot 副本与最新锁定的 Snapshot 副本之间的所有中间 Snapshot 副本都会被删除。

** 对于 SnapLock Compliance 卷以外的所有卷，重新同步操作可能发生原因会丢失在创建基本 Snapshot 副本后写入源卷的较新数据。


====
* 执行反向重新同步时，此关系的镜像策略将设置为 DPDefault ，而镜像计划将设置为无。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要反转的镜像关系。
. 单击 * 操作 * > * 反向重新同步 * 。
. 选中确认复选框，然后单击 * 反向重新同步 * 。


* 相关信息 *

xref:reference_protection_window.adoc[保护窗口]
