---
permalink: online-help-96-97/task_creating_fc_san_optimized_luns.html 
sidebar: sidebar 
keywords: create, fc, san, optimized, lun, system, manager, online, help 
summary: 在 AFF 平台上首次设置集群期间，您可以使用 System Manager 创建一个或多个 FC SAN 优化的 LUN 。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本创建 FC SAN 优化的 LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 AFF 平台上首次设置集群期间，您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）创建一个或多个 FC SAN 优化的 LUN 。

.开始之前
* 您必须确保仅创建了一个名为 AFF_SAN_DEFAULT_SVM 的 Storage Virtual Machine （ SVM ），并且此 SVM 不包含任何 LUN 。
* 您必须已验证硬件设置是否已成功完成。
+
https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 文档中心"]



.关于此任务
* 只有在首次设置具有两个或更多节点的集群时，才能使用此方法。
+
System Manager 仅使用前两个节点创建 LUN 。

* 每个 LUN 都在一个单独的卷上创建。
* 卷采用精简配置。
* 已对创建的 LUN 禁用空间预留。
* 大多数集群配置都已在出厂时完成，并已进行优化，可实现最佳存储效率和性能。
+
您不能修改这些配置。



.步骤
. 使用集群管理员凭据登录到 System Manager 。
+
使用此方法创建 LUN 后，您将无法再次使用此方法。

+
如果在未创建 LUN 的情况下关闭对话框，则必须导航到 LUN 选项卡并单击 * 创建 * 以再次访问此对话框。

. 在 * 创建 LUN* 对话框的 * LUN 详细信息 * 区域中，指定应用程序类型：
+
|===
| 应用程序类型 | 那么 ... 


 a| 
Oracle
 a| 
.. 指定数据库名称和大小。
.. 如果已部署 Oracle Real Application Clusters （ RAC ），请选中 * Oracle RAC* 复选框。
+
仅支持两个 RAC 节点。您必须确保 Oracle RAC 至少向启动程序组添加了两个启动程序。





 a| 
SQL/
 a| 
指定数据库的数量和每个数据库的大小。



 a| 
其他
 a| 
.. 指定每个 LUN 的名称和大小。
.. 如果要创建更多 LUN ，请单击 * 添加更多 LUN* ，然后指定每个 LUN 的名称和大小。


|===
+
数据，日志，二进制文件和临时 LUN 会根据选定的应用程序类型创建。

. 在 * 映射到这些启动程序 * 区域中，执行以下步骤：
+
.. 指定启动程序组名称和操作系统类型。
.. 通过从下拉列表中选择主机启动程序 WWPN 或在文本框中键入启动程序来添加主机启动程序 WWPN 。
.. 添加启动程序的别名。


+
仅创建一个启动程序组。

. 单击 * 创建 * 。
+
此时将显示一个摘要表，其中包含已创建的 LUN 。

. 单击 * 关闭 * 。


* 相关信息 *

https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 文档中心"]
