---
permalink: online-help-96-97/task_editing_volume_properties.html 
sidebar: sidebar 
keywords: edit, volume, properties, online, help, deduplication, system, manager 
summary: 您可以使用 System Manager 修改卷属性，例如卷名称，安全模式，预留百分比和空间保证。您可以修改存储效率设置（重复数据删除计划，重复数据删除策略和数据压缩）和空间回收设置。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本编辑卷属性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP System Manager classic (适用于ONTAP 9.7及更早版本)修改卷属性、例如卷名称、安全模式、预留百分比和空间保证。您可以修改存储效率设置（重复数据删除计划，重复数据删除策略和数据压缩）和空间回收设置。

.开始之前
要启用卷加密，必须已使用 System Manager 安装卷加密许可证，并且已使用命令行界面（ CLI ）启用 "`key-manager setup` " 。启用 "`key-manager setup` " 后，必须刷新 Web 浏览器。

.关于此任务
* 您可以将预留百分比设置为 0% 或 100% 。
* 32 位卷不支持数据压缩。
* 对于 Data ONTAP 8.3.1 集群，您可以为 Cloud Volumes ONTAP for AWS （ AWS ）启用实时压缩和后台压缩。
+
Data ONTAP Edge 不支持数据压缩。

* 您不能重命名 SnapLock Compliance 卷。


.步骤
. 单击 * 存储 * > * 卷 * 。
. 从 * SVM* 字段的下拉菜单中，选择要编辑的卷所在的 Storage Virtual Machine （ SVM ）。
. 选择要修改的卷，然后单击 * 编辑 * 。
+
此时将显示编辑卷对话框。

. 在 * 常规 * 选项卡中，根据需要修改以下属性：
+
** 更改卷名称
** 启用卷加密
+
只有在已启用卷加密许可证且相应平台支持加密的情况下，此选项才可用。您可以从命令行界面执行 key-manager 设置。

** 更改卷的安全模式
** 启用或禁用精简配置


. 单击 * 存储效率 * 选项卡，并通过配置以下属性来启用存储效率：
+
** 重复数据删除
** 数据压缩
您不能为具有全闪存优化特性的聚合中的卷启用后台数据压缩。您只能为这些卷启用实时压缩。


+
您只能对具有全闪存优化特性的聚合中的卷或 Flash Pool 聚合中的卷启用实时重复数据删除。

. 对于 SnapLock 卷，单击 * SnapLock * 选项卡，然后执行以下步骤：
+
.. 指定自动提交期限。
+
自动提交期限用于确定卷中的文件在提交到 WORM 状态之前必须保持多长时间不变。

.. 指定最短保留期限和最长保留期限。
+
值必须介于 1 天到 70 年之间或无限范围内。

.. 选择默认保留期限。
+
默认保留期限必须在指定的最短保留期限和最长保留期限内。



. 单击 * 高级 * 选项卡，并启用以下属性：
+
** 如果希望卷在已用空间超过增长阈值时自动增长，请选择 * 增长 * 。
** 如果要根据已用空间量增大或缩小卷大小，请选择 * 增长或缩减 * 。
+
... 指定卷可增长到的最大大小。


** 通过选择以下选项之一启用旧 Snapshot 副本的自动删除：
+
*** 试用
+
删除未被任何其他子系统锁定的 Snapshot 副本。

*** 销毁
+
删除由数据备份功能锁定的 Snapshot 副本。

*** 中断
+
删除可能会中断数据传输的 Snapshot 副本。



** 选择要分配给卷的缓存策略。
+
此选项仅适用于 Flash Pool 聚合中的 FlexVol 卷。

** 选择卷中缓存数据的保留优先级。
+
此选项仅适用于 Flash Pool 聚合中的 FlexVol 卷。

** 指定要为卷设置的预留百分比。
** 更新读取文件的访问时间。
+
对于 SnapLock 卷，此选项处于禁用状态。



. 单击 * 保存并关闭 * 。


* 相关信息 *

xref:reference_volumes_window.adoc[卷窗口]

xref:task_setting_up_cifs.adoc[正在设置CIFS]
