---
permalink: online-help-96-97/task_editing_vault_relationships.html 
sidebar: sidebar 
keywords: edit, vault, relationships, system, manager, online, help, cluster, schedule 
summary: 您可以使用 System Manager 通过选择集群中的现有策略或计划或者创建新的策略或计划来编辑存储关系。但是，您不能编辑现有策略或计划的参数。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本管理存储关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
除了从目标 SVM 创建存储关系之外，您还可以使用 ONTAP System Manager classic （在 ONTAP 9.7 及更早版本中提供）来更新，恢复，暂停，初始化和删除存储关系。



== 编辑关系

您可以使用 System Manager 通过选择集群中的现有策略或计划或者创建新的策略或计划来编辑存储关系。但是，您不能编辑现有策略或计划的参数。

.开始之前
源集群和目标集群之间的对等关系必须运行正常。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要修改策略或计划的存储关系，然后单击 * 编辑 * 。
. 在 * 编辑关系 * 对话框中，选择相应的操作：
+
|===
| 如果您要 ... | 执行以下操作 ... 


 a| 
选择一个现有策略。
 a| 
单击 * 浏览 * ，然后选择现有策略。    您可以选择一个与附加到源卷的 Snapshot 策略具有最大匹配标签数的策略。



 a| 
创建新策略。
 a| 
.. 单击 * 创建策略 * 。
.. 指定策略的名称。
.. 设置计划传输的优先级。
+
low 表示传输的优先级最低，通常计划在正常优先级传输之后进行。默认情况下，优先级设置为正常。

.. 选中 * 启用网络压缩 * 复选框以压缩要传输的数据。
.. 为存储策略指定 SnapMirror 标签和目标保留计数。
+
您必须确保在源卷上创建具有相同标签的 Snapshot 副本，以使新的 SnapMirror 标签生效。

.. 单击 * 创建 * 。


|===
. 指定关系的计划：
+
|===
| 条件 | 执行以下操作 ... 


 a| 
要分配现有计划
 a| 
从列表中选择一个现有计划。



 a| 
要创建新计划
 a| 
.. 单击 * 创建计划 * 。
.. 指定计划的名称。
.. 选择以下选项之一：
+
*** * 基本 *
+
您可以选择此选项以仅指定一周中的某一天，时间和传输间隔。

*** * 高级 *
+
您可以选择此选项以指定 cron 模式的计划。



.. 单击 * 创建 * 。




 a| 
您不想分配计划
 a| 
选择 * 无 * 。

|===
. 单击 * 确定 * 。


* 相关信息 *

xref:reference_protection_window.adoc[保护窗口]



== 初始化关系

如果您在创建存储关系时尚未初始化存储关系，则可以使用 System Manager 初始化该关系。启动从源 FlexVol 卷到目标 FlexVol 卷的基线数据传输。

.开始之前
源集群和目标集群之间的对等关系必须运行正常。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要初始化的关系，然后单击 * 操作 * > * 初始化 * 。
. 在 * 初始化 * 窗口中，单击 * 初始化 * 。


.结果
此时将创建一个 Snapshot 副本并将其传输到目标。

此 Snapshot 副本用作后续增量 Snapshot 副本的基线。

* 相关信息 *

xref:reference_protection_window.adoc[保护窗口]



== 从目标 SVM 创建关系

您可以使用 System Manager 从目标 Storage Virtual Machine （ SVM ）创建存储关系，并分配用于创建备份存储的存储策略。如果系统上发生数据丢失或损坏，可以从备份存储目标还原备份的数据。

.开始之前
* 源集群必须运行 ONTAP 8.2.2 或更高版本。
* 源集群和目标集群都必须启用 SnapVault 许可证或 SnapMirror 许可证。
+
[NOTE]
====
对于某些平台，如果目标集群已启用 SnapVault 许可证或 SnapMirror 许可证且已启用 DPO 许可证，则源集群不必启用 SnapVault 许可证或 SnapMirror 许可证。

====
* 源集群和目标集群之间的对等关系必须运行正常。
* 目标 SVM 必须具有可用空间。
* 源聚合和目标聚合必须是 64 位聚合。
* 必须存在读 / 写（ rw ）类型的源卷。
* 必须存在存储（ XDP ）策略。
+
如果存储策略不存在，则必须创建存储策略或接受自动分配的默认存储策略（ XDPDefault ）。

* FlexVol 卷必须处于联机状态且为读 / 写。
* SnapLock 聚合类型必须相同。
* 如果要从运行 ONTAP 9.2 或更早版本的集群连接到启用了 SAML 身份验证的远程集群，则必须在远程集群上启用基于密码的身份验证。


.关于此任务
* System Manager 不支持级联关系。
+
例如，关系中的目标卷不能是另一关系中的源卷。

* 您不能在 MetroCluster 配置中 sync-source SVM 和 sync-destination SVM 之间创建存储关系。
* 您可以在 MetroCluster 配置中 sync-source SVM 之间创建存储关系。
* 您可以创建从 sync-source SVM 上的卷到提供数据的 SVM 上的卷的存储关系。
* 您可以创建从提供数据的 SVM 上的卷到 sync-source SVM 上的数据保护（ DP ）卷的存储关系。
* 您只能在非 SnapLock （主）卷和 SnapLock 目标（二级）卷之间创建存储关系。
* 一次选择最多可以保护 25 个卷。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 在 * 关系 * 窗口中，单击 * 创建 * 。
. 在 * 浏览 SVM* 对话框中，为目标卷选择一个 SVM 。
. 在 * 创建保护关系 * 对话框中，从 * 关系类型 * 下拉列表中选择 * 存储 * 。
. 指定集群， SVM 和源卷。
+
如果指定集群运行的 ONTAP 软件版本早于 ONTAP 9.3 ，则仅会列出对等 SVM 。如果指定集群运行的是 ONTAP 9.3 或更高版本，则会列出对等 SVM 和允许的 SVM 。

. 输入卷名称后缀。
+
卷名称后缀会附加到源卷名称中，以生成目标卷名称。

. 如果要创建 SnapLock 卷，请指定默认保留期限。
+
可以将默认保留期限设置为介于 1 天到 70 年之间的任何值，也可以设置为 " 无限 " 。

. *可选：*单击*浏览*、然后更改存储策略。
. 从现有计划列表中为此关系选择一个计划。
. *可选：*选择*初始化关系*以初始化存储关系。
. 启用 SnapLock 聚合，然后选择 SnapLock 合规性聚合或 SnapLock 企业聚合。
. 启用启用启用了 FabricPool 的聚合，然后选择适当的分层策略。
. 单击 * 验证 * 以验证选定卷是否具有匹配标签。
. 单击 * 创建 * 。


.结果
如果选择创建目标卷，则会使用以下默认设置创建类型为 _dp_ 的卷：

* 已启用自动增长。
* 重复数据删除会根据用户首选项或源卷的重复数据删除设置启用或禁用。
* 已禁用数据压缩。
* 语言属性设置为与源卷的语言属性匹配。


此时将在目标卷和源卷之间创建存储关系。如果选择初始化此关系，则基本 Snapshot 副本将传输到目标卷。



== 更新关系

您可以使用 System Manager 手动启动计划外增量更新。您可能需要手动更新，以防止因即将发生断电，计划内维护或数据迁移而导致数据丢失。

.开始之前
必须初始化存储关系。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要更新数据的关系，然后单击 * 操作 * > * 更新 * 。
. 选择以下选项之一：
+
** 选择 * 按策略 * 可从源卷和目标卷之间的最新通用 Snapshot 副本执行增量传输。
** 选择 * 选择 Snapshot 副本 * 并指定要传输的 Snapshot 副本。


. *可选：*选择*将传输带宽限制为*可限制用于传输的网络带宽并指定最大传输速度。
. 单击 * 更新 * 。
. 在 * 详细信息 * 选项卡中验证传输状态。




== 删除关系

您可以使用 System Manager 结束源卷与目标卷之间的存储关系，并从源释放 Snapshot 副本。

.关于此任务
释放此关系将永久删除源卷上存储关系使用的基本 Snapshot 副本。要重新创建存储关系，必须使用命令行界面（ CLI ）从源卷运行重新同步操作。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要删除存储关系的卷，然后单击 * 删除 * 。
. 选中确认复选框，然后单击 * 删除 * 。
+
您还可以选中释放基本 Snapshot 副本复选框以删除源卷上存储关系使用的基本 Snapshot 副本。

+
如果关系未释放，则必须使用命令行界面在源集群上运行释放操作，以便从源卷中删除为存储关系创建的基本 Snapshot 副本。





== 恢复关系

您可以使用 System Manager 恢复暂停的存储关系。恢复此关系后，系统将恢复向目标 FlexVol 卷进行的正常数据传输，并重新启动所有存储活动。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要恢复数据传输的关系，然后单击 * 操作 * > * 恢复 * 。
. 在 * 恢复 * 窗口中，单击 * 恢复 * 。


.结果
恢复正常数据传输。如果此关系已计划传输，则此传输将从下一个计划开始。



== 暂停关系

您可以使用 System Manager 通过暂停存储关系来禁用向目标 FlexVol 卷传输数据。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要停止计划的数据传输的关系，然后单击 * 操作 * > * 暂停 * 。
. 在 * 暂停 * 窗口中，单击 * 暂停 * 。


.结果
如果没有正在进行的传输，则传输状态将显示为已暂停。如果正在进行传输，则传输不会受到影响，传输状态将显示为正在暂停，直到传输完成为止。

* 相关信息 *

xref:reference_protection_window.adoc[保护窗口]
