---
permalink: online-help-96-97/task_creating_initiator_groups.html 
sidebar: sidebar 
keywords: create, initiator, group, system, manager, lun, online, help, manage, delete, edit, add 
summary: 您可以使用 System Manager 创建启动程序组。使用启动程序组可以控制主机对特定 LUN 的访问。您可以使用端口集限制启动程序可以访问的 LIF 。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本管理启动程序组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）管理启动程序组。使用启动程序组可以控制主机对特定 LUN 的访问。您可以使用端口集限制启动程序可以访问的 LIF 。



== 创建启动程序组

.步骤
. 单击 * 存储 * > * LUNs * 。
. 在 * 启动程序组 * 选项卡中，单击 * 创建 * 。
. 在 * 创建启动程序组 * 对话框的 * 常规 * 选项卡中，指定启动程序组名称，操作系统，主机别名，端口集以及该组支持的协议。
. 单击 * 创建 * 。




== 删除启动程序组

您可以使用 System Manager 中的启动程序组选项卡删除启动程序组。

.开始之前
必须手动取消映射映射映射映射到启动程序组的所有 LUN 。

.步骤
. 单击 * 存储 * > * LUNs * 。
. 在 * 启动程序组 * 选项卡中，选择要删除的一个或多个启动程序组，然后单击 * 删除 * 。
. 单击 * 删除 * 。
. 验证删除的启动程序组是否不再显示在 * 启动程序组 * 选项卡中。




== 添加启动程序

您可以使用 System Manager 将启动程序添加到启动程序组。当启动程序所属的启动程序组映射到某个 LUN 时，启动程序可提供对该 LUN 的访问权限。

.步骤
. 单击 * 存储 * > * LUNs * 。
. 在 * LUN 管理 * 选项卡中，选择要添加启动程序的启动程序组，然后单击 * 编辑 * 。
. 在 * 编辑启动程序组 * 对话框中，单击 * 启动程序 * 。
. 单击 * 添加 * 。
. 指定启动程序名称并单击 * 确定 * 。
. 单击 * 保存并关闭 * 。




== 从启动程序组中删除启动程序

您可以使用 System Manager 中的启动程序组选项卡删除启动程序。要从启动程序组中删除启动程序，必须解除启动程序与启动程序组的关联。

.开始之前
映射到包含要删除的启动程序的启动程序组的所有 LUN 都必须手动取消映射。

.步骤
. 单击 * 存储 * > * LUNs * 。
. 在 * 启动程序组 * 选项卡中，选择要从中删除启动程序的启动程序组，然后单击 * 编辑 * 。
. 在 * 编辑启动程序组 * 对话框中，单击 * 启动程序 * 选项卡。
. 从文本框中选择并删除启动程序，然后单击 * 保存 * 。
+
启动程序已与启动程序组解除关联。



* 相关信息 *

xref:reference_luns_window.adoc[LUN 窗口]
