---
permalink: online-help-96-97/task_creating_snaplock_volumes.html 
sidebar: sidebar 
keywords: create, snaplock, volume, online, help, system, manager 
summary: 您可以使用 System Manager 创建 SnapLock Compliance 卷或 SnapLock 企业卷。创建卷时，您还可以设置保留时间，并选择是否自动设置卷中数据的 WORM 状态。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本创建 SnapLock 卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP System Manager classic (适用于ONTAP 9.7及更早版本)创建SnapLock Compliance卷或SnapLock Enterprise卷。创建卷时，您还可以设置保留时间，并选择是否自动设置卷中数据的 WORM 状态。

.开始之前
* 必须已安装 SnapLock 许可证。
* SnapLock 聚合必须处于联机状态。
* 要创建加密卷，必须已使用 System Manager 安装卷加密许可证，并且已使用命令行界面（ CLI ）启用 "`key-manager setup` " 。
+
启用 "`key-manager setup` " 后，必须刷新 Web 浏览器。



.关于此任务
* 您可以删除完整的 SnapLock 企业卷或 SnapLock 企业卷中的文件；但是，您不能仅删除 SnapLock 企业卷中文件中的数据。
* 如果将数据提交到 SnapLock Compliance 卷，则无法删除该卷。
* 您不能在 Cloud Volumes ONTAP 中对卷进行加密。
* 如果在源卷上启用了加密，并且目标集群运行的 ONTAP 软件版本早于 ONTAP 9.3 ，则默认情况下，目标卷上的加密处于禁用状态。


.步骤
. 单击 * 存储 * > * 卷 * 。
. 单击 * 创建 * > * 创建 FlexVol * 。
. 浏览并选择要在其中创建卷的 Storage Virtual Machine （ SVM ）。
. 如果要更改卷的默认名称，请在 * 创建卷 * 对话框中指定新名称。
+
创建 SnapLock Compliance 卷后，您无法更改此卷的名称。

. 选择卷的容器聚合。
+
要创建 SnapLock 卷，必须选择 SnapLock 合规性聚合或 SnapLock 企业聚合。此卷会从聚合继承 SnapLock 类型，并且在创建此卷后无法更改此 SnapLock 类型；因此，您必须选择正确的聚合。

. 选中 * 卷加密 * 复选框以对卷启用加密。
+
只有在启用了卷加密许可证且相应平台能够支持加密的情况下，此选项才可用。

. 选择要为其创建此卷的存储类型。
+
如果要创建 SnapMirror 目标卷，则必须选择 * 数据保护 * 。您可以对此卷进行只读访问。

. 指定要为 Snapshot 副本预留的卷大小以及卷总大小的百分比。
+
为 SAN 卷和 VMware 卷的 Snapshot 副本预留的默认空间为 0% 。对于 NAS 卷，默认值为 5% 。

. *可选：*选择*精简配置*可为卷启用精简配置。
+
启用精简配置后，只有在将数据写入卷时，才会从聚合中为卷分配空间。

. *可选：*在*存储效率*选项卡中进行所需更改、以便在卷上启用重复数据删除。
+
System Manager 会使用默认的重复数据删除计划。如果指定的卷大小超过运行重复数据删除所需的限制，则会创建该卷，而不会启用重复数据删除。

. 选择 * SnapLock * 选项卡，然后执行以下步骤：
+
.. *可选：*指定自动提交期限。
+
在将卷中的文件提交到 WORM 状态之前，此文件在您指定的期限内保持不变。要手动将文件设置为 WORM 状态，必须选择 * 未指定 * 作为自动提交设置。

+
值必须介于 5 分钟到 10 年之间。

.. 指定最短保留期限和最长保留期限。
+
值必须介于 1 天到 70 年之间或无限范围内。

.. 选择默认保留期限。
+
默认保留期限必须在指定的最短保留期限和最长保留期限内。



. *可选：*选中*服务质量*选项卡中的*管理存储服务质量*复选框、为FlexVol 卷启用存储QoS、以便管理工作负载性能。
. 创建存储 QoS 策略组或选择现有策略组，以控制 FlexVol 卷的输入 / 输出（ I/O ）性能。
+
|===
| 如果您要 ... | 执行此操作 ... 


 a| 
创建存储 QoS 策略组
 a| 
.. 选择 * 新建策略组 * 。
.. 指定策略组名称。
.. 指定最小吞吐量限制。
+
*** 在 System Manager 9.5 中，您只能对基于性能的全闪存优化特性设置最小吞吐量限制。在 System Manager 9.6 中，您还可以为 ONTAP Select 高级系统设置最小吞吐量限制。
*** 您不能为启用了 FabricPool 的聚合上的卷设置最小吞吐量限制。
*** 如果未指定最小吞吐量值或最小吞吐量值设置为 0 ，则系统会自动显示 "`None` " 作为值。
+
此值区分大小写。



.. 指定最大吞吐量限制，以确保策略组中对象的工作负载不超过指定的吞吐量限制。
+
*** 最小吞吐量限制和最大吞吐量限制的单位类型必须相同。
*** 如果未指定最小吞吐量限制，则可以设置最大吞吐量限制，以 IOPS ， B/ 秒， KB/ 秒， MB/ 秒等为单位。
*** 如果未指定最大吞吐量值，系统将自动显示 "`无限制` " 作为值。
+
此值区分大小写。指定的单位不会影响最大吞吐量。







 a| 
选择现有策略组
 a| 
.. 选择 * 现有策略组 * ，然后单击 * 选择 * 以从 " 选择策略组 " 对话框中选择现有策略组。
.. 指定最小吞吐量限制。
+
*** 在 System Manager 9.5 中，您只能对基于性能的全闪存优化特性设置最小吞吐量限制。在 System Manager 9.6 中，您还可以为 ONTAP Select 高级系统设置最小吞吐量限制。
*** 您不能为启用了 FabricPool 的聚合上的卷设置最小吞吐量限制。
*** 如果未指定最小吞吐量值或最小吞吐量值设置为 0 ，则系统会自动显示 "`None` " 作为值。
+
此值区分大小写。



.. 指定最大吞吐量限制，以确保策略组中对象的工作负载不超过指定的吞吐量限制。
+
*** 最小吞吐量限制和最大吞吐量限制的单位类型必须相同。
*** 如果未指定最小吞吐量限制，则可以设置最大吞吐量限制，以 IOPS ， B/ 秒， KB/ 秒， MB/ 秒等为单位。
*** 如果未指定最大吞吐量值，系统将自动显示 "`无限制` " 作为值。
+
此值区分大小写。指定的单位不会影响最大吞吐量。



+
如果将策略组分配给多个对象，则指定的最大吞吐量将在这些对象之间共享。



|===
. 在 * 保护 * 选项卡中启用 * 卷保护 * 以保护卷：
. 在 * 保护 * 选项卡中，选择 * 复制 * 类型：
+
|===
| 如果选择的复制类型为 ... | 执行此操作 ... 


 a| 
异步
 a| 
.. * 可选： * 如果您不知道复制类型和关系类型，请单击 * 帮助我选择 * ，指定值，然后单击 * 应用 * 。
.. 选择关系类型。
+
关系类型可以是镜像，存储或镜像和存储。

.. 为目标卷选择一个集群和一个 SVM 。
+
如果选定集群运行的 ONTAP 软件版本早于 ONTAP 9.3 ，则仅会列出对等 SVM 。如果选定集群运行的是 ONTAP 9.3 或更高版本，则会列出对等 SVM 和允许的 SVM 。

.. 根据需要修改卷名称后缀。




 a| 
同步
 a| 
.. * 可选： * 如果您不知道复制类型和关系类型，请单击 * 帮助我选择 * ，指定值，然后单击 * 应用 * 。
.. 选择同步策略。
+
同步策略可以是 StrictSync 或 Sync 。

.. 为目标卷选择一个集群和一个 SVM 。
+
如果选定集群运行的 ONTAP 软件版本早于 ONTAP 9.3 ，则仅会列出对等 SVM 。如果选定集群运行的是 ONTAP 9.3 或更高版本，则会列出对等 SVM 和允许的 SVM 。

.. 根据需要修改卷名称后缀。


|===
. 单击 * 创建 * 。
. 验证您创建的卷是否包含在 * 卷 * 窗口的卷列表中。


.结果
此卷是使用 UNIX 安全模式创建的，其所有者拥有 UNIX 700 的 " `read write execute` " 权限。
