---
permalink: online-help-96-97/task_setting_up_cluster_using_template_file.html 
sidebar: sidebar 
keywords: set, up, cluster, template, file, system, manager, online, help, autosupport 
summary: 您可以使用 System Manager 中提供的模板文件来设置集群，方法是创建集群，设置节点管理和集群管理网络，然后设置事件通知。（从 ONTAP System Manager 9.6 开始，不支持 AutoSupport 。） 您可以下载 .xlsx 格式或 .csv 格式的模板文件。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本中的模板文件设置集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager 经典版（在 ONTAP 9.7 及更早版本中提供）中提供的模板文件来设置集群，方法是创建集群，设置节点管理和集群管理网络，然后设置事件通知。(从ONTAP系统管理器9.6开始、不支持AutoSupport。) 您可以在中下载模板文件 `.xlsx` 格式化或 `.csv` 格式。

.关于此任务
* 如果集群支持 ONTAP 9.1 或更高版本，则只能添加运行 ONTAP 9.1 或更高版本的存储系统。
* 上传文件时，不会自动填充所有字段。
+
您必须手动输入某些字段的值，例如密码和集群管理端口。



.步骤
. 打开Web浏览器、然后输入已配置的节点管理IP地址： `+https://node-management-IP+`
+
** 如果您已设置集群的凭据，则会显示登录页面。
+
您必须输入凭据才能登录。

** 如果尚未设置集群的凭据，则会显示引导式设置窗口。


. 下载 `.xlsx` 模板文件或 `.csv` 模板文件。
. 在模板文件中提供所有必需的值，然后保存该文件。
+
[NOTE]
====
** 请勿编辑模板中除值以外的任何其他列。
** 请勿更改模板文件的版本。


====
. 单击 * 浏览 * ，然后选择更新后的模板文件。
+
** 您只能在中上传模板文件 `.csv` 格式。如果您已在中下载模板文件 `.xlsx` 格式、则必须将文件另存为 `.csv` 文件、然后上传此文件。
** 您必须确保此文件使用的编码为 `UTF8`。如果不是，则不会读取这些值。


. 单击 * 上传 * 。
+
您在模板文件中提供的详细信息用于完成集群设置过程。

. 单击 * 引导式设置 * 图标可查看集群的详细信息。
. 验证 * 集群 * 窗口中的详细信息，然后单击 * 提交并继续 * 。
+
如果需要，您可以编辑集群详细信息。

+
如果您第二次登录到集群窗口，则默认情况下会启用 * 功能许可证 * 字段。您可以添加新的功能许可证密钥或保留预先填充的许可证密钥。

. 验证 * 网络 * 窗口中的详细信息，然后单击 * 提交并继续 * 。
+
如果需要，您可以编辑网络详细信息。

. 验证 * 支持 * 窗口中的详细信息，然后单击 * 提交并继续 * 。
+
如果需要，您可以编辑支持详细信息。

. 验证 * 存储 * 窗口中的详细信息，然后创建聚合或退出集群设置：
+
|===
| 如果您要 ... | 那么 ... 


 a| 
退出集群设置，而不配置存储和创建 SVM
 a| 
单击 * 跳过此步骤 * 。



 a| 
使用聚合配置存储并创建 SVM
 a| 
单击 * 提交并继续 * 。

|===
+
如果需要，您可以编辑支持详细信息。

. 验证 * 创建 Storage Virtual Machine （ SVM ） * 窗口中的详细信息，然后单击 * 提交并继续 * 。
+
如果需要，您可以编辑 SVM 名称，选择其他数据协议以及修改网络接口和适配器详细信息。

. 如果已单击 * 存储 * 窗口中的 * 跳过此步骤 * ，请在 * 摘要 * 窗口中查看详细信息，然后单击 * 管理集群 * 以启动 System Manager 。
. 如果已单击 * 存储 * 窗口中的 * 提交并继续 * ，请验证 SVM 窗口中的详细信息，然后单击 * 提交并继续 * 。
+
如果需要，您可以编辑 SVM 详细信息。

. 验证 * 摘要 * 窗口中的所有详细信息，然后单击 * 配置应用程序 * 为应用程序配置存储，或者单击 * 管理集群 * 完成集群设置过程并启动 System Manager ，或者单击 * 导出配置 * 下载配置文件。


* 相关信息 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/System_Manager_Cluster_Guided_Setup_Templates["System Manager 集群引导式设置模板"]
