---
permalink: online-help-96-97/task_editing_mirror_vault_relationships.html 
sidebar: sidebar 
keywords: edit, mirror, vault, relationship, system, manager, online, help 
summary: 您可以使用 System Manager 通过修改选定策略或计划来编辑镜像和存储关系。但是，您不能编辑现有策略或计划的参数。 
---
= 使用 System Manager 管理镜像和存储关系— ONTAP 9.7 及更早版本
:allow-uri-read: 


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）管理镜像和存储关系。您可以编辑，删除，初始化，更新，暂停， 恢复和中断镜像和存储关系。除了从目标SVM创建镜像和存储关系之外、您还可以执行重新同步或反向重新同步操作。



== 编辑关系

您可以使用 System Manager 通过修改选定策略或计划来编辑镜像和存储关系。但是，您不能编辑现有策略或计划的参数。

.开始之前
源集群和目标集群之间的对等关系必须运行正常。

.关于此任务
您可以通过修改策略类型来修改版本灵活的镜像关系，存储关系或镜像和存储关系的关系类型。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要修改的镜像和存储关系，然后单击 * 编辑 * 。
. 在 * 编辑关系 * 对话框中，选择相应的操作：
+
|===
| 如果您要 ... | 执行以下操作 ... 


 a| 
选择一个现有策略。
 a| 
单击 * 浏览 * ，然后选择现有策略。    您可以选择一个与附加到源卷的 Snapshot 策略具有最大匹配标签数的策略。



 a| 
创建新策略。
 a| 
.. 单击 * 创建策略 * 。
.. 指定策略的名称。
.. 设置计划传输的优先级。
+
low 表示传输的优先级最低，通常计划在正常优先级传输之后进行。默认情况下，优先级设置为正常。

.. 选中 * 启用网络压缩 * 复选框以压缩要传输的数据。
.. 为存储策略指定 SnapMirror 标签和目标保留计数。
+
您必须确保在源卷上创建具有相同标签的 Snapshot 副本，以使新的 SnapMirror 标签生效。

.. 单击 * 创建 * 。


|===
. 指定关系的计划：
+
|===
| 条件 | 执行以下操作 ... 


 a| 
要分配现有计划
 a| 
单击 * 浏览 * ，然后选择现有计划。



 a| 
要创建新计划
 a| 
.. 单击 * 创建计划 * 。
.. 指定计划的名称。
.. 选择以下选项之一：
+
*** * 基本 *
+
您可以选择此选项以仅指定一周中的某一天，时间和传输间隔。

*** * 高级 *
+
您可以选择此选项以指定 cron 模式的计划。



.. 单击 * 创建 * 。




 a| 
您不想分配计划
 a| 
选择 * 无 * 。

|===
. 单击 * 确定 * 。




== 手动更新关系

您可以使用 System Manager 手动启动计划外增量更新。您可能需要手动更新，以防止因即将发生断电，计划内维护或数据迁移而导致数据丢失。

.开始之前
镜像和存储关系必须已初始化且处于 Snapmirrored 状态。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要更新数据的镜像关系，然后单击 * 操作 * > * 更新 * 。
. 选择以下选项之一：
+
** 选择 * 按策略 * 可从源卷和目标卷之间的最新通用 Snapshot 副本执行增量传输。
** 选择 * 选择 Snapshot 副本 * 并指定要传输的 Snapshot 副本。


. 选择 * 将传输带宽限制为 * 以限制用于传输的网络带宽，然后指定最大传输速度。
. 单击 * 更新 * 。
. 在 * 详细信息 * 选项卡中验证传输状态。




== 初始化关系

如果在创建镜像和存储关系时尚未初始化此关系，则可以使用 System Manager 对其进行初始化。初始化关系时，系统会从源卷向目标卷执行完整的基线数据传输。

.开始之前
源集群和目标集群之间的对等关系必须运行正常。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要初始化的镜像和存储关系，然后单击 * 操作 * > * 初始化 * 。
. 选中确认复选框，然后单击 * 初始化 * 。
. 在 * 保护 * 窗口中验证关系的状态。


.结果
此时将创建一个 Snapshot 副本并将其传输到目标。

此 Snapshot 副本用作后续增量 Snapshot 副本的基线。



== 从目标 SVM 创建关系

您可以使用 System Manager 从目标 Storage Virtual Machine （ SVM ）创建镜像和存储关系。通过创建此关系，您可以定期将数据从源卷传输到目标卷，从而更好地保护数据。此外，您还可以通过创建源卷的备份来长期保留数据。

.开始之前
* 目标集群必须运行 ONTAP 8.3.2 或更高版本。
* 必须在源集群和目标集群上启用 SnapMirror 许可证。
+
[NOTE]
====
对于某些平台，如果目标集群启用了 SnapMirror 许可证和数据保护优化（ DPO ）许可证，则源集群不必启用 SnapMirror 许可证。

====
* 源集群和目标集群之间的对等关系必须运行正常。
* 目标 SVM 必须具有可用空间。
* 源聚合和目标聚合必须是 64 位聚合。
* 必须已存在读 / 写（ rw ）类型的源卷。
* SnapLock 聚合类型必须相同。
* 如果要从运行 ONTAP 9.2 或更早版本的集群连接到启用了 SAML 身份验证的远程集群，则必须在远程集群上启用基于密码的身份验证。


.关于此任务
* System Manager 不支持级联关系。
+
例如，关系中的目标卷不能是另一关系中的源卷。

* 您不能在 MetroCluster 配置中 sync-source SVM 和 sync-destination SVM 之间创建镜像和存储关系。
* 您可以在 MetroCluster 配置中 sync-source SVM 之间创建镜像和存储关系。
* 您可以创建从 sync-source SVM 上的卷到提供数据的 SVM 上的卷的镜像和存储关系。
* 您可以创建从提供数据的 SVM 上的卷到 sync-source SVM 上的 DP 卷的镜像和存储关系。
* 一次选择最多可以保护 25 个卷。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 在 * 关系 * 窗口中，单击 * 创建 * 。
. 在 * 浏览 SVM* 对话框中，为目标卷选择一个 SVM 。
. 在 * 创建保护关系 * 对话框中，从 * 关系类型 * 下拉列表中选择 * 镜像和存储 * 。
. 指定集群， SVM 和源卷。
+
如果指定集群运行的 ONTAP 软件版本早于 ONTAP 9.3 ，则仅会列出对等 SVM 。如果指定集群运行的是 ONTAP 9.3 或更高版本，则会列出对等 SVM 和允许的 SVM 。

. 输入卷名称后缀。
+
卷名称后缀会附加到源卷名称中，以生成目标卷名称。

. *可选：*单击*浏览*、然后更改镜像和存储策略。
+
您可以选择与附加到源卷的 Snapshot 策略具有最大匹配标签数的策略。

. 从现有计划列表中为此关系选择一个计划。
. *可选：*选择*初始化关系*以初始化此关系。
. 启用启用启用了 FabricPool 的聚合，然后选择适当的分层策略。
. 单击 * 验证 * 以验证选定卷是否具有匹配标签。
. 单击 * 创建 * 。




== 重新同步关系

您可以使用 System Manager 重新建立先前已断开的镜像和存储关系。您可以执行重新同步操作，以便从禁用源卷的灾难中恢复。

.开始之前
源和目标集群以及源和目标 Storage Virtual Machine （ SVM ）必须处于对等关系。

.关于此任务
在执行重新同步操作之前，应注意以下事项：

* 执行重新同步操作时，目标卷上的内容将被源卷上的内容覆盖。
+
[NOTE]
====
重新同步操作可能发生原因会在创建基本 Snapshot 副本后丢失写入目标卷的较新数据。

====
* 如果保护窗口中的上次传输错误字段建议执行重新同步操作，则必须先中断此关系，然后再执行重新同步操作。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要重新同步的镜像和存储关系，然后单击 * 操作 * > * 重新同步 * 。
. 选中确认复选框，然后单击 * 重新同步 * 。




== 反向重新同步关系

您可以使用 System Manager 重新建立先前已断开的镜像和存储关系。在反向重新同步操作中，源卷和目标卷的功能将发生反转。在修复或替换源卷，更新源卷以及重新建立系统的原始配置时，您可以使用目标卷提供数据。

.开始之前
源卷必须处于联机状态。

.关于此任务
* 执行反向重新同步时，源卷上的内容将被目标卷上的内容覆盖。
+
[NOTE]
====
反向重新同步操作可能会使源卷上的数据丢失发生原因。

====
* 执行反向重新同步时，此关系的策略将设置为 MirrorAndVault ，而计划将设置为无。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要反转的镜像和存储关系，然后单击 * 操作 * > * 反向重新同步 * 。
. 选中确认复选框，然后单击 * 反向重新同步 * 。




== 中断关系

如果源卷不可用，并且您希望客户端应用程序从目标卷访问数据，则可以使用 System Manager 中断镜像和存储关系。在修复或替换源卷，更新源卷以及重新建立系统的初始配置时，您可以使用目标卷提供数据。

.开始之前
* 镜像和存储关系必须处于已暂停或闲置状态。
* 目标卷必须挂载到目标 Storage Virtual Machine （ SVM ）命名空间上。


.关于此任务
您可以中断 ONTAP 系统和 SolidFire 存储系统之间的镜像关系。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要中断的镜像和存储关系，然后单击 * 操作 * > * 中断 * 。
. 选中确认复选框，然后单击 * 中断 * 。


.结果
镜像和存储关系已断开。目标卷类型从数据保护（ DP ）只读更改为读 / 写。系统会存储镜像和存储关系的基本 Snapshot 副本，以供日后使用。



== 恢复关系

如果您具有暂停的镜像和存储关系，则可以使用 System Manager 恢复此关系。恢复此关系后，系统将恢复向目标卷进行的正常数据传输，并重新启动所有保护活动。

.关于此任务
如果已从命令行界面（ CLI ）暂停已断开的镜像和存储关系，则无法从 System Manager 恢复此关系。您必须使用命令行界面恢复此关系。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要恢复的镜像和存储关系，然后单击 * 操作 * > * 恢复 * 。
. 选中确认复选框，然后单击 * 恢复 * 。


.结果
恢复正常数据传输。如果此关系已计划传输，则此传输将从下一个计划开始。



== 删除关系

您可以使用 System Manager 结束源卷与目标卷之间的镜像和存储关系，并从源卷释放 Snapshot 副本。

.关于此任务
* 删除镜像和存储关系之前，最好先断开此关系。
* 要重新创建此关系，必须使用命令行界面（ CLI ）从源卷运行重新同步操作。


.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要删除的镜像和存储关系，然后单击 * 删除 * 。
. 选中确认复选框，然后单击 * 删除 * 。
+
您还可以选中释放基本 Snapshot 副本复选框，以删除源卷上的镜像和存储关系使用的基本 Snapshot 副本。

+
如果关系未释放，则必须使用命令行界面在源集群上运行释放操作，以便从源卷中删除为镜像和存储关系创建的基本 Snapshot 副本。



.结果
此关系将被删除，并且源卷上的基本 Snapshot 副本将被永久删除。



== 暂停关系

在创建 Snapshot 副本之前，您可以使用 System Manager 暂停目标卷以使目标保持稳定。暂停操作可以完成镜像和存储关系的活动数据传输，并禁用以后的传输。

.开始之前
镜像和存储关系必须处于 Snapmirrored 状态。

.步骤
. 单击 * 保护 * > * 卷关系 * 。
. 选择要暂停的镜像和存储关系，然后单击 * 操作 * > * 暂停 * 。
. 选中确认复选框，然后单击 * 暂停 * 。


.结果
如果没有正在进行的传输、则传输状态将显示为 `Quiesced`。如果正在进行传输、则传输不会受到影响、传输状态将显示为 `Quiescing` 直到传输完成。
