---
permalink: online-help-96-97/task_updating_single_node_clusters.html 
sidebar: sidebar 
keywords: update, singe, node, cluster, system, manager, online, help 
summary: 您可以使用 System Manager 更新单节点集群。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本更新单节点集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）更新单节点集群。

.开始之前
* 集群必须运行ONTAP 9.4或更高版本。
* 您必须已将软件映像从 NetApp 支持站点复制到网络上的 HTTP 服务器，网络上的 FTP 服务器或本地系统，以便节点可以访问此映像。
+
link:task_obtaining_ontap_software_images.html["获取 ONTAP 软件映像"]



.关于此任务
* 从 System Manager 9.5 开始，您可以更新双组件 MetroCluster 配置中的单节点集群。
+
您必须在这两个站点上执行此操作。

* 更新 MetroCluster 配置中的单节点集群不会造成系统中断。
+
集群重新启动时， System Manager 用户界面不可用。

* 在 System Manager 9.4 及更高版本中，您可以更新非 MetroCluster 配置中的单节点集群。
+
更新非 MetroCluster 配置中的单节点集群会造成系统中断。更新期间，客户端数据不可用。

* 如果在更新托管集群管理 LIF 的节点时尝试执行其他任务，则可能会显示一条错误消息。
+
您必须等待更新完成，然后才能执行任何操作。

* 如果在 System Manager 9.4 中配置了 NVMe 协议，并且您从 System Manager 9.4 更新到 System Manager 9.5 ，则 NVMe 协议将在没有许可证的情况下提供 90 天的宽限期。
+
此功能在 MetroCluster 配置中不可用。

* 如果未在 System Manager 9.5 中配置 NVMe 协议，而您从 System Manager 9.5 更新到 System Manager 9.6 ，则不会提供宽限期，您必须安装 NVMe 许可证才能使用 NVMe 协议。
+
此功能在 MetroCluster 配置中不可用。



.步骤
. 单击 * 配置 * > * 集群 * > * 更新 * 。
. 在 * 集群更新 * 选项卡中，添加新的软件映像或选择可用的软件映像。
+
|===
| 如果您要 ... | 那么 ... 


 a| 
从本地客户端添加新软件映像
 a| 
.. 单击 * 从本地客户端添加 * 。
.. 搜索软件映像，然后单击 * 打开 * 。




 a| 
从 NetApp 支持站点添加新的软件映像
 a| 
.. 单击 * 从服务器添加 * 。
.. 在添加新软件映像对话框中，输入用于保存从 NetApp 支持站点下载的映像的 HTTP 服务器或 FTP 服务器的 URL。
+
对于匿名 FTP ，必须在中指定 URL `+ftp://anonymous@ftpserver+` 格式。

.. 单击 * 添加 * 。




 a| 
选择一个可用映像
 a| 
从列出的映像中选择一个。

|===
. 单击 * 验证 * 以运行更新前验证检查，以验证集群是否已做好更新准备。
+
验证操作将检查集群组件以验证是否可以完成更新，然后显示任何错误或警告。验证操作还会显示更新软件之前必须执行的任何必要补救措施。

+
[NOTE]
====
在继续更新之前，您必须针对这些错误执行所有必要的补救措施。尽管您可以忽略警告的补救措施，但最佳做法是在继续更新之前执行所有补救措施。

====
. 单击 * 下一步 * 。
. 单击 * 更新 * 。
+
此时将再次执行验证。

+
** 验证完成后，一个表将显示任何错误和警告，以及继续操作前需要采取的任何补救措施。
** 如果验证完成后出现警告，您可以选择 * 继续出现警告的更新 * 复选框，然后单击 * 继续 * 。
验证完成且更新正在进行中时，更新可能会因错误而暂停。您可以单击错误消息以查看详细信息，然后执行补救措施，然后再恢复更新。


+
更新成功完成后，节点将重新启动，您将重定向到 System Manager 登录页面。如果节点重新启动需要很长时间，则必须刷新浏览器。

. 登录到 System Manager ，单击 * 配置 * > * 集群 * > * 更新 * > * 更新历史记录 * ，然后查看详细信息，以验证集群是否已成功更新到选定版本。

