---
permalink: online-help-96-97/task_creating_qos_policy_groups.html 
sidebar: sidebar 
keywords: online, help, create, qos, policy, groups, system, manager, quality, service 
summary: 您可以使用 System Manager 创建存储服务质量（ QoS ）策略组，以限制工作负载的吞吐量并监控工作负载性能。 
---
= 使用System Manager - ONTAP 9.7及更早版本管理QoS策略组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）创建存储服务质量（ QoS ）策略组，以限制工作负载的吞吐量并监控工作负载性能。



== 创建 QoS 策略组

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 策略 * 窗格中，单击 * QoS 策略组 * 。
. 在 * QoS 策略组 * 窗口中，单击 * 创建 * 。
. 在 * 创建策略组 * 对话框中，指定策略的组名称。
. 指定最小吞吐量限制。
+
** 在 System Manager 9.5 中，您只能对基于性能的全闪存优化特性设置最小吞吐量限制。在 System Manager 9.6 中，您还可以为 ONTAP Select 高级系统设置最小吞吐量限制。
** 您不能为启用了 FabricPool 的聚合上的卷设置最小吞吐量限制。
** 如果未指定最小吞吐量值或最小吞吐量值设置为 0 ，则系统会自动显示 "`None` " 作为值。
+
此值区分大小写。



. 指定最大吞吐量限制。
+
** 最小吞吐量限制和最大吞吐量限制的单位类型必须相同。
** 如果未指定最小吞吐量限制，则可以设置最大吞吐量限制，以 IOPS 和 B/ 秒， KB/ 秒， MB/ 秒等为单位。
** 如果未指定最大吞吐量限制，则系统会自动显示 "`无限制` " 作为值。
+
此值区分大小写。指定的单位不会影响最大吞吐量。



. 单击 * 确定 * 。




== 删除 QoS 策略组

您可以使用 ONTAP System Manager classic （适用于 ONTAP 9.7 及更早版本）删除不再需要的存储服务质量（ QoS ）策略组。

.开始之前
您必须已取消分配分配分配给策略组的所有存储对象。

.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 策略 * 窗格中，单击 * QoS 策略组 * 。
. 在 * QoS 策略组 * 窗口中，选择要删除的策略组，然后单击 * 删除 * 。
. 在确认对话框中，单击 * 删除 * 。




== 编辑 QoS 策略组

您可以使用 ONTAP System Manager classic （在 ONTAP 9.7 及更早版本中提供）中的编辑策略组对话框修改现有存储服务质量（ QoS ）策略组的名称和最大吞吐量。

.关于此任务
* 在 System Manager 9.5 中，您只能对基于性能的全闪存优化特性设置最小吞吐量限制。在 System Manager 9.6 中，您还可以为 ONTAP Select 高级系统设置最小吞吐量限制。
* 您不能为启用了 FabricPool 的聚合上的卷设置最小吞吐量限制。


.步骤
. 单击 * 存储 * > * SVMs * 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 策略 * 窗格中，单击 * QoS 策略组 * 。
. 选择要编辑的 QoS 策略组，然后单击 * 编辑 * 。
+
** 最小吞吐量限制和最大吞吐量限制的单位类型必须相同。
** 如果未指定最小吞吐量限制，则可以设置最大吞吐量限制，以 IOPS 和 B/ 秒， KB/ 秒， MB/ 秒等为单位。
** 如果未指定最大吞吐量限制，则此值将设置为无限制，而您指定的单位不会影响最大吞吐量。


. 在 * 编辑策略组 * 对话框中，编辑 QoS 策略组详细信息，然后单击 * 保存 * 。

