---
permalink: online-help-96-97/task_configuring_iscsi_protocol_on_svms.html 
sidebar: sidebar 
keywords: system, manager, iscsi, protocol, svm, online, help, lif, portset 
summary: 您可以使用 System Manager 在 Storage Virtual Machine （ SVM\ ）上配置 iSCSI 协议，以提供块级数据访问。您可以创建 iSCSI LIF 和端口集，然后将 LIF 添加到端口集。LIF 在最合适的适配器上创建，并分配给端口集，以确保数据路径冗余。 
---
= 使用 System Manager - ONTAP 9.7 及更早版本在 SVM 上配置 iSCSI 协议
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP System Manager classic (适用于ONTAP 9.7及更早版本)在Storage Virtual Machine (SVM)上配置iSCSI协议、以提供块级数据访问。您可以创建 iSCSI LIF 和端口集，然后将 LIF 添加到端口集。LIF 在最合适的适配器上创建，并分配给端口集，以确保数据路径冗余。

.开始之前
* 必须在集群上启用 iSCSI 许可证。
+
如果 SVM 上未启用 iSCSI 协议，您可以使用编辑 Storage Virtual Machine 窗口为 SVM 启用该协议。

* 集群中的所有节点都必须运行状况良好。
* 每个节点必须至少具有两个数据端口、并且端口状态必须为 `up`。


.关于此任务
* 您可以在创建 SVM 时配置 iSCSI 协议，也可以稍后进行配置。
* 自动创建卷时不考虑 SnapLock 聚合。


.步骤
. 如果在创建 SVM 时未配置 iSCSI 协议，请单击 * 存储 * > * SVM* 。
. 选择 SVM ，然后单击 * SVM 设置 * 。
. 在 * 协议 * 窗格中，单击 * iSCSI * 。
. *可选：*在*网络访问*部分中、指定iSCSI目标的别名。
+
别名的最大字符数为 128 。如果不指定目标别名，则会使用 SVM 名称作为别名。

. 指定可分配给单个节点的 iSCSI LIF 的数量。
+
每个节点的 LIF 最小数量为 1 。最大数量是中所有端口的最小数量 `up` 跨节点的状态。如果最大值是一个奇数，则会将先前的偶数视为最大值。您可以选择最小值和最大值范围内的任意偶数。

+
一个4节点集群中有node1、node2和node3、每个端口都有六个 `up` 状态和node4、其中有七个端口 `up` 状态。集群的有效最大值为 6 。

+
如果要分配给节点的 LIF 数量超过两个，则必须为每个 LIF 至少分配一个端口集。

. 指定网络详细信息（包括子网详细信息）以创建 iSCSI LIF ：
+
|===
| 如果您要 ... | 那么 ... 


 a| 
使用子网指定 IP 地址
 a| 
.. 选择 * 使用子网 * 。
.. 在添加详细信息对话框中，选择必须从中分配 IP 地址的子网。
+
对于集群间 LIF ，仅显示与选定 IP 空间关联的子网。

.. 如果要为接口分配特定 IP 地址，请选择 * 使用特定 IP 地址 * ，然后键入 IP 地址。
+
如果您指定的 IP 地址尚未位于子网范围内，则会将此 IP 地址添加到子网中。

.. 单击 * 确定 * 。




 a| 
手动指定 IP 地址，而不使用子网
 a| 
.. 选择 * 不使用子网 * 。
.. 在添加详细信息对话框中，执行以下步骤：
+
... 指定 IP 地址和网络掩码或前缀。
... 可选：指定网关。
... 如果不想对目标字段使用默认值，请指定新的目标值。
+
如果不指定目标值，则目标字段将根据 IP 地址系列填充默认值。



+
如果路由不存在，则会根据网关和目标自动创建新路由。

.. 单击 * 确定 * 。


|===
. 选择广播域。
. 选择适配器类型。
+
如果集群中配置了 NIC 卡，则应选择 * NIC * 。

+
如果集群中配置了 CNS 卡，则应选择 * CNA* 。

+
如果集群中配置了 ifgrp ，则应选择 * 接口组 * 。

+
[NOTE]
====
必须在广播域中添加 ifgrp 端口。

====
. *可选：*通过指定LUN大小、LUN的操作系统类型以及主机启动程序详细信息、在配置iSCSI协议时为iSCSI存储配置LUN。
. 如果要验证或修改自动生成的 iSCSI LIF 的配置，请选择 * 查看或修改 LIF 配置（高级设置） * 。
+
您只能修改 LIF 名称和主端口。默认情况下，端口集设置为最小值。必须指定唯一条目。如果指定重复的 LIF 名称， System Manager 会将数字值附加到重复的 LIF 名称。

+
根据选定的端口集， LIF 会通过轮循方法分布在各个端口集之间，以确保在发生节点故障或端口故障时实现冗余。

. 单击 * 提交并继续 * 。


.结果
iSCSI LIF 和端口集是使用指定配置创建的。LIF 会根据选定的端口集分布在各个端口集之间。如果所有 LIF 均已成功创建，则 iSCSI 服务将启动。

如果 LIF 创建失败，您可以使用网络接口窗口创建 LIF ，使用 LUN 窗口将 LIF 附加到端口集，然后使用 iSCSI 窗口启动 iSCSI 服务。
