---
permalink: fc-config-esxi/index.html 
sidebar: sidebar 
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, hba, esx, host, computer, virtual storage console, vsc 
summary: 使用 ONTAP System Manager 经典界面（ ONTAP 9.7 及更早版本），您可以在 Storage Virtual Machine （ SVM ）上快速设置 FC 服务，配置 LUN ，并使用 ESX 主机计算机上的 FC HBA 将 LUN 用作数据存储库。 
---
= 使用 VSC 为 ESXi 配置 FC 概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 ONTAP System Manager 经典界面（ ONTAP 9.7 及更早版本），您可以在 Storage Virtual Machine （ SVM ）上快速设置 FC 服务，配置 LUN ，并使用 ESX 主机计算机上的 FC HBA 将 LUN 用作数据存储库。

在以下情况下使用此操作步骤：

* 您正在使用受支持版本的适用于 VMware vSphere 的 Virtual Storage Console （ VSC ）为 ESX 主机配置存储设置并配置数据存储库。
+
** 从 VSC 7.0 开始， VSC 属于 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["适用于 VMware vSphere 的 ONTAP 工具"^] 虚拟设备，包括适用于 VMware vSphere 的 VSC ， vStorage APIs for Storage Awareness （ VASA ） Provider 和 Storage Replication Adapter （ SRA ）功能。
** 请务必检查 https://imt.netapp.com/matrix/["NetApp 互操作性表工具"^] 以确认当前 ONTAP 版本与 VSC 版本之间的兼容性。


* 您的网络使用 IPv4 地址。
* 您正在 ESXi 5.x 和传统 FC 交换机上使用传统 FC HBA 。
+
此操作步骤不包括 FCoE 。

* 集群中的每个节点上至少有两个可用的 FC 目标端口。
+
板载 FC 和 UTA2 （也称为 "`CNA` " ）端口以及某些适配器均可配置。这些端口的配置会在 ONTAP 命令行界面中完成，此操作步骤不会对此进行介绍。

* 您未配置 FC SAN 启动。
* 您正在主机上创建数据存储库。
+
此操作步骤不包括原始设备映射（ RDM ）磁盘或使用 N 端口 ID 虚拟化（ NPIV ）直接为 VM 提供 FC 。



有关详细信息，请参见 https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597 ：适用于 ONTAP 的 VMware vSphere"^] 以及适用于您的 VSC 版本的文档。
